// config.bin - 18:21:26 09/04/19, generated in 0.11 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define public		0
#define protected		1
#define public		2

class CfgPatches {
	class COS_gilet {
		units[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {};
		version = 20-05-2016;
		author = "Sakuraba_and_author_in_credits";
	};
};

class UniformSlotInfo {
	slotType = 0;
	linkProxy = "-";
};

class cfgWeapons {
	class Vest_NoCamo_Base;	// External class reference
	class ItemCore;	// External class reference
	class InventoryItem_Base_F;	// External class reference
	class Item_Base_F;	// External class reference
	class VestItem;	// External class reference
	class V_RebreatherB;	// External class reference
	class Pistol;	// External class reference
	
	class Pistol_Base_F : Pistol {
		class WeaponSlotsInfo;	// External class reference
	};
	
	class MyLittlePistol : Pistol_Base_F {
		class WeaponSlotsInfo : WeaponSlotsInfo {
			holsterOffset = "holster";
			holsterScale = 0.95;
		};
	};
	
	class RECYCLEUR_FULL_TL : V_RebreatherB {
		author = "Splendid Modder";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		_generalMacro = RECYCLEUR_FULL_TL;
		displayName = ".RECYCLEUR  [Fns]";
		allowedSlots[] = {901};
		picture = "\COS_gilet\data\icon\ic.recycleur.ca.paa";
		model = "\COS_gilet\RECYCLEUR";
		hiddenUnderwaterSelections[] = {"hide"};
		shownUnderwaterSelections[] = {"unhide", "unhide2"};
		hiddenUnderwaterSelectionsTextures[] = {"COS_gilet\data\HALO\DIVER_KIT_co.paa", "\COS_gilet\data\HALO\DIVER_KIT_co.paa", "A3\characters_f\data\visors_ca.paa"};
		
		class ItemInfo : VestItem {
			uniformModel = "\COS_gilet\RECYCLEUR_FULL";
			vestType = "Rebreather";
			hiddenUnderwaterSelections[] = {"hide"};
			shownUnderwaterSelections[] = {"unhide", "unhide2"};
			hiddenUnderwaterSelectionsTextures[] = {"COS_gilet\data\HALO\DIVER_KIT_co.paa", "\COS_gilet\data\HALO\DIVER_KIT_co.paa", "A3\characters_f\data\visors_ca.paa"};
			picture = "\COS_gilet\data\icon\ic.recycleur.ca.paa";
			containerClass = "Supply0";
			mass = 95;
		};
	};
	
	class RECYCLEUR_B : V_RebreatherB {
		author = "Splendid Modder";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		_generalMacro = RECYCLEUR_FULL_B;
		displayName = ".RECYCLEUR  [No Fns]";
		allowedSlots[] = {901};
		picture = "\COS_gilet\data\icon\ic.recycleur.ca.paa";
		model = "\COS_gilet\RECYCLEUR";
		hiddenUnderwaterSelections[] = {"hide"};
		shownUnderwaterSelections[] = {"unhide", "unhide2"};
		hiddenUnderwaterSelectionsTextures[] = {"COS_gilet\data\HALO\DIVER_KIT_co.paa", "\COS_gilet\data\HALO\DIVER_KIT_co.paa", "A3\characters_f\data\visors_ca.paa"};
		
		class ItemInfo : VestItem {
			uniformModel = "\COS_gilet\RECYCLEUR";
			vestType = "Rebreather";
			hiddenUnderwaterSelections[] = {"hide"};
			shownUnderwaterSelections[] = {"unhide", "unhide2"};
			hiddenUnderwaterSelectionsTextures[] = {"COS_gilet\data\HALO\DIVER_KIT_co.paa", "\COS_gilet\data\HALO\DIVER_KIT_co.paa", "A3\characters_f\data\visors_ca.paa"};
			picture = "\COS_gilet\data\icon\ic.recycleur.ca.paa";
			containerClass = "Supply0";
			mass = 95;
		};
	};
	
	class JPC_1_TAN : Vest_NoCamo_Base {
		author = "Splendid Modder";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		_generalMacro = JPC_1_TAN;
		displayName = ".JPC 1 TAN";
		picture = "COS_gilet\data\icon\ic_vest_fs.ca.paa";
		allowedSlots[] = {901};
		model = "\COS_gilet\JPC_1";
		hiddenSelections[] = {"camo1", "camo2", "camo3", "camo4", "camo5"};
		hiddenSelectionsTextures[] = {"COS_gilet\data\JPC\CRYE_JPC_TAN.co.paa", "cos_gilet\data\poches\POCHE_coy.co.paa", "cos_gilet\data\poches\POCHE2_coy.co.paa", "cos_gilet\data\poches\assets_strap_tan.co.paa", "cos_gilet\data\poches\afam_radio_tan.co.paa"};
		hiddenSelectionsMaterials[] = {};
		
		class ItemInfo : VestItem {
			uniformModel = "\COS_gilet\JPC_1";
			hiddenSelections[] = {"camo1", "camo2", "camo3", "camo4", "camo5"};
			hiddenSelectionsTextures[] = {"COS_gilet\data\JPC\CRYE_JPC_TAN.co.paa", "cos_gilet\data\poches\POCHE_coy.co.paa", "cos_gilet\data\poches\POCHE2_coy.co.paa", "cos_gilet\data\poches\assets_strap_tan.co.paa", "cos_gilet\data\poches\afam_radio_tan.co.paa"};
			containerClass = "Supply200";
			picture = "COS_gilet\data\icon\ic_vest_fs.ca.paa";
			mass = 50;
			passThrough = "true";
			
			class HitpointsProtectionInfo {
				class Chest {
					HitpointName = "HitChest";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Diaphragm {
					HitpointName = "HitDiaphragm";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 25;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					passThrough = 0.3;
				};
			};
		};
	};
	
	class JPC_1_OD : Vest_NoCamo_Base {
		author = "Splendid Modder";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		_generalMacro = JPC_1_OD;
		displayName = ".JPC OD";
		picture = "COS_gilet\data\icon\ic_vest_fs.ca.paa";
		model = "\COS_gilet\JPC_1";
		hiddenSelections[] = {};
		hiddenSelectionsTextures[] = {};
		hiddenSelectionsMaterials[] = {};
		
		class ItemInfo : VestItem {
			uniformModel = "\COS_gilet\JPC_1";
			hiddenSelections[] = {};
			containerClass = "Supply200";
			picture = "COS_gilet\data\icon\ic_vest_fs.ca.paa";
			mass = 50;
			passThrough = "true";
			
			class HitpointsProtectionInfo {
				class Chest {
					HitpointName = "HitChest";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Diaphragm {
					HitpointName = "HitDiaphragm";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 25;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					passThrough = 0.3;
				};
			};
		};
	};
	
	class JPC_2_TAN : Vest_NoCamo_Base {
		author = "Splendid Modder";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		_generalMacro = JPC_2_TAN;
		displayName = ".JPC 2 TAN";
		picture = "COS_gilet\data\icon\ic_vest_fs.ca.paa";
		model = "\COS_gilet\JPC_2";
		hiddenSelections[] = {"camo1", "camo2", "camo3", "camo4", "camo5"};
		hiddenSelectionsTextures[] = {"COS_gilet\data\JPC\CRYE_JPC_TAN.co.paa", "cos_gilet\data\poches\POCHE_coy.co.paa", "cos_gilet\data\poches\POCHE2_coy.co.paa", "cos_gilet\data\poches\assets_strap_tan.co.paa", "cos_gilet\data\poches\afam_radio_tan.co.paa"};
		hiddenSelectionsMaterials[] = {};
		
		class ItemInfo : VestItem {
			uniformModel = "\COS_gilet\JPC_2";
			hiddenSelections[] = {"camo1", "camo2", "camo3", "camo4", "camo5"};
			hiddenSelectionsTextures[] = {"COS_gilet\data\JPC\CRYE_JPC_TAN.co.paa", "cos_gilet\data\poches\POCHE_coy.co.paa", "cos_gilet\data\poches\POCHE2_coy.co.paa", "cos_gilet\data\poches\assets_strap_tan.co.paa", "cos_gilet\data\poches\afam_radio_tan.co.paa"};
			containerClass = "Supply200";
			picture = "COS_gilet\data\icon\ic_vest_fs.ca.paa";
			mass = 50;
			passThrough = "true";
			
			class HitpointsProtectionInfo {
				class Chest {
					HitpointName = "HitChest";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Diaphragm {
					HitpointName = "HitDiaphragm";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 25;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					passThrough = 0.3;
				};
			};
		};
	};
	
	class JPC_2_OD : Vest_NoCamo_Base {
		author = "Splendid Modder";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		_generalMacro = JPC_2_OD;
		displayName = ".JPC 2 OD";
		picture = "COS_gilet\data\icon\ic_vest_fs.ca.paa";
		model = "\COS_gilet\JPC_2";
		hiddenSelections[] = {};
		hiddenSelectionsTextures[] = {};
		hiddenSelectionsMaterials[] = {};
		
		class ItemInfo : VestItem {
			uniformModel = "\COS_gilet\JPC_2";
			hiddenSelections[] = {};
			containerClass = "Supply200";
			picture = "COS_gilet\data\icon\ic_vest_fs.ca.paa";
			mass = 50;
			passThrough = "true";
			
			class HitpointsProtectionInfo {
				class Chest {
					HitpointName = "HitChest";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Diaphragm {
					HitpointName = "HitDiaphragm";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 25;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					passThrough = 0.3;
				};
			};
		};
	};
	
	class JPC_3_TAN : Vest_NoCamo_Base {
		author = "Splendid Modder";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		_generalMacro = JPC_3_TAN;
		displayName = ".JPC 3 TAN";
		picture = "COS_gilet\data\icon\ic_vest_fs.ca.paa";
		model = "\COS_gilet\JPC_3";
		hiddenSelections[] = {"camo1", "camo2", "camo3", "camo4", "camo5"};
		hiddenSelectionsTextures[] = {"COS_gilet\data\JPC\CRYE_JPC_TAN.co.paa", "cos_gilet\data\poches\POCHE_coy.co.paa", "cos_gilet\data\poches\POCHE2_coy.co.paa", "cos_gilet\data\poches\assets_strap_tan.co.paa", "cos_gilet\data\poches\afam_radio_tan.co.paa"};
		hiddenSelectionsMaterials[] = {};
		
		class ItemInfo : VestItem {
			uniformModel = "\COS_gilet\JPC_3";
			hiddenSelections[] = {"camo1", "camo2", "camo3", "camo4", "camo5"};
			hiddenSelectionsTextures[] = {"COS_gilet\data\JPC\CRYE_JPC_TAN.co.paa", "cos_gilet\data\poches\POCHE_coy.co.paa", "cos_gilet\data\poches\POCHE2_coy.co.paa", "cos_gilet\data\poches\assets_strap_tan.co.paa", "cos_gilet\data\poches\afam_radio_tan.co.paa"};
			containerClass = "Supply200";
			picture = "COS_gilet\data\icon\ic_vest_fs.ca.paa";
			mass = 50;
			passThrough = "true";
			
			class HitpointsProtectionInfo {
				class Chest {
					HitpointName = "HitChest";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Diaphragm {
					HitpointName = "HitDiaphragm";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 25;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					passThrough = 0.3;
				};
			};
		};
	};
	
	class JPC_3_OD : Vest_NoCamo_Base {
		author = "modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		_generalMacro = JPC_3_OD;
		displayName = ".JPC 3 OD";
		picture = "COS_gilet\data\icon\ic_vest_fs.ca.paa";
		model = "\COS_gilet\JPC_3";
		hiddenSelections[] = {};
		hiddenSelectionsTextures[] = {};
		hiddenSelectionsMaterials[] = {};
		
		class ItemInfo : VestItem {
			uniformModel = "\COS_gilet\JPC_3";
			hiddenSelections[] = {};
			containerClass = "Supply200";
			picture = "COS_gilet\data\icon\ic_vest_fs.ca.paa";
			mass = 50;
			passThrough = "true";
			
			class HitpointsProtectionInfo {
				class Chest {
					HitpointName = "HitChest";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Diaphragm {
					HitpointName = "HitDiaphragm";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 25;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					passThrough = 0.3;
				};
			};
		};
	};
	
	class JPC_4_TAN : Vest_NoCamo_Base {
		author = "modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		_generalMacro = JPC_4_TAN;
		displayName = ".JPC 4 TAN";
		picture = "COS_gilet\data\icon\ic_vest_fs.ca.paa";
		model = "\COS_gilet\JPC_4";
		hiddenSelections[] = {"camo1", "camo2", "camo3", "camo4", "camo5"};
		hiddenSelectionsTextures[] = {"COS_gilet\data\JPC\CRYE_JPC_TAN.co.paa", "cos_gilet\data\poches\POCHE_coy.co.paa", "cos_gilet\data\poches\POCHE2_coy.co.paa", "cos_gilet\data\poches\assets_strap_tan.co.paa", "cos_gilet\data\poches\afam_radio_tan.co.paa"};
		hiddenSelectionsMaterials[] = {};
		
		class ItemInfo : VestItem {
			uniformModel = "\COS_gilet\JPC_4";
			hiddenSelections[] = {"camo1", "camo2", "camo3", "camo4", "camo5"};
			hiddenSelectionsTextures[] = {"COS_gilet\data\JPC\CRYE_JPC_TAN.co.paa", "cos_gilet\data\poches\POCHE_coy.co.paa", "cos_gilet\data\poches\POCHE2_coy.co.paa", "cos_gilet\data\poches\assets_strap_tan.co.paa", "cos_gilet\data\poches\afam_radio_tan.co.paa"};
			containerClass = "Supply200";
			picture = "COS_gilet\data\icon\ic_vest_fs.ca.paa";
			mass = 50;
			passThrough = "true";
			
			class HitpointsProtectionInfo {
				class Chest {
					HitpointName = "HitChest";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Diaphragm {
					HitpointName = "HitDiaphragm";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 25;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					passThrough = 0.3;
				};
			};
		};
	};
	
	class JPC_4_OD : Vest_NoCamo_Base {
		author = "modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		vehicleClass = "Backpacks";
		_generalMacro = JPC_4_OD;
		displayName = ".JPC 4 OD";
		picture = "COS_gilet\data\icon\ic_vest_fs.ca.paa";
		model = "\COS_gilet\JPC_4";
		hiddenSelections[] = {};
		hiddenSelectionsTextures[] = {};
		hiddenSelectionsMaterials[] = {};
		
		class ItemInfo : VestItem {
			uniformModel = "\COS_gilet\JPC_4";
			hiddenSelections[] = {};
			hiddenSelectionsTextures[] = {};
			containerClass = "Supply200";
			picture = "COS_gilet\data\icon\ic_vest_fs.ca.paa";
			mass = 50;
			passThrough = "true";
			
			class HitpointsProtectionInfo {
				class Chest {
					HitpointName = "HitChest";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Diaphragm {
					HitpointName = "HitDiaphragm";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 25;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					passThrough = 0.3;
				};
			};
		};
	};
	
	class vest_co_pilot_combat : Vest_NoCamo_Base {
		author = "modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		_generalMacro = "vest_co_pilot_combat";
		displayName = ".vest_co_pilot_combat";
		picture = "";
		model = "\COS_gilet\co_pilot";
		hiddenSelections[] = {};
		hiddenSelectionsTextures[] = {};
		hiddenSelectionsMaterials[] = {};
		
		class ItemInfo : VestItem {
			uniformModel = "\COS_gilet\co_pilot";
			hiddenSelections[] = {};
			containerClass = "Supply200";
			mass = 50;
			passThrough = "true";
			
			class HitpointsProtectionInfo {
				class Chest {
					HitpointName = "HitChest";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Diaphragm {
					HitpointName = "HitDiaphragm";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 25;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					passThrough = 0.3;
				};
			};
		};
	};
	
	class vest_pilot_combat : Vest_NoCamo_Base {
		author = "modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		_generalMacro = "vest_pilot_combat";
		displayName = ".vest pilot combat";
		picture = "";
		model = "\COS_gilet\pilot";
		hiddenSelections[] = {};
		hiddenSelectionsTextures[] = {};
		hiddenSelectionsMaterials[] = {};
		
		class ItemInfo : VestItem {
			uniformModel = "\COS_gilet\pilot";
			hiddenSelections[] = {};
			containerClass = "Supply200";
			mass = 50;
			passThrough = "true";
			
			class HitpointsProtectionInfo {
				class Chest {
					HitpointName = "HitChest";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Diaphragm {
					HitpointName = "HitDiaphragm";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 25;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					passThrough = 0.3;
				};
			};
		};
	};
	
	class halo_vest_L : Vest_NoCamo_Base {
		author = "modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		_generalMacro = "halo_vest_L";
		displayName = ".halo vest L ";
		picture = "\COS_equips\data\icon\patch_COS.ca.paa";
		model = "\COS_gilet\halo_vest_L";
		hiddenSelections[] = {};
		hiddenSelectionsTextures[] = {};
		hiddenSelectionsMaterials[] = {};
		
		class ItemInfo : VestItem {
			uniformModel = "\COS_gilet\halo_vest_L";
			hiddenSelections[] = {};
			containerClass = "Supply200";
			mass = 50;
			passThrough = "true";
			vestType = "Rebreather";
			
			class HitpointsProtectionInfo {
				class Chest {
					HitpointName = "HitChest";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Diaphragm {
					HitpointName = "HitDiaphragm";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 25;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					passThrough = 0.3;
				};
			};
		};
	};
	
	class mbss_TL_od : Vest_NoCamo_Base {
		author = "SpecTeR/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		_generalMacro = "mbss_TL_od ";
		displayName = ".MBSS TL Od ";
		allowedSlots[] = {701, 901};
		picture = "\COS_equips\data\icon\mbss_paca_icon.paa";
		model = "\COS_gilet\mbss_TL";
		hiddenSelections[] = {};
		hiddenSelectionsTextures[] = {};
		hiddenSelectionsMaterials[] = {""};
		
		class ItemInfo : VestItem {
			uniformModel = "\COS_gilet\mbss_TL";
			hiddenSelections[] = {};
			containerClass = "Supply200";
			picture = "\COS_equips\data\icon\mbss_paca_icon.paa";
			mass = 50;
			passThrough = "true";
			
			class HitpointsProtectionInfo {
				class Chest {
					HitpointName = "HitChest";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Diaphragm {
					HitpointName = "HitDiaphragm";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 25;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					passThrough = 0.3;
				};
			};
		};
	};
	
	class mbss_TL_coy : Vest_NoCamo_Base {
		author = "SpecTeR/modifiedbySakuraba";
		scope = private;
		scopeCurator = 0;
		scopeArsenal = 0;
		_generalMacro = "mbss_TL_coy ";
		displayName = ".MBSS TL Coy ";
		allowedSlots[] = {901};
		picture = "\COS_equips\data\icon\mbss_paca_icon.paa";
		model = "\COS_gilet\mbss_TL";
		hiddenSelections[] = {"camo", "camo2", "camo3", "camo4"};
		hiddenSelectionsTextures[] = {"COS_gilet\data\mbss_paca\kit_mbss_MC_co.paa", "COS_gilet\data\poches\poche_coy.co.paa", "COS_gilet\data\poches\poche2_coy.co.paa", "COS_gilet\data\poches\GEO_MC.co_2.paa"};
		hiddenSelectionsMaterials[] = {""};
		
		class ItemInfo : VestItem {
			uniformModel = "\COS_gilet\mbss_TL";
			hiddenSelections[] = {"camo", "camo2", "camo3", "camo4"};
			containerClass = "Supply200";
			picture = "\COS_equips\data\icon\mbss_paca_icon.paa";
			mass = 50;
			passThrough = "true";
			
			class HitpointsProtectionInfo {
				class Chest {
					HitpointName = "HitChest";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Diaphragm {
					HitpointName = "HitDiaphragm";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 25;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					passThrough = 0.3;
				};
			};
		};
	};
	
	class mbss_com_od : Vest_NoCamo_Base {
		author = "SpecTeR/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		_generalMacro = "mbss_com_od";
		displayName = ".MBSS Com Od";
		allowedSlots[] = {901};
		picture = "\COS_equips\data\icon\mbss_paca_icon.paa";
		model = "\COS_gilet\mbss_com";
		hiddenSelections[] = {};
		hiddenSelectionsTextures[] = {};
		hiddenSelectionsMaterials[] = {""};
		
		class ItemInfo : VestItem {
			uniformModel = "\COS_gilet\mbss_com";
			hiddenSelections[] = {};
			containerClass = "Supply200";
			picture = "\COS_equips\data\icon\mbss_paca_icon.paa";
			mass = 50;
			passThrough = "true";
			
			class HitpointsProtectionInfo {
				class Chest {
					HitpointName = "HitChest";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Diaphragm {
					HitpointName = "HitDiaphragm";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 25;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					passThrough = 0.3;
				};
			};
		};
	};
	
	class mbss_com_coy : Vest_NoCamo_Base {
		author = "SpecTeR/modifiedbySakuraba";
		scope = private;
		scopeCurator = 0;
		scopeArsenal = 0;
		_generalMacro = "mbss_com_coy";
		displayName = ".MBSS Com Coy";
		allowedSlots[] = {901};
		picture = "\COS_equips\data\icon\mbss_paca_icon.paa";
		model = "\COS_gilet\mbss_com";
		hiddenSelections[] = {"camo", "camo2", "camo3", "camo4"};
		hiddenSelectionsTextures[] = {"COS_gilet\data\mbss_paca\kit_mbss_MC_co.paa", "COS_gilet\data\poches\poche_coy.co.paa", "COS_gilet\data\poches\poche2_coy.co.paa", "COS_gilet\data\poches\GEO_MC.co_2.paa"};
		hiddenSelectionsMaterials[] = {""};
		
		class ItemInfo : VestItem {
			uniformModel = "\COS_gilet\mbss_com";
			hiddenSelections[] = {"camo", "camo2", "camo3", "camo4"};
			containerClass = "Supply200";
			picture = "\COS_equips\data\icon\mbss_paca_icon.paa";
			mass = 50;
			passThrough = "true";
			
			class HitpointsProtectionInfo {
				class Chest {
					HitpointName = "HitChest";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Diaphragm {
					HitpointName = "HitDiaphragm";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 25;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					passThrough = 0.3;
				};
			};
		};
	};
	
	class mbss_SCOUT_od : Vest_NoCamo_Base {
		author = "SpecTeR/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		_generalMacro = "mbss_SCOUT_od";
		displayName = ".MBSS Scout od";
		allowedSlots[] = {901};
		picture = "\COS_equips\data\icon\mbss_paca_icon.paa";
		model = "\COS_gilet\mbss_SCOUT";
		hiddenSelections[] = {};
		hiddenSelectionsTextures[] = {};
		hiddenSelectionsMaterials[] = {""};
		
		class ItemInfo : VestItem {
			uniformModel = "\COS_gilet\mbss_SCOUT";
			hiddenSelections[] = {};
			containerClass = "Supply200";
			picture = "\COS_equips\data\icon\mbss_paca_icon.paa";
			mass = 50;
			passThrough = "true";
			
			class HitpointsProtectionInfo {
				class Chest {
					HitpointName = "HitChest";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Diaphragm {
					HitpointName = "HitDiaphragm";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 25;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					passThrough = 0.3;
				};
			};
		};
	};
	
	class mbss_SCOUT_coy : Vest_NoCamo_Base {
		author = "SpecTeR/modifiedbySakuraba";
		scope = private;
		scopeCurator = 0;
		scopeArsenal = 0;
		_generalMacro = "mbss_SCOUT_coy";
		displayName = ".MBSS Scout coy";
		allowedSlots[] = {901};
		picture = "\COS_equips\data\icon\mbss_paca_icon.paa";
		model = "\COS_gilet\mbss_SCOUT";
		hiddenSelections[] = {"camo", "camo2", "camo3", "camo4"};
		hiddenSelectionsTextures[] = {"COS_gilet\data\mbss_paca\kit_mbss_MC_co.paa", "COS_gilet\data\poches\poche_coy.co.paa", "COS_gilet\data\poches\poche2_coy.co.paa", "COS_gilet\data\poches\GEO_MC.co_2.paa"};
		hiddenSelectionsMaterials[] = {""};
		
		class ItemInfo : VestItem {
			uniformModel = "\COS_gilet\mbss_SCOUT";
			hiddenSelections[] = {"camo", "camo2", "camo3", "camo4"};
			containerClass = "Supply200";
			picture = "\COS_equips\data\icon\mbss_paca_icon.paa";
			mass = 50;
			passThrough = "true";
			
			class HitpointsProtectionInfo {
				class Chest {
					HitpointName = "HitChest";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Diaphragm {
					HitpointName = "HitDiaphragm";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 25;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					passThrough = 0.3;
				};
			};
		};
	};
	
	class mbss_RECON_od : Vest_NoCamo_Base {
		author = "SpecTeR/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		_generalMacro = "mbss_RECON_od";
		displayName = ".MBSS Recon Od";
		allowedSlots[] = {901};
		picture = "\COS_equips\data\icon\mbss_paca_icon.paa";
		model = "\COS_gilet\mbss_RECON";
		hiddenSelections[] = {};
		hiddenSelectionsTextures[] = {};
		hiddenSelectionsMaterials[] = {""};
		
		class ItemInfo : VestItem {
			uniformModel = "\COS_gilet\mbss_RECON";
			hiddenSelections[] = {};
			containerClass = "Supply200";
			picture = "\COS_equips\data\icon\mbss_paca_icon.paa";
			mass = 50;
			passThrough = "true";
			
			class HitpointsProtectionInfo {
				class Chest {
					HitpointName = "HitChest";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Diaphragm {
					HitpointName = "HitDiaphragm";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 25;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					passThrough = 0.3;
				};
			};
		};
	};
	
	class mbss_RECON_BLK : Vest_NoCamo_Base {
		author = "SpecTeR/modifiedbySakuraba";
		scope = private;
		scopeCurator = 0;
		scopeArsenal = 0;
		_generalMacro = "mbss_RECON_BLK";
		displayName = ".MBSS Recon BLK";
		allowedSlots[] = {901};
		picture = "\COS_equips\data\icon\mbss_paca_icon.paa";
		model = "\COS_gilet\mbss_RECON_blk";
		hiddenSelections[] = {};
		hiddenSelectionsTextures[] = {};
		hiddenSelectionsMaterials[] = {""};
		
		class ItemInfo : VestItem {
			uniformModel = "\COS_gilet\mbss_RECON_blk";
			hiddenSelections[] = {};
			containerClass = "Supply200";
			picture = "\COS_equips\data\icon\mbss_paca_icon.paa";
			mass = 50;
			passThrough = "true";
			
			class HitpointsProtectionInfo {
				class Chest {
					HitpointName = "HitChest";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Diaphragm {
					HitpointName = "HitDiaphragm";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 25;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					passThrough = 0.3;
				};
			};
		};
	};
	
	class 6094_com_OD : Vest_NoCamo_Base {
		author = "3D_artist/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		_generalMacro = "6094_com_OD";
		displayName = ".6094 Com OD";
		allowedSlots[] = {701, 901};
		picture = "\COS_equips\data\icon\ic_LBT_OD.ca.paa";
		model = "\COS_gilet\6094_com";
		hiddenSelections[] = {"camo", "camo1", "camo2", "camo3"};
		hiddenSelectionsTextures[] = {"COS_gilet\data\gilet_combat\6094\TMC_od_co.paa", "COS_gilet\data\POCHES\trousse_od_co.paa", "COS_gilet\data\poches\poche_od.co.paa", "COS_gilet\data\poches\poche2_od.co.paa"};
		hiddenSelectionsMaterials[] = {""};
		
		class ItemInfo : VestItem {
			uniformModel = "\COS_gilet\6094_com";
			hiddenSelections[] = {"camo", "camo1", "camo2", "camo3"};
			containerClass = "Supply200";
			picture = "\COS_equips\data\icon\ic_LBT_OD.ca.paa";
			mass = 50;
			passThrough = "true";
			
			class HitpointsProtectionInfo {
				class Chest {
					HitpointName = "HitChest";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Diaphragm {
					HitpointName = "HitDiaphragm";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 25;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					passThrough = 0.3;
				};
			};
		};
	};
	
	class 6094_com_coy : Vest_NoCamo_Base {
		author = "3D_artist/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		_generalMacro = "6094_com_coy";
		displayName = ".6094 Com Coy";
		allowedSlots[] = {901};
		picture = "\COS_equips\data\icon\ic_LBT_OD.ca.paa";
		model = "\COS_gilet\6094_com";
		hiddenSelections[] = {"camo", "camo1", "camo2", "camo3", "camo6", "camo8"};
		hiddenSelectionsTextures[] = {"COS_gilet\data\gilet_combat\6094\TMC_tan_co.paa", "COS_gilet\data\POCHES\trousse_tan_co.paa", "COS_gilet\data\poches\poche_coy.co.paa", "COS_gilet\data\poches\poche2_coy.co.paa", "COS_gilet\data\poches\trousse_tan_co.paa", "COS_gilet\data\poches\AFAM_radio_MC.co.paa"};
		hiddenSelectionsMaterials[] = {""};
		
		class ItemInfo : VestItem {
			uniformModel = "\COS_gilet\6094_com";
			hiddenSelections[] = {"camo", "camo1", "camo2", "camo3", "camo6", "camo8"};
			containerClass = "Supply200";
			picture = "\COS_equips\data\icon\ic_LBT_OD.ca.paa";
			mass = 50;
			passThrough = "true";
			
			class HitpointsProtectionInfo {
				class Chest {
					HitpointName = "HitChest";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Diaphragm {
					HitpointName = "HitDiaphragm";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 25;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					passThrough = 0.3;
				};
			};
		};
	};
	
	class 6094_SCOUT_od : Vest_NoCamo_Base {
		author = "3D_artist/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		_generalMacro = "6094_SCOUT_od";
		displayName = ".6094 Scout Od";
		allowedSlots[] = {901};
		picture = "\COS_equips\data\icon\ic_LBT_OD.ca.paa";
		model = "\COS_gilet\6094_SCOUT";
		hiddenSelections[] = {"camo", "camo2", "camo3"};
		hiddenSelectionsTextures[] = {"COS_gilet\data\gilet_combat\6094\TMC_OD_co.paa", "COS_gilet\data\poches\poche_od.co.paa", "COS_gilet\data\poches\poche2_od.co.paa"};
		hiddenSelectionsMaterials[] = {""};
		
		class ItemInfo : VestItem {
			uniformModel = "\COS_gilet\6094_SCOUT";
			hiddenSelections[] = {"camo", "camo2", "camo3"};
			containerClass = "Supply200";
			picture = "\COS_equips\data\icon\ic_LBT_OD.ca.paa";
			mass = 50;
			passThrough = "true";
			
			class HitpointsProtectionInfo {
				class Chest {
					HitpointName = "HitChest";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Diaphragm {
					HitpointName = "HitDiaphragm";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 25;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					passThrough = 0.3;
				};
			};
		};
	};
	
	class 6094_SCOUT_coy : Vest_NoCamo_Base {
		author = "3D_artist/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		_generalMacro = "6094_SCOUT_coy";
		displayName = ".6094 Scout Coy";
		allowedSlots[] = {901};
		picture = "\COS_equips\data\icon\ic_LBT_OD.ca.paa";
		model = "\COS_gilet\6094_SCOUT";
		hiddenSelections[] = {"camo", "camo2", "camo3"};
		hiddenSelectionsTextures[] = {"COS_gilet\data\gilet_combat\6094\TMC_tan_co.paa", "COS_gilet\data\poches\poche_coy.co.paa", "COS_gilet\data\poches\poche2_coy.co.paa"};
		hiddenSelectionsMaterials[] = {""};
		
		class ItemInfo : VestItem {
			uniformModel = "\COS_gilet\6094_SCOUT";
			hiddenSelections[] = {"camo", "camo2", "camo3"};
			containerClass = "Supply200";
			picture = "\COS_equips\data\icon\ic_LBT_OD.ca.paa";
			mass = 50;
			passThrough = "true";
			
			class HitpointsProtectionInfo {
				class Chest {
					HitpointName = "HitChest";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Diaphragm {
					HitpointName = "HitDiaphragm";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 25;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					passThrough = 0.3;
				};
			};
		};
	};
	
	class 6094_RECON_od : Vest_NoCamo_Base {
		author = "3D_artist/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		_generalMacro = "6094_RECON_od";
		displayName = ".6094 Recon Od";
		allowedSlots[] = {901};
		picture = "\COS_equips\data\icon\ic_LBT_OD.ca.paa";
		model = "\COS_gilet\6094_RECON";
		hiddenSelections[] = {"camo", "camo2", "camo3"};
		hiddenSelectionsTextures[] = {"COS_gilet\data\gilet_combat\6094\TMC_OD_co.paa", "COS_gilet\data\poches\poche_od.co.paa", "COS_gilet\data\poches\poche2_od.co.paa"};
		hiddenSelectionsMaterials[] = {""};
		
		class ItemInfo : VestItem {
			uniformModel = "\COS_gilet\6094_RECON";
			hiddenSelections[] = {"camo", "camo2", "camo3"};
			containerClass = "Supply200";
			picture = "\COS_equips\data\icon\ic_LBT_OD.ca.paa";
			mass = 50;
			passThrough = "true";
			
			class HitpointsProtectionInfo {
				class Chest {
					HitpointName = "HitChest";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Diaphragm {
					HitpointName = "HitDiaphragm";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 25;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					passThrough = 0.3;
				};
			};
		};
	};
	
	class 6094_RECON_coy : Vest_NoCamo_Base {
		author = "3D_artist/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		_generalMacro = "6094_RECON_coy";
		displayName = ".6094 Recon Coy";
		allowedSlots[] = {901};
		picture = "\COS_equips\data\icon\ic_LBT_OD.ca.paa";
		model = "\COS_gilet\6094_RECON";
		hiddenSelections[] = {"camo", "camo2", "camo3", "camo4"};
		hiddenSelectionsTextures[] = {"COS_gilet\data\gilet_combat\6094\TMC_tan_co.paa", "COS_gilet\data\poches\poche_coy.co.paa", "COS_gilet\data\poches\poche2_coy.co.paa", "bfst_gilet\data\belt\holster_tan_co.paa"};
		hiddenSelectionsMaterials[] = {""};
		
		class ItemInfo : VestItem {
			uniformModel = "\COS_gilet\6094_RECON";
			hiddenSelections[] = {"camo", "camo2", "camo3", "camo4"};
			containerClass = "Supply200";
			picture = "\COS_equips\data\icon\ic_LBT_OD.ca.paa";
			mass = 50;
			passThrough = "true";
			
			class HitpointsProtectionInfo {
				class Chest {
					HitpointName = "HitChest";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Diaphragm {
					HitpointName = "HitDiaphragm";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 25;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					passThrough = 0.3;
				};
			};
		};
	};
	
	class 6094_MEDIC_od : Vest_NoCamo_Base {
		author = "3D_artist/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		_generalMacro = "6094_MEDIC_od";
		displayName = ".6094 Medic Od";
		allowedSlots[] = {901};
		picture = "\COS_equips\data\icon\ic_LBT_OD.ca.paa";
		model = "\COS_gilet\6094_MEDIC";
		hiddenSelections[] = {"camo", "camo2", "camo3"};
		hiddenSelectionsTextures[] = {"COS_gilet\data\gilet_combat\6094\TMC_OD_co.paa", "COS_gilet\data\poches\poche_od.co.paa", "COS_gilet\data\poches\poche2_od.co.paa"};
		hiddenSelectionsMaterials[] = {""};
		
		class ItemInfo : VestItem {
			uniformModel = "\COS_gilet\6094_MEDIC";
			hiddenSelections[] = {"camo", "camo2", "camo3"};
			containerClass = "Supply200";
			picture = "\COS_equips\data\icon\ic_LBT_OD.ca.paa";
			mass = 50;
			passThrough = "true";
			
			class HitpointsProtectionInfo {
				class Chest {
					HitpointName = "HitChest";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Diaphragm {
					HitpointName = "HitDiaphragm";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 25;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					passThrough = 0.3;
				};
			};
		};
	};
	
	class 6094_MEDIC_coy : Vest_NoCamo_Base {
		author = "3D_artist/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		_generalMacro = "6094_MEDIC_coy";
		displayName = ".6094 Medic Coy";
		allowedSlots[] = {901};
		picture = "\COS_equips\data\icon\ic_LBT_OD.ca.paa";
		model = "\COS_gilet\6094_MEDIC";
		hiddenSelections[] = {"camo", "camo2", "camo3"};
		hiddenSelectionsTextures[] = {"COS_gilet\data\gilet_combat\6094\TMC_tan_co.paa", "COS_gilet\data\poches\poche_coy.co.paa", "COS_gilet\data\poches\poche2_coy.co.paa"};
		hiddenSelectionsMaterials[] = {""};
		
		class ItemInfo : VestItem {
			uniformModel = "\COS_gilet\6094_MEDIC";
			hiddenSelections[] = {"camo", "camo2", "camo3"};
			containerClass = "Supply200";
			picture = "\COS_equips\data\icon\ic_LBT_OD.ca.paa";
			mass = 50;
			passThrough = "true";
			
			class HitpointsProtectionInfo {
				class Chest {
					HitpointName = "HitChest";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Diaphragm {
					HitpointName = "HitDiaphragm";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 25;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					passThrough = 0.3;
				};
			};
		};
	};
	
	class 6094_HEAVY_od : Vest_NoCamo_Base {
		author = "3D_artist/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		_generalMacro = "6094_HEAVY_od";
		displayName = ".6094 TL Od";
		allowedSlots[] = {901};
		picture = "\COS_equips\data\icon\ic_LBT_OD.ca.paa";
		model = "\COS_gilet\6094_HEAVY";
		hiddenSelections[] = {"camo", "camo2", "camo3", "camo4"};
		hiddenSelectionsTextures[] = {"COS_gilet\data\gilet_combat\6094\TMC_OD_co.paa", "COS_gilet\data\poches\poche_od.co.paa", "COS_gilet\data\poches\poche2_od.co.paa"};
		hiddenSelectionsMaterials[] = {""};
		
		class ItemInfo : VestItem {
			uniformModel = "\COS_gilet\6094_HEAVY";
			hiddenSelections[] = {"camo", "camo2", "camo3", "camo4"};
			containerClass = "Supply200";
			picture = "\COS_equips\data\icon\ic_LBT_OD.ca.paa";
			mass = 50;
			passThrough = "true";
			
			class HitpointsProtectionInfo {
				class Chest {
					HitpointName = "HitChest";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Diaphragm {
					HitpointName = "HitDiaphragm";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 25;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					passThrough = 0.3;
				};
			};
		};
	};
	
	class 6094_HEAVY_coy : Vest_NoCamo_Base {
		author = "3D_artist/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		_generalMacro = "6094_HEAVY_coy";
		displayName = ".6094 TL Coy";
		allowedSlots[] = {901};
		picture = "\COS_equips\data\icon\ic_LBT_OD.ca.paa";
		model = "\COS_gilet\6094_HEAVY";
		hiddenSelections[] = {"camo", "camo2", "camo3", "camo4"};
		hiddenSelectionsTextures[] = {"COS_gilet\data\gilet_combat\6094\TMC_tan_co.paa", "COS_gilet\data\poches\poche_coy.co.paa", "COS_gilet\data\poches\poche2_coy.co.paa"};
		hiddenSelectionsMaterials[] = {""};
		
		class ItemInfo : VestItem {
			uniformModel = "\COS_gilet\6094_HEAVY";
			hiddenSelections[] = {"camo", "camo2", "camo3", "camo4"};
			containerClass = "Supply200";
			picture = "\COS_equips\data\icon\ic_LBT_OD.ca.paa";
			mass = 50;
			passThrough = "true";
			
			class HitpointsProtectionInfo {
				class Chest {
					HitpointName = "HitChest";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Diaphragm {
					HitpointName = "HitDiaphragm";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 25;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					passThrough = 0.3;
				};
			};
		};
	};
	
	class 6094_JTAC : Vest_NoCamo_Base {
		author = "3D_artist/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		_generalMacro = 6094_JTAC;
		displayName = ".6094 Operateur";
		allowedSlots[] = {901};
		picture = "\COS_equips\data\icon\ic_LBT_OD.ca.paa";
		model = "\COS_gilet\6094_HEAVY";
		hiddenSelections[] = {"camo", "camo2", "camo3"};
		hiddenSelectionsTextures[] = {"COS_gilet\data\gilet_combat\6094\TMC_OD_co.paa", "COS_gilet\data\poches\poche_od.co.paa", "COS_gilet\data\poches\poche2_od.co.paa"};
		hiddenSelectionsMaterials[] = {""};
		descriptionUse = "Use: View GPS";
		simulation = "ItemGPS";
		
		class ItemInfo : VestItem {
			uniformModel = "\COS_gilet\6094_JTAC";
			hiddenSelections[] = {"camo", "camo2", "camo3"};
			containerClass = "Supply200";
			picture = "\COS_equips\data\icon\ic_LBT_OD.ca.paa";
			mass = 50;
			passThrough = "true";
			
			class HitpointsProtectionInfo {
				class Chest {
					HitpointName = "HitChest";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Diaphragm {
					HitpointName = "HitDiaphragm";
					armor = 25;
					PassThrough = 0.3;
				};
				
				class Abdomen {
					hitpointName = "HitAbdomen";
					armor = 25;
					passThrough = 0.3;
				};
				
				class Body {
					hitpointName = "HitBody";
					passThrough = 0.3;
				};
			};
		};
	};
};

class cfgMods {
	author = "sakuraba";
	timepacked = 1523079339;
};
