// config.bin - 18:20:19 09/04/19, generated in 0.08 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define private		0
#define protected		1
#define public		2

#define true	1
#define false	0

class DefaultEventhandlers;	// External class reference

class CfgPatches {
	class COS_equips {
		units[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {};
		version = 20-05-2016;
		author = "Sakuraba_and_author_in_credits";
	};
};

class UniformSlotInfo {
	slotType = 0;
	linkProxy = "-";
};

class CfgVehicleClasses {};

class cfgWeapons {
	class H_HelmetB;	// External class reference
	class H_Booniehat_khk_hs;	// External class reference
	class NVGoggles;	// External class reference
	class ItemCore;	// External class reference
	class InventoryItem_Base_F;	// External class reference
	class HeadgearItem;	// External class reference
	class Item_Base_F;	// External class reference
	
	class FILET_DIVER : NVGoggles {
		scope = private;
		author = "bySakuraba";
		displayname = ".FILET_DIVER";
		model = "\COS_equips\FILET_DIVER";
		picture = "\COS_equips\data\icon\FILET_HAT";
		hiddenSelections[] = {};
		hiddenSelectionsTextures[] = {};
		hiddenSelectionsMaterials[] = {};
		identityTypes[] = {};
		modelOptics = "-";
		visionMode[] = {"Normal"};
		
		class ItemInfo {
			type = 616;
			hmdType = 0;
			uniformModel = "\COS_equips\FILET_DIVER";
			modelOff = "\COS_equips\FILET_DIVER";
			hiddenSelections[] = {};
			hiddenSelectionsTextures[] = {};
			hiddenSelectionsMaterials[] = {};
			mass = 2;
		};
	};
	
	class FILET_HAT : NVGoggles {
		scope = private;
		author = "bySakuraba";
		displayname = ".FILET_HAT";
		model = "\COS_equips\FILET_HAT";
		picture = "\COS_equips\data\icon\FILET_HAT";
		hiddenSelections[] = {};
		hiddenSelectionsTextures[] = {};
		identityTypes[] = {};
		modelOptics = "-";
		visionMode[] = {"Normal"};
		ACE_Overlay = "COS_equips\data\glasses\overlays\filet_overlay_ca.paa_ca.paa";
		
		class ItemInfo {
			type = 616;
			hmdType = 0;
			uniformModel = "\COS_equips\FILET_HAT";
			modelOff = "\COS_equips\FILET_HAT";
			hiddenSelections[] = {};
			hiddenSelectionsTextures[] = {};
			mass = 4;
			ACE_Overlay = "COS_equips\data\glasses\overlays\filet_overlay_ca.paa_ca.paa";
		};
	};
	
	class FILET_SNIPER_cam : NVGoggles {
		scope = public;
		author = "bySakuraba";
		displayname = ".Filet_Sniper_Cam";
		model = "\COS_equips\FILET_SNIPER";
		picture = "\COS_equips\data\icon\FILET_SNIPER";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\COS_equips\data\ghillie_bag\FILET_cam_ca.paa"};
		identityTypes[] = {};
		modelOptics = "-";
		visionMode[] = {"Normal"};
		ACE_Overlay = "COS_equips\data\glasses\overlays\filet_overlay_ca.paa_ca.paa";
		
		class ItemInfo {
			type = 616;
			hmdType = 0;
			uniformModel = "\COS_equips\FILET_SNIPER";
			modelOff = "\COS_equips\FILET_SNIPER";
			hiddenSelections[] = {"camo"};
			hiddenSelectionsTextures[] = {"\COS_equips\data\ghillie_bag\FILET_cam_ca.paa"};
			ACE_Overlay = "COS_equips\data\glasses\overlays\filet_overlay_ca.paa_ca.paa";
			mass = 2;
		};
	};
	
	class SNIPER_VOILE_TAN : NVGoggles {
		scope = public;
		author = "bySakuraba";
		displayname = ".SNIPER_VOILE_TAN";
		model = "\COS_equips\FILET_SNIPER";
		picture = "\COS_equips\data\icon\FILET_SNIPER";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\COS_equips\data\ghillie_bag\sniper_veil_TAN.co.paa"};
		identityTypes[] = {};
		modelOptics = "-";
		visionMode[] = {"Normal"};
		ACE_Overlay = "COS_equips\data\glasses\overlays\filet_overlay_ca.paa_ca.paa";
		
		class ItemInfo {
			type = 616;
			hmdType = 0;
			uniformModel = "\COS_equips\FILET_SNIPER";
			modelOff = "\COS_equips\FILET_SNIPER";
			hiddenSelections[] = {"camo"};
			hiddenSelectionsTextures[] = {"\COS_equips\data\ghillie_bag\sniper_veil_TAN.co.paa"};
			ACE_Overlay = "COS_equips\data\glasses\overlays\filet_overlay_ca.paa_ca.paa";
			mass = 2;
		};
	};
	
	class NBC_masque : NVGoggles {
		scope = public;
		ace_color[] = {0, 0, -1};
		ace_tintAmount = 8;
		ace_resistance = 2;
		ace_protection = 1;
		displayname = ".NBC_masque";
		author = "COD_ghost";
		model = "\COS_equips\masque_NBC";
		hiddenSelections[] = {};
		hiddenSelectionsTextures[] = {};
		hiddenSelectionsMaterials[] = {};
		modelOptics = "-";
		visionMode[] = {"Normal"};
		picture = "\COS_equips\data\icon\NBC_set_ca.paa";
		identityTypes[] = {};
		
		class ItemInfo {
			type = 616;
			hmdType = 0;
			uniformModel = "\COS_equips\masque_NBC";
			modelOff = "\COS_equips\masque_NBC";
			hiddenSelections[] = {};
			mass = 3;
			ACE_Overlay = "COS_equips\data\glasses\overlays\GAZ_MASK_overlay_ca.paa";
		};
	};
	
	class BALA_NBC_PELTOR : NVGoggles {
		scope = public;
		ace_color[] = {0, 0, -1};
		ace_tintAmount = 8;
		ace_resistance = 2;
		ace_protection = 1;
		displayname = ".BALA_NBC_PELTOR";
		author = "";
		model = "\COS_equips\BALA_NBC_PELTOR";
		hiddenSelections[] = {};
		hiddenSelectionsTextures[] = {};
		hiddenSelectionsMaterials[] = {};
		modelOptics = "-";
		visionMode[] = {"Normal"};
		picture = "\COS_equips\data\icon\GAZ_mask_ca.paa";
		identityTypes[] = {};
		ACE_Overlay = "COS_equips\data\glasses\overlays\GAZ_MASK_overlay_ca.paa";
		
		class ItemInfo {
			type = 616;
			hmdType = 0;
			uniformModel = "\COS_equips\BALA_NBC_PELTOR";
			modelOff = "\COS_equips\BALA_NBC_PELTOR";
			hiddenSelections[] = {};
			mass = 4;
		};
	};
	
	class tac_glass_1 : NVGoggles {
		scope = public;
		ace_color[] = {0, 0, -1};
		ace_tintAmount = 8;
		ace_resistance = 2;
		ace_protection = 1;
		displayname = ".tac_glass";
		author = "retexbySakuraba";
		model = "\COS_equips\tac_glass_1";
		hiddenSelections[] = {"camo", "camo2"};
		hiddenSelectionsTextures[] = {"cos_equips\data\glasses\ess\tactical_ca.tga", "cos_equips\data\glasses\lense\red_glass_ca.paa"};
		hiddenSelectionsMaterials[] = {"cos_equips\data\glasses\ess\tactical.rvmat", "cos_equips\data\glasses\reflective_glass.rvmat"};
		modelOptics = "-";
		visionMode[] = {"Normal"};
		picture = "\COS_equips\data\icon\ic_tac_gl_yel_ca.paa";
		identityTypes[] = {};
		
		class ItemInfo {
			type = 616;
			hmdType = 0;
			uniformModel = "\COS_equips\tac_glass_1";
			modelOff = "\COS_equips\tac_glass_1";
			hiddenSelections[] = {"camo", "camo2"};
			mass = 2;
		};
	};
	
	class tac_glass_2 : NVGoggles {
		scope = public;
		ace_color[] = {0, 0, -1};
		ace_tintAmount = 8;
		ace_resistance = 2;
		ace_protection = 1;
		displayname = ".tac_glass_yellow";
		author = "retexbySakuraba";
		model = "\COS_equips\tac_glass_1";
		hiddenSelections[] = {"camo", "camo2"};
		hiddenSelectionsTextures[] = {"cos_equips\data\glasses\ess\tactical_ca.tga", "cos_equips\data\glasses\lense\blu_glass_ca.paa"};
		hiddenSelectionsMaterials[] = {"cos_equips\data\glasses\ess\tactical.rvmat", "cos_equips\data\glasses\reflective_glass.rvmat"};
		modelOptics = "-";
		visionMode[] = {"Normal"};
		picture = "\COS_equips\data\icon\ic_tac_gl_yel_ca.paa";
		identityTypes[] = {};
		
		class ItemInfo {
			type = 616;
			hmdType = 0;
			uniformModel = "\COS_equips\tac_glass_1";
			modelOff = "\COS_equips\tac_glass_1";
			hiddenSelections[] = {"camo", "camo2"};
			mass = 2;
		};
	};
	
	class Booniehat_CE_hs : H_Booniehat_khk_hs {
		scope = public;
		author = "retexbySakuraba";
		picture = "\COS_equips\data\icon\brousse_ce_ca.paa";
		displayName = ".BOB_brousse_CE";
		model = "A3\Characters_F_EPB\Common\booniehat_hs.p3d";
		hiddenSelectionsTextures[] = {"\COS_equips\data\Custom_HeadGear\headgear\Chp_brousse_CE.paa"};
		allowedFacewear[] = {"", 5, "G_Aviator", 1, "G_Balaclava_oli", 1, "G_Shades_Black", 1, "G_Shades_Green", 1, "G_Bandanna_vert", 1};
		identityTypes[] = {};
	};
	
	class Booniehat_daguet_hs : H_Booniehat_khk_hs {
		scope = public;
		author = "retexbySakuraba";
		picture = "\COS_equips\data\icon\brousse_daguet_ca.paa";
		displayName = ".BOB_brousse_daguet";
		model = "A3\Characters_F_EPB\Common\booniehat_hs.p3d";
		hiddenSelectionsTextures[] = {"\COS_equips\data\Custom_HeadGear\headgear\Chp_brousse_daguet.paa"};
		allowedFacewear[] = {"", 5, "G_Aviator", 1, "G_Balaclava_oli", 1, "G_Shades_Black", 1, "G_Shades_Green", 1, "G_Bandanna_vert", 1};
		identityTypes[] = {};
	};
	
	class Booniehat : H_Booniehat_khk_hs {
		scope = private;
		author = "retexbySakuraba";
		picture = "\COS_equips\data\icon\brousse_daguet_ca.paa";
		displayName = ".BOB_brousse...";
		model = "COS_equips\chapeau_brousse";
		hiddenSelectionsTextures[] = {};
		identityTypes[] = {};
		
		class ItemInfo : HeadgearItem {
			mass = 3;
			allowedSlots[] = {801, 901, 701, 605};
			uniformModel = "COS_equips\chapeau_brousse";
			armor = "0";
			passThrough = true;
			hiddenSelections[] = {};
			hiddenSelectionsTextures[] = {};
		};
	};
	
	class cap_revers : H_Booniehat_khk_hs {
		scope = private;
		author = "retexbySakuraba";
		weaponPoolAvailable = 1;
		displayName = ".cap_revers";
		picture = "\COS_equips\data\icon\cap_tac_tan_tan_ca.paa";
		model = "\COS_equips\cap_revers";
		hiddenSelections[] = {"camo1", "camo5"};
		hiddenSelectionsTextures[] = {"COS_equips\data\cap_tac\cap_od_co.paa"};
		identityTypes[] = {};
		
		class ItemInfo : HeadgearItem {
			mass = 3;
			allowedSlots[] = {801, 901, 701, 605};
			uniformModel = "\COS_equips\cap_revers";
			armor = "0";
			passThrough = true;
			hiddenSelections[] = {"camo1", "camo5"};
			hiddenSelectionsTextures[] = {"COS_equips\data\cap_tac\cap_od_co.paa"};
		};
	};
	
	class cap_tac_ESS : H_Booniehat_khk_hs {
		scope = public;
		author = "retexbySakuraba";
		weaponPoolAvailable = 1;
		displayName = ".cap_tac_ESS_tan";
		picture = "\COS_equips\data\icon\cap_tac_tan_tan_ca.paa";
		model = "\COS_equips\cap_tac_ESS";
		hiddenSelections[] = {"camo1", "camo5"};
		hiddenSelectionsTextures[] = {"COS_equips\data\cap_tac\cap_od_co.paa"};
		identityTypes[] = {};
		
		class ItemInfo : HeadgearItem {
			mass = 3;
			allowedSlots[] = {801, 901, 701, 605};
			uniformModel = "\COS_equips\cap_tac_ESS";
			armor = "0";
			passThrough = true;
			hiddenSelections[] = {"camo1", "camo5"};
			hiddenSelectionsTextures[] = {"COS_equips\data\cap_tac\cap_od_co.paa"};
		};
	};
	
	class cap_tac_tan : H_Booniehat_khk_hs {
		scope = public;
		author = "retexbySakuraba";
		weaponPoolAvailable = 1;
		displayName = ".cap_tac_tan";
		picture = "\COS_equips\data\icon\cap_tac_tan_tan_ca.paa";
		model = "\COS_equips\cap_tac";
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsTextures[] = {"COS_equips\data\cap_tac\cap_br_co.paa"};
		identityTypes[] = {};
		
		class ItemInfo : HeadgearItem {
			mass = 3;
			allowedSlots[] = {801, 901, 701, 605};
			uniformModel = "\COS_equips\cap_tac";
			armor = "0";
			passThrough = true;
			hiddenSelections[] = {"camo1"};
			hiddenSelectionsTextures[] = {"COS_equips\data\cap_tac\cap_br_co.paa"};
		};
	};
	
	class cap_tac_od : ItemCore {
		scope = public;
		author = "retexbySakuraba";
		weaponPoolAvailable = 1;
		displayName = ".cap_tac_od";
		picture = "\COS_equips\data\icon\cap_tac_od_tan_ca.paa";
		model = "\COS_equips\cap_tac";
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsTextures[] = {"COS_equips\data\cap_tac\cap_od_co.paa"};
		identityTypes[] = {};
		
		class ItemInfo : HeadgearItem {
			mass = 3;
			allowedSlots[] = {801, 901, 701, 605};
			uniformModel = "\COS_equips\cap_tac";
			hiddenSelections[] = {"camo1"};
			hiddenSelectionsTextures[] = {"COS_equips\data\cap_tac\cap_od_co.paa"};
			armor = "0";
			passThrough = true;
		};
	};
	
	class GCP_Face_wear_tan : NVGoggles {
		scope = public;
		author = "retexbySakuraba";
		displayname = ".Face_wear_tan";
		model = "\A3\Characters_F_Bootcamp\Guerrilla\g_bandana_clean.p3d";
		picture = "\COS_equips\data\icon\patch_COS.ca.paa";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\COS_equips\data\Custom_HeadGear\headgear\bandmask_tan_co.paa"};
		identityTypes[] = {};
		
		class ItemInfo {
			type = 616;
			hmdType = 0;
			uniformModel = "\A3\Characters_F_Bootcamp\Guerrilla\g_bandana_clean.p3d";
			modelOff = "\A3\Characters_F_Bootcamp\Guerrilla\g_bandana_clean.p3d";
			hiddenSelections[] = {"camo"};
			hiddenSelectionsTextures[] = {"\COS_equips\data\Custom_HeadGear\headgear\bandmask_tan_co.paa"};
			mass = 3;
		};
	};
	
	class GCP_Face_wear_skull : NVGoggles {
		scope = public;
		author = "retexbySakuraba";
		displayname = ".Face_wear_skull";
		model = "\A3\Characters_F_Bootcamp\Guerrilla\g_bandana_clean.p3d";
		picture = "\COS_equips\data\icon\patch_COS.ca.paa";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\COS_equips\data\Custom_HeadGear\headgear\bandmask_skull_co.paa"};
		identityTypes[] = {};
		visionMode[] = {"Normal"};
		
		class ItemInfo {
			type = 616;
			hmdType = 0;
			uniformModel = "\A3\Characters_F_Bootcamp\Guerrilla\g_bandana_clean.p3d";
			modelOff = "\A3\Characters_F_Bootcamp\Guerrilla\g_bandana_clean.p3d";
			hiddenSelections[] = {"camo"};
			hiddenSelectionsTextures[] = {"\COS_equips\data\Custom_HeadGear\headgear\bandmask_skull_co.paa"};
			mass = 3;
		};
	};
	
	class shemagh_tan : NVGoggles {
		scope = public;
		author = "retexbySakuraba";
		displayname = ".shemagh_tan";
		model = "\COS_equips\shesh";
		picture = "\COS_equips\data\icon\shesh_tan_ca.paa";
		hiddenSelections[] = {"camo5"};
		hiddenSelectionsTextures[] = {"\COS_equips\data\shesh\shemagh_tan_co.paa"};
		identityTypes[] = {};
		visionMode[] = {"Normal"};
		
		class ItemInfo {
			type = 616;
			hmdType = 0;
			uniformModel = "\COS_equips\shesh";
			modelOff = "\COS_equips\shesh";
			hiddenSelections[] = {"camo5"};
			hiddenSelectionsTextures[] = {"\COS_equips\data\shesh\shemagh_tan_co.paa"};
			mass = 3;
		};
	};
	
	class OAKLEY : NVGoggles {
		ace_color[] = {0, 0, -1};
		ace_tintAmount = 8;
		ace_resistance = 2;
		ace_protection = 1;
		scope = public;
		displayname = ".Goggle";
		author = "retexbySakuraba";
		model = "\COS_equips\OAKLEY";
		hiddenSelections[] = {};
		hiddenSelectionsTextures[] = {};
		hiddenSelectionsMaterials[] = {};
		modelOptics = "-";
		visionMode[] = {"Normal"};
		picture = "\COS_equips\data\icon\ess_blk_ca.paa";
		identityTypes[] = {};
		
		class ItemInfo {
			type = 616;
			hmdType = 0;
			uniformModel = "\COS_equips\OAKLEY";
			modelOff = "\COS_equips\OAKLEY";
			hiddenSelections[] = {};
			mass = 2;
		};
	};
	
	class OAKLEY_UP : NVGoggles {
		scope = public;
		displayname = ".Goggle_UP";
		author = "retexbySakuraba";
		model = "\COS_equips\OAKLEY_UP";
		hiddenSelections[] = {};
		hiddenSelectionsTextures[] = {};
		hiddenSelectionsMaterials[] = {};
		modelOptics = "-";
		picture = "\COS_equips\data\icon\ess_blk_ca.paa";
		identityTypes[] = {};
		visionMode[] = {"Normal"};
		
		class ItemInfo {
			type = 616;
			hmdType = 0;
			uniformModel = "\COS_equips\OAKLEY_UP";
			modelOff = "\COS_equips\OAKLEY_UP";
			hiddenSelections[] = {};
			mass = 2;
		};
	};
	
	class halo_mask : NVGoggles {
		scope = public;
		ace_color[] = {0, 0, -1};
		ace_tintAmount = 8;
		ace_resistance = 2;
		ace_protection = 1;
		displayname = ".HALO_mask";
		author = "retexbySakuraba";
		model = "\COS_equips\HALO_mask";
		hiddenSelections[] = {"camo", "camo1"};
		hiddenSelectionsTextures[] = {"COS_equips\data\gaz_mask\gaz_mask.co.paa", "COS_equips\data\halo\halomask.co.paa"};
		hiddenSelectionsMaterials[] = {};
		modelOptics = "-";
		visionMode[] = {"Normal"};
		picture = "\COS_equips\data\icon\HALO_mask_ca.paa";
		identityTypes[] = {};
		ACE_Overlay = "COS_equips\data\glasses\overlays\m04_overlay_ca.paa";
		
		class ItemInfo {
			type = 616;
			hmdType = 0;
			uniformModel = "\COS_equips\HALO_mask";
			modelOff = "\COS_equips\HALO_mask";
			hiddenSelections[] = {"camo", "camo1"};
			mass = 9;
		};
	};
};

class cfgGlasses {
	class None;	// External class reference
	class G_Bandanna_shades;	// External class reference
	class G_Balaclava_blk;	// External class reference
	class G_Combat;	// External class reference
	class G_B_Diving;	// External class reference
	
	class tac_glass_red : None {
		ace_color[] = {0, 0, -1};
		ace_tintAmount = 8;
		ace_resistance = 2;
		ace_protection = 1;
		scope = public;
		displayname = ".tac_glass_red";
		author = "retexbySakuraba";
		model = "\COS_equips\tac_glass_1";
		picture = "\COS_equips\data\icon\ic_tac_gl_yel_ca.paa";
		hiddenSelections[] = {};
		hiddenSelectionsTextures[] = {};
		identityTypes[] = {"NoGlasses", 1000};
		modelOptics = "-";
		mass = 2;
	};
	
	class tac_glass_yel : None {
		ace_color[] = {0, 0, -1};
		ace_tintAmount = 8;
		ace_resistance = 2;
		ace_protection = 1;
		scope = public;
		displayname = ".tac_glass_yel";
		author = "retexbySakuraba";
		model = "\COS_equips\tac_glass_1";
		picture = "\COS_equips\data\icon\ic_tac_gl_yel_ca.paa";
		hiddenSelections[] = {"camo", "camo2"};
		hiddenSelectionsTextures[] = {"cos_equips\data\glasses\ess\tactical_ca.tga", "cos_equips\data\glasses\lense\blu_glass_ca.paa"};
		hiddenSelectionsMaterials[] = {"cos_equips\data\glasses\ess\tactical.rvmat", "cos_equips\data\glasses\reflective_glass.rvmat"};
		identityTypes[] = {"NoGlasses", 1000};
		modelOptics = "-";
		mass = 2;
	};
	
	class ess_mask_blk : None {
		ace_color[] = {0, 0, -1};
		ace_tintAmount = 8;
		ace_resistance = 2;
		ace_protection = 1;
		scope = public;
		displayname = ".Goggle_blk";
		author = "retexbySakuraba";
		model = "\COS_equips\OAKLEY";
		picture = "\COS_equips\data\icon\ess_blk_ca.paa";
		hiddenSelections[] = {};
		hiddenSelectionsTextures[] = {};
		identityTypes[] = {"NoGlasses", 1000};
		modelOptics = "-";
		mass = 3;
	};
	
	class FILET_HAT : None {
		scope = public;
		displayname = ".FILET_HAT";
		author = "Sakuraba";
		model = "\COS_equips\FILET_HAT";
		picture = "\COS_equips\data\icon\shesh_tan_ca.paa";
		hiddenSelections[] = {};
		hiddenSelectionsTextures[] = {};
		identityTypes[] = {"NoGlasses", 1000};
		
		class ItemInfo {
			type = 616;
			hmdType = 0;
			uniformModel = "\COS_equips\shesh";
			mass = 3;
			hiddenSelections[] = {"camo5"};
		};
	};
	
	class shesh_tan : None {
		scope = public;
		displayname = ".shesh_tan";
		author = "retexbySakuraba";
		model = "\COS_equips\shesh";
		picture = "\COS_equips\data\icon\shesh_tan_ca.paa";
		hiddenSelections[] = {"camo5"};
		hiddenSelectionsTextures[] = {"cos_equips\data\shesh\jhon\j_shesh_tan.co.paa"};
		identityTypes[] = {"NoGlasses", 1000};
		
		class ItemInfo {
			type = 616;
			hmdType = 0;
			uniformModel = "\COS_equips\shesh";
			mass = 3;
			hiddenSelections[] = {"camo5"};
		};
	};
	
	class shesh_cover_tan : None {
		displayName = ".shesh_cover_tan";
		author = "retexbySakuraba";
		model = "\COS_equips\shesh_cover";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\COS_equips\data\SHESH\head-wear_tan_co.paa"};
		hiddenSelectionsMaterials[] = {};
		picture = "\COS_equips\data\icon\shesh_tan_ca.paa";
		mass = 3;
		modelOptics = "-";
	};
	
	class shesh_neck_od : None {
		displayName = ".shesh_neck_od";
		author = "retexbySakuraba";
		model = "\COS_equips\shesh_face_2";
		hiddenSelections[] = {"camo", "camo1"};
		hiddenSelectionsTextures[] = {"\COS_equips\data\SHESH\SHESH_net_gr_co.paa", "COS_equips\data\SHESH\shesh_neck_od.co.paa"};
		hiddenSelectionsMaterials[] = {"COS_equips\data\SHESH\shesh_net.rvmat", "COS_equips\data\SHESH\shesh_neck.rvmat"};
		picture = "\COS_equips\data\icon\shesh_tan_ca.paa";
		identityTypes[] = {"NoGlasses", 1000};
		mass = 3;
	};
	
	class shesh_neck_tan : None {
		displayName = ".shesh_neck_tan ";
		author = "retexbySakuraba";
		model = "\COS_equips\shesh_face_2";
		hiddenSelections[] = {"camo", "camo1"};
		hiddenSelectionsTextures[] = {"\COS_equips\data\SHESH\SHESH_net_tan_co.paa", "COS_equips\data\SHESH\shesh_neck_tan.co.paa"};
		hiddenSelectionsMaterials[] = {"COS_equips\data\SHESH\shesh_net.rvmat", "COS_equips\data\SHESH\shesh_neck.rvmat"};
		picture = "\COS_equips\data\icon\shesh_tan_ca.paa";
		identityTypes[] = {"NoGlasses", 1000};
		mass = 3;
	};
	
	class shesh_face_tan : None {
		displayName = ".scarf_tan";
		author = "retexbySakuraba";
		model = "\COS_equips\shesh_face";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\COS_equips\data\shesh\shemagh_tan_co.paa"};
		hiddenSelectionsMaterials[] = {};
		picture = "\COS_equips\data\icon\shesh_tan_ca.paa";
		identityTypes[] = {"NoGlasses", 1000};
		mass = 3;
		modelOptics = "-";
	};
	
	class shesh_face_od : None {
		displayName = ".scarf_od";
		author = "retexbySakuraba";
		model = "\COS_equips\shesh_face";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\COS_equips\data\shesh\shemagh_od_co.paa"};
		hiddenSelectionsMaterials[] = {};
		picture = "\COS_equips\data\icon\shesh_tan_ca.paa";
		identityTypes[] = {"NoGlasses", 1000};
		mass = 3;
	};
	
	class BALA_PELTOR_GAZ : None {
		scope = public;
		author = "retexbySakuraba";
		displayName = ".Bala_Gaz_Peltor";
		model = "\COS_equips\BALA_PELTOR_GAZ";
		picture = "\COS_equips\data\icon\bala_s_od_ca.paa";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"COS_equips\data\BALA_SWAT\balaclava_od_co.paa"};
		identityTypes[] = {"NoGlasses", 1000};
		mass = 7;
	};
	
	class BALA_PELTOR_OD : None {
		scope = public;
		author = "retexbySakuraba";
		displayName = ".BALA_PELTOR_OD";
		model = "\COS_equips\BALA_PELTOR";
		picture = "\COS_equips\data\icon\bala_s_od_ca.paa";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"COS_equips\data\BALA_SWAT\balaclava_od_co.paa"};
		identityTypes[] = {"NoGlasses", 1000};
		mass = 6;
	};
	
	class BALA_PELTOR_TAN : None {
		scope = public;
		author = "retexbySakuraba";
		displayName = ".BALA_PELTOR_TAN";
		model = "\COS_equips\BALA_PELTOR";
		picture = "\COS_equips\data\icon\bala_s_tan_ca.paa";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"COS_equips\data\BALA_SWAT\balaclava_TAN_co.paa"};
		identityTypes[] = {"NoGlasses", 1000};
		mass = 6;
	};
	
	class BALA_SWAT_ESS_BLK : None {
		author = "retexbySakuraba";
		ace_color[] = {0, 0, -1};
		ace_tintAmount = 8;
		ace_resistance = 2;
		ace_protection = 1;
		displayName = ".BALA_ESS_BLK";
		model = "\COS_equips\BALA_ESS";
		picture = "\COS_equips\data\icon\bala_s_blk_ca.paa";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"COS_equips\data\BALA_SWAT\balaclava_BLK_co.paa"};
		identityTypes[] = {"NoGlasses", 1000};
		mass = 6;
	};
	
	class BALA_SWAT_ESS_od : None {
		author = "retexbySakuraba";
		ace_color[] = {0, 0, -1};
		ace_tintAmount = 8;
		ace_resistance = 2;
		ace_protection = 1;
		displayName = ".BALA_ESS_od";
		model = "\COS_equips\BALA_ESS";
		picture = "\COS_equips\data\icon\bala_s_blk_ca.paa";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"COS_equips\data\BALA_SWAT\balaclava_od_co.paa"};
		identityTypes[] = {"NoGlasses", 1000};
		mass = 6;
	};
	
	class BALA_SWAT_ESS_TAN : None {
		author = "retexbySakuraba";
		ace_color[] = {0, 0, -1};
		ace_tintAmount = 8;
		ace_resistance = 2;
		ace_protection = 1;
		displayName = ".BALA_ESS_TAN";
		model = "\COS_equips\BALA_ESS";
		picture = "\COS_equips\data\icon\bala_s_blk_ca.paa";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"COS_equips\data\BALA_SWAT\balaclava_TAN_co.paa"};
		identityTypes[] = {"NoGlasses", 1000};
		mass = 6;
	};
	
	class BALA_SWAT_BW_BLK : None {
		author = "retexbySakuraba";
		displayName = ".BALA_S_BW_BLK";
		model = "\COS_equips\BALA_BW";
		picture = "\COS_equips\data\icon\bala_s_blk_ca.paa";
		hiddenSelections[] = {"camo", "camo2"};
		hiddenSelectionsTextures[] = {"COS_equips\data\BALA_SWAT\balaclava_BLK_co.paa", "\COS_equips\data\BW\bowman_base_co.paa"};
		identityTypes[] = {"NoGlasses", 1000};
		mass = 6;
	};
	
	class BALA_SWAT_BW_OD : None {
		author = "retexbySakuraba";
		displayName = ".BALA_S_BW_OD";
		model = "\COS_equips\BALA_BW";
		picture = "\COS_equips\data\icon\bala_s_od_ca.paa";
		hiddenSelections[] = {"camo", "camo2"};
		hiddenSelectionsTextures[] = {"COS_equips\data\BALA_SWAT\balaclava_od_co.paa", "\COS_equips\data\BW\bowman_base_co.paa"};
		identityTypes[] = {"NoGlasses", 1000};
		mass = 6;
	};
	
	class BALA_SWAT_BW_TAN : None {
		author = "retexbySakuraba";
		displayName = ".BALA_S_BW_TAN";
		model = "\COS_equips\BALA_BW";
		picture = "\COS_equips\data\icon\bala_s_tan_ca.paa";
		hiddenSelections[] = {"camo", "camo2"};
		hiddenSelectionsTextures[] = {"COS_equips\data\BALA_SWAT\balaclava_TAN_co.paa", "\COS_equips\data\BW\bowman_base_co.paa"};
		identityTypes[] = {"NoGlasses", 1000};
		mass = 6;
	};
	
	class BALA_SWAT_BLK : None {
		author = "retexbySakuraba";
		displayName = ".BALA_SWAT_BLK";
		model = "\COS_equips\BALA_SWAT";
		picture = "\COS_equips\data\icon\bala_s_blk_ca.paa";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\COS_equips\data\BALA_SWAT\balaclava_Blk_co.paa"};
		identityTypes[] = {"NoGlasses", 1000};
		mass = 3;
	};
	
	class BALA_SWAT_TAN : None {
		author = "retexbySakuraba";
		displayName = ".BALA_SWAT_TAN";
		model = "\COS_equips\BALA_SWAT";
		picture = "\COS_equips\data\icon\bala_s_tan_ca.paa";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\COS_equips\data\BALA_SWAT\balaclava_TAN_co.paa"};
		identityTypes[] = {"NoGlasses", 1000};
		mass = 3;
	};
	
	class BALA_SWAT_od : None {
		author = "retexbySakuraba";
		displayName = ".BALA_SWAT_od";
		model = "\COS_equips\BALA_SWAT";
		picture = "\COS_equips\data\icon\bala_s_od_ca.paa";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\COS_equips\data\BALA_SWAT\balaclava_OD_co.paa"};
		identityTypes[] = {"NoGlasses", 1000};
		mass = 3;
	};
	
	class BALA_SWAT_CE : None {
		author = "retexbySakuraba";
		displayName = ".BALA_SWAT_CE";
		model = "\COS_equips\BALA_SWAT";
		picture = "\COS_equips\data\icon\bala_s_od_ca.paa";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\COS_equips\data\BALA_SWAT\balaclava_CE_co.paa"};
		identityTypes[] = {"NoGlasses", 1000};
		mass = 3;
	};
	
	class GCP_Balaclava_Ghost : None {
		author = "retexbySakuraba";
		displayName = ".Balaclava_Ghost";
		model = "\A3\Characters_F_Bootcamp\Guerrilla\g_balaclava_clean.p3d";
		picture = "\COS_equips\data\icon\patch_COS.ca.paa";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\COS_equips\data\Custom_HeadGear\headgear\headgear_balaclava_Ghost_co.paa"};
		identityTypes[] = {"NoGlasses", 1000};
		mass = 3;
	};
	
	class A3_Balaclava_od : None {
		author = "retexbySakuraba";
		_generalMacro = "NEW_Balaclava_od";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		displayName = ".A3_Balaclava_A3_od";
		model = "\A3\Characters_F_Exp\BLUFOR\G_Balaclava_TI_F.p3d";
		picture = "\COS_equips\data\icon\patch_COS.ca.paa";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\COS_equips\data\BALA_SWAT\bala3\NEW_Balaclava_od_co.paa"};
		hiddenSelectionsMaterials[] = {"COS_equips\data\BALA_SWAT\bala3\NEW_Balaclava.rvmat"};
		identityTypes[] = {"NoGlasses", 1000};
		mass = 3;
		DLC = "Expansion";
	};
	
	class A3_Balaclava_tan : None {
		author = "retexbySakuraba";
		_generalMacro = "NEW_Balaclava_tan";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		displayName = ".A3_Balaclava_A3_tan";
		model = "\A3\Characters_F_Exp\BLUFOR\G_Balaclava_TI_F.p3d";
		picture = "\COS_equips\data\icon\patch_COS.ca.paa";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\COS_equips\data\BALA_SWAT\bala3\NEW_Balaclava_tan_co.paa"};
		hiddenSelectionsMaterials[] = {"COS_equips\data\BALA_SWAT\bala3\NEW_Balaclava.rvmat"};
		identityTypes[] = {"NoGlasses", 1000};
		mass = 3;
		DLC = "Expansion";
	};
	
	class masque_NBC : G_Combat {
		ace_color[] = {0, 0, -1};
		ace_tintAmount = 8;
		ace_resistance = 2;
		ace_protection = 1;
		scope = public;
		displayname = ".masque_NBC";
		Author = "";
		model = "\COS_equips\masque_NBC.p3d";
		identityTypes[] = {};
		picture = "\COS_equips\data\icon\NBC_set_ca.paa";
		hiddenSelections[] = {};
		hiddenSelectionsTextures[] = {};
		ACE_Overlay = "COS_equips\data\glasses\overlays\GAZ_MASK_overlay_ca.paa";
		mass = 5;
	};
	
	class mask_HALO : None {
		scope = public;
		ace_color[] = {0, 0, -1};
		ace_tintAmount = 8;
		ace_resistance = 2;
		ace_protection = 1;
		displayname = ".mask_HALO";
		author = "retexbySakuraba";
		model = "\COS_equips\HALO_mask";
		hiddenSelections[] = {};
		hiddenSelectionsTextures[] = {};
		ACE_Overlay = "COS_equips\data\glasses\overlays\frozen_overlay_ca.paa";
		identityTypes[] = {"NoGlasses", 1000};
		modelOptics = "-";
		picture = "\COS_equips\data\icon\HALO_set_ca.paa";
		mass = 9;
	};
	
	class DIVER_MASK : G_B_Diving {
		scope = public;
		ace_color[] = {0, 0, -1};
		ace_tintAmount = 8;
		ace_resistance = 2;
		ace_protection = 1;
		author = "retexbySakuraba";
		_generalMacro = DIVER_MASK;
		displayname = ".DIVER_MASK";
		model = "\COS_equips\DIVER_MASK";
		hiddenSelections[] = {"camo", "camo2"};
		hiddenSelectionsTextures[] = {"\cos_equips\data\halo\BEUCHAT_MASK_co.paa"};
		hiddenSelectionsMaterials[] = {};
		hiddenUnderwaterSelections[] = {"hide"};
		shownUnderwaterSelections[] = {"unhide", "unhide2"};
		hiddenUnderwaterSelectionsTextures[] = {"\cos_equips\data\halo\BEUCHAT_MASK_co.paa", "\cos_equips\data\halo\BEUCHAT_MASK_co.paa", "\A3\characters_f\data\visors_ca.paa"};
		ACE_Overlay = "COS_equips\data\glasses\overlays\DIVER_MASK_overlay_ca.paa";
		identityTypes[] = {"NoGlasses", 1000};
		modelOptics = "-";
		mass = 4;
		picture = "\COS_equips\data\icon\ic_DIVER_MASK_ca.paa";
	};
};

class cfgMods {
	author = "sakuraba";
	timepacked = 1501976299;
};
