class DefaultEventhandlers;
class CfgPatches
{
	class COS_casques
	{
		units[]={};
		requiredVersion=0.1;
		requiredAddons[]={};
		version="07-052-2018";
		author="Sakuraba_and_author_in_credits";
	};
	class CJTF_IRstrobeA3
	{
		units[]={};
		weapons[]={};
		requiredVersion=1;
		requiredAddons[]={};
	};
};
class UniformSlotInfo
{
	slotType=0;
	linkProxy="-";
};
class cfgWeapons
{
	class H_CrewHelmetHeli_I;
	class H_PilotHelmetHeli_I;
	class H_HelmetB;
	class ItemCore;
	class InventoryItem_Base_F;
	class HeadgearItem;
	class Item_Base_F;
	class Reflectors;
	class EventHandlers;
	class Casque_Pilote_RHFS: H_PilotHelmetHeli_I
	{
		author="Sakuraba";
		displayName=".Casque Pilote RHFS";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		picture="\COS_casques\data\icon\OPS_CORE_ca.paa"; //REPLACED broken file path by Corey
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\COS_casques\data\caqsue\casque_RHFS.paa"
		};
	};
	class Casque_Crew_RHFS: H_CrewHelmetHeli_I
	{
		author="Sakuraba";
		displayName=".Casque Crew RHFS";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		picture="\COS_tenues\data\PATCH\MEOS.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\COS_casques\data\caqsue\casque_RHFS.paa"
		};
	};
	class HALO_MOWHAK: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		displayName=".HALO_MOWHAK";
		_generalMacro="HALO_MOWHAK";
		author="3d_artist/modifiedbySakuraba";
		model="\COS_casques\HALO_MOWHAK";
		hiddenSelections[]={};
		hiddenSelectionsTextures[]={};
		hiddenSelectionsMaterials[]={};
		picture="COS_casques\data\icon\HALO_set_ca.paa";
		class ItemInfo: HeadgearItem
		{
			mass=25;
			uniformModel="\COS_casques\HALO_MOWHAK";
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]={};
			hiddenSelectionsTextures[]={};
			picture="COS_casques\data\icon\HALO_set_ca.paa";
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					Armor=8;
					passThrough=0.5;
				};
			};
		};
	};
	class HALO_MOWHAK_2: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		displayName=".HALO_MOWHAK_2";
		_generalMacro="HALO_MOWHAK_2";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\HALO_set_ca.paa";
		model="\COS_casques\HALO_MOWHAK_2";
		hiddenSelections[]={};
		hiddenSelectionsTextures[]={};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=25;
			uniformModel="\COS_casques\HALO_MOWHAK_2";
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]={};
			hiddenSelectionsTextures[]={};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					Armor=8;
					passThrough=0.5;
				};
			};
		};
	};
	class HALO_MARITIME_GREY: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		displayName=".HALO_MARITIME_GREY";
		_generalMacro="HALO_MARITIME_GREY";
		author="ORC/modifiedbySakuraba";
		picture="COS_casques\data\icon\HALO_set_ca.paa";
		model="\COS_casques\HALO_MARITIME";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"COS_casques\data\MARITIME\Maritime_GREY_co.paa"
		};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=25;
			uniformModel="\COS_casques\HALO_MARITIME";
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"COS_casques\data\MARITIME\Maritime_GREY_co.paa"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					Armor=8;
					passThrough=0.5;
				};
			};
		};
	};
	class HALO_MARITIME_tan: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		displayName=".HALO MARITIME tan";
		_generalMacro="HALO_MARITIME_tan";
		author="ORC/modifiedbySakuraba";
		picture="COS_casques\data\icon\HALO_set_ca.paa";
		model="\COS_casques\HALO_MARITIME";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"COS_casques\data\MARITIME\Maritime_tan_co.paa"
		};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=25;
			uniformModel="\COS_casques\HALO_MARITIME";
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"COS_casques\data\MARITIME\Maritime_tan_co.paa"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					Armor=8;
					passThrough=0.5;
				};
			};
		};
	};
	class ABS_Base_Jump_grey: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		displayName=".ABS Base Jump grey";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\HALO_set_ca.paa";
		model="\COS_casques\ABS_Base_Jump";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]={};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=25;
			uniformModel="\COS_casques\ABS_Base_Jump";
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelectionsTextures[]={};
			hiddenSelectionsMaterials[]={};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					Armor=8;
					passThrough=0.5;
				};
			};
		};
	};
	class ABS_Base_Jump_tan: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		displayName=".ABS Base Jump tan";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\HALO_set_ca.paa";
		model="\COS_casques\ABS_Base_Jump";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"cos_casques\data\maritime\maritime_tan_co.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"cos_casques\data\maritime\maritime.rvmat"
		};
		class ItemInfo: HeadgearItem
		{
			mass=25;
			uniformModel="\COS_casques\ABS_Base_Jump";
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"cos_casques\data\maritime\maritime_tan_co.paa"
			};
			hiddenSelectionsMaterials[]=
			{
				"cos_casques\data\maritime\maritime.rvmat"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					Armor=8;
					passThrough=0.5;
				};
			};
		};
	};
	class ABS_Base_Jump_IR_grey: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		displayName=".ABS Base Jump IR grey";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\HALO_set_ca.paa";
		model="\COS_casques\ABS_Base_Jump_IR";
		hiddenSelections[]={};
		hiddenSelectionsTextures[]={};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=25;
			uniformModel="\COS_casques\ABS_Base_Jump_IR";
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]={};
			hiddenSelectionsTextures[]={};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					Armor=8;
					passThrough=0.5;
				};
			};
		};
	};
	class ABS_Base_Jump_IR_tan: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		displayName=".ABS Base Jump IR tan";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\HALO_set_ca.paa";
		model="\COS_casques\ABS_Base_Jump_IR";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"COS_casques\data\MARITIME\maritime_tan_co.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"COS_casques\data\MARITIME\maritime.rvmat"
		};
		class ItemInfo: HeadgearItem
		{
			mass=25;
			uniformModel="\COS_casques\ABS_Base_Jump_IR";
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"COS_casques\data\MARITIME\maritime_tan_co.paa"
			};
			hiddenSelectionsMaterials[]=
			{
				"COS_casques\data\MARITIME\maritime.rvmat"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					Armor=8;
					passThrough=0.5;
				};
			};
		};
	};
	class ABS_Base_Jump_peltor_grey: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		displayName=".ABS Base Jump peltor grey";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\HALO_set_ca.paa";
		model="\COS_casques\ABS_Base_Jump_peltor";
		hiddenSelections[]={};
		hiddenSelectionsTextures[]={};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=25;
			uniformModel="\COS_casques\ABS_Base_Jump_peltor";
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]={};
			hiddenSelectionsTextures[]={};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					Armor=8;
					passThrough=0.5;
				};
			};
		};
	};
	class ABS_Base_Jump_peltor_tan: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		displayName=".ABS Base Jump peltor tan";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\HALO_set_ca.paa";
		model="\COS_casques\ABS_Base_Jump_peltor";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"cos_casques\data\maritime\maritime_tan_co.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"cos_casques\data\maritime\maritime.rvmat"
		};
		class ItemInfo: HeadgearItem
		{
			mass=25;
			uniformModel="\COS_casques\ABS_Base_Jump_peltor";
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelectionsTextures[]=
			{
				"cos_casques\data\maritime\maritime_tan_co.paa"
			};
			hiddenSelectionsMaterials[]=
			{
				"cos_casques\data\maritime\maritime.rvmat"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					Armor=8;
					passThrough=0.5;
				};
			};
		};
	};
	class Maritime_ESS_GREY: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		displayName=".Maritime_ESS_MM";
		_generalMacro="Maritime_ESS_MM";
		author="ORC/modifiedbySakuraba";
		picture="COS_casques\data\icon\ic_MARITIME_F_ca.paa";
		model="\COS_casques\Maritime_ESS";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"COS_casques\data\MARITIME\Maritime_MM_co.paa"
		};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=25;
			uniformModel="\COS_casques\Maritime_ESS";
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"COS_casques\data\MARITIME\Maritime_MM_co.paa"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					Armor=8;
					passThrough=0.5;
				};
			};
		};
	};
	class Maritime_L_BLK: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		displayName=".Maritime_L_BLK";
		author="ORC/modifiedbySakuraba";
		_generalMacro="Maritime_L_BLK";
		picture="COS_casques\data\icon\ic_MARITIME_ca.paa";
		model="\COS_casques\Maritime_L";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"COS_casques\data\MARITIME\Maritime_BLK_co.paa"
		};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=25;
			uniformModel="\COS_casques\Maritime_L";
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"COS_casques\data\Maritime_BLK_co.paa"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					Armor=8;
					passThrough=0.5;
				};
			};
		};
	};
	class Maritime_M_GREY: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		displayName=".Maritime_M_Grey";
		_generalMacro="Maritime_M_GREY";
		author="ORC/modifiedbySakuraba";
		picture="COS_casques\data\icon\ic_MARITIME_F_ca.paa";
		model="\COS_casques\Maritime_M";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"COS_casques\data\MARITIME\Maritime_GREY_co.paa"
		};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=25;
			uniformModel="\COS_casques\Maritime_M";
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"COS_casques\data\MARITIME\Maritime_GREY_co.paa"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					Armor=8;
					passThrough=0.5;
				};
			};
		};
	};
	class Maritime_F_GREY: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		displayName=".Maritime_F_Grey";
		_generalMacro="Maritime_F_GREY";
		author="ORC/modifiedbySakuraba";
		picture="COS_casques\data\icon\ic_MARITIME_F_ca.paa";
		model="\COS_casques\Maritime_F";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"COS_casques\data\MARITIME\Maritime_GREY_co.paa"
		};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=25;
			uniformModel="\COS_casques\Maritime_F";
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"COS_casques\data\MARITIME\Maritime_GREY_co.paa"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					Armor=8;
					passThrough=0.5;
				};
			};
		};
	};
	class Maritime_L_GREY: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		displayName=".Maritime_L_Grey";
		_generalMacro="Maritime_L_GREY";
		author="ORC/modifiedbySakuraba";
		picture="COS_casques\data\icon\ic_MARITIME_ca.paa";
		model="\COS_casques\Maritime_L";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"COS_casques\data\MARITIME\Maritime_GREY_co.paa"
		};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=25;
			uniformModel="\COS_casques\Maritime_L";
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"COS_casques\data\Maritime_GREY_co.paa"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					Armor=8;
					passThrough=0.5;
				};
			};
		};
	};
	class Maritime_ESS_TAN: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		displayName=".Maritime_ESS_Tan";
		_generalMacro="Maritime_ESS_TAN";
		author="ORC/modifiedbySakuraba";
		picture="COS_casques\data\icon\ic_MARITIME_F_ca.paa";
		model="\COS_casques\Maritime_ESS";
		hiddenSelections[]={};
		hiddenSelectionsTextures[]={};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=25;
			uniformModel="\COS_casques\Maritime_ESS";
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]={};
			hiddenSelectionsTextures[]={};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					Armor=8;
					passThrough=0.5;
				};
			};
		};
	};
	class Maritime_M_TAN: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		displayName=".Maritime_M_Tan";
		_generalMacro="Maritime_M_TAN";
		author="ORC/modifiedbySakuraba";
		picture="COS_casques\data\icon\ic_MARITIME_F_ca.paa";
		model="\COS_casques\Maritime_M";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"COS_casques\data\MARITIME\Maritime_TAN_co.paa"
		};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=25;
			uniformModel="\COS_casques\Maritime_M";
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"COS_casques\data\MARITIME\Maritime_TAN_co.paa"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					Armor=8;
					passThrough=0.5;
				};
			};
		};
	};
	class Maritime_F_TAN: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		displayName=".Maritime_F_Tan";
		_generalMacro="Maritime_F_TAN";
		author="ORC/modifiedbySakuraba";
		picture="COS_casques\data\icon\ic_MARITIME_F_ca.paa";
		model="\COS_casques\Maritime_F";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"COS_casques\data\MARITIME\Maritime_TAN_co.paa"
		};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=25;
			uniformModel="\COS_casques\Maritime_F";
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"COS_casques\data\MARITIME\Maritime_TAN_co.paa"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					Armor=8;
					passThrough=0.5;
				};
			};
		};
	};
	class Maritime_L_TAN: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		displayName=".Maritime_L_Tan";
		_generalMacro="Maritime_L_TAN";
		author="ORC/modifiedbySakuraba";
		picture="COS_casques\data\icon\ic_MARITIME_ca.paa";
		model="\COS_casques\Maritime_L";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"COS_casques\data\MARITIME\Maritime_TAN_co.paa"
		};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=25;
			uniformModel="\COS_casques\Maritime_L";
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"COS_casques\data\Maritime_TAN_co.paa"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					Armor=8;
					passThrough=0.5;
				};
			};
		};
	};
	class Mich2001_ess_od: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		displayName=".Mich2001_Ess_Od";
		_generalMacro="Mich2001_ess_od";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\ic_MICH2001_DES_ca.paa";
		model="\COS_casques\Mich2001_ess";
		hiddenSelections[]={};
		hiddenSelectionsTextures[]={};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=25;
			uniformModel="\COS_casques\Mich2001_ess";
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]={};
			hiddenSelectionsTextures[]={};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					Armor=8;
					passThrough=0.5;
				};
			};
		};
	};
	class Mich2001_ess_des: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		displayName=".Mich2001_Ess_Des";
		_generalMacro="Mich2001_ess_des";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\ic_MICH2001_DES_ca.paa";
		model="\COS_casques\Mich2001_ess";
		hiddenSelections[]=
		{
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"COS_casques\data\light_helmet\Helmet_Base_des.co.paa"
		};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=25;
			uniformModel="\COS_casques\Mich2001_ess";
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]=
			{
				"camo1"
			};
			hiddenSelectionsTextures[]=
			{
				"COS_casques\data\light_helmet\Helmet_Base_des.co.paa"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					Armor=8;
					passThrough=0.5;
				};
			};
		};
	};
	class Mich2001_ess_snk: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		displayName=".Mich2001_Ess_Snk";
		_generalMacro="Mich2001_ess_snk";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\ic_MICH2001_SNK_ca.paa";
		model="\COS_casques\Mich2001_ess";
		hiddenSelections[]=
		{
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"COS_casques\data\light_helmet\Helmet_Base_snk.co.paa"
		};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=25;
			uniformModel="\COS_casques\Mich2001_ess";
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]=
			{
				"camo1"
			};
			hiddenSelectionsTextures[]=
			{
				"COS_casques\data\light_helmet\Helmet_Base_snk.co.paa"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					Armor=8;
					passThrough=0.5;
				};
			};
		};
	};
	class Mich2001_strap_od: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		displayName=".Mich2001_Strap_Od";
		_generalMacro="Mich2001_strap_od";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\ic_MICH2001_OD_ca.paa";
		model="\COS_casques\Mich2001_equip";
		hiddenSelections[]={};
		hiddenSelectionsTextures[]={};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=23;
			uniformModel="\COS_casques\Mich2001_equip";
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]={};
			hiddenSelectionsTextures[]={};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					Armor=8;
					passThrough=0.5;
				};
			};
		};
	};
	class Mich2001_strap_des: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		displayName=".Mich2001_Strap_Des";
		_generalMacro="Mich2001_strap_des";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\ic_MICH2001_DES_ca.paa";
		model="\COS_casques\Mich2001_equip";
		hiddenSelections[]=
		{
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"COS_casques\data\light_helmet\Helmet_Base_des.co.paa"
		};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=23;
			uniformModel="\COS_casques\Mich2001_equip";
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]=
			{
				"camo1"
			};
			hiddenSelectionsTextures[]=
			{
				"COS_casques\data\light_helmet\Helmet_Base_des.co.paa"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					Armor=8;
					passThrough=0.5;
				};
			};
		};
	};
	class Mich2001_strap_snk: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		displayName=".Mich2001_Strap_Snk";
		_generalMacro="Mich2001_strap_snk";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\ic_MICH2001_SNK_ca.paa";
		model="\COS_casques\Mich2001_equip";
		hiddenSelections[]=
		{
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"COS_casques\data\light_helmet\Helmet_Base_snk.co.paa"
		};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=23;
			uniformModel="\COS_casques\Mich2001_equip";
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]=
			{
				"camo1"
			};
			hiddenSelectionsTextures[]=
			{
				"COS_casques\data\light_helmet\Helmet_Base_snk.co.paa"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					Armor=8;
					passThrough=0.5;
				};
			};
		};
	};
	class Mich2001_od: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		displayName=".Mich2001_Od";
		_generalMacro="Mich2001_od";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\ic_MICH2001_OD_ca.paa";
		model="\COS_casques\Mich2001";
		hiddenSelections[]={};
		hiddenSelectionsTextures[]={};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=20;
			uniformModel="\COS_casques\Mich2001";
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]={};
			hiddenSelectionsTextures[]={};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					Armor=8;
					passThrough=0.5;
				};
			};
		};
	};
	class Mich2001_des: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		displayName=".Mich2001_Des";
		_generalMacro="Mich2001_des";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\ic_MICH2001_DES_ca.paa";
		model="\COS_casques\Mich2001";
		hiddenSelections[]=
		{
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"COS_casques\data\light_helmet\Helmet_Base_des.co.paa"
		};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=20;
			uniformModel="\COS_casques\Mich2001";
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]=
			{
				"camo1"
			};
			hiddenSelectionsTextures[]=
			{
				"COS_casques\data\light_helmet\Helmet_Base_des.co.paa"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					Armor=8;
					passThrough=0.5;
				};
			};
		};
	};
	class Mich2001_snk: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		displayName=".Mich2001_Snk";
		_generalMacro="Mich2001_snk";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\ic_MICH2001_SNK_ca.paa";
		model="\COS_casques\Mich2001";
		hiddenSelections[]=
		{
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"COS_casques\data\light_helmet\Helmet_Base_snk.co.paa"
		};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=20;
			uniformModel="\COS_casques\Mich2001";
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]=
			{
				"camo1"
			};
			hiddenSelectionsTextures[]=
			{
				"COS_casques\data\light_helmet\Helmet_Base_snk.co.paa"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					Armor=8;
					passThrough=0.5;
				};
			};
		};
	};
	class OPS_CORE_strap_F: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		displayName=".OpsCore_Strap_Full";
		_generalMacro="OPS_CORE_strap_F";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\OPS_CORE_ca.paa";
		model="\COS_casques\fast_helmet_equip_F";
		hiddenSelections[]={};
		hiddenSelectionsTextures[]={};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=27;
			uniformModel="\COS_casques\fast_helmet_equip_F";
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]={};
			hiddenSelectionsTextures[]={};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					Armor=8;
					passThrough=0.5;
				};
			};
		};
	};
	class OPS_CORE_strap: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		displayName=".OpsCore_Strap";
		_generalMacro="OPS_CORE_strap";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\OPS_CORE_ca.paa";
		model="\COS_casques\fast_helmet_equip";
		hiddenSelections[]={};
		hiddenSelectionsTextures[]={};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=27;
			uniformModel="\COS_casques\fast_helmet_equip";
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]={};
			hiddenSelectionsTextures[]={};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					Armor=8;
					passThrough=0.5;
				};
			};
		};
	};
	class OPS_CORE_strap_ESS: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		displayName=".OpsCore_Strap_goggle";
		_generalMacro="OPS_CORE_strap_ESS";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\OPS_CORE_ca.paa";
		model="\COS_casques\fast_helmet_equip_ESS";
		hiddenSelections[]={};
		hiddenSelectionsTextures[]={};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=31;
			uniformModel="\COS_casques\fast_helmet_equip_ESS";
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]={};
			hiddenSelectionsTextures[]={};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					Armor=8;
					passThrough=0.5;
				};
			};
		};
	};
	class OPS_CORE_ESS: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		displayName=".OpsCore_Goggle";
		_generalMacro="OPS_CORE_ESS";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\OPS_CORE_ca.paa";
		model="\COS_casques\fast_helmet_ESS";
		hiddenSelections[]={};
		hiddenSelectionsTextures[]={};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=31;
			uniformModel="\COS_casques\fast_helmet_ESS";
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]={};
			hiddenSelectionsTextures[]={};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					Armor=8;
					passThrough=0.5;
				};
			};
		};
	};
	class OPS_CORE: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		displayName=".OpsCore";
		_generalMacro="OPS_CORE";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\OPS_CORE_ca.paa";
		model="\COS_casques\fast_helmet";
		hiddenSelections[]={};
		hiddenSelectionsTextures[]={};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=31;
			uniformModel="\COS_casques\fast_helmet";
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]={};
			hiddenSelectionsTextures[]={};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					Armor=8;
					passThrough=0.5;
				};
			};
		};
	};
	class OPS_CORE_F: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		displayName=".OpsCore_Full";
		_generalMacro="OPS_CORE_F";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\OPS_CORE_ca.paa";
		model="\COS_casques\fast_helmet_F";
		hiddenSelections[]={};
		hiddenSelectionsTextures[]={};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=31;
			uniformModel="\COS_casques\fast_helmet_F";
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]={};
			hiddenSelectionsTextures[]={};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					Armor=8;
					passThrough=0.5;
				};
			};
		};
	};
	class PROTECH: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		displayName=".PROTECH";
		_generalMacro="PROTECH";
		author="modifiedbySakuraba";
		picture="COS_casques\data\icon\patch_COS.ca.paa";
		model="\COS_casques\PROTECH";
		hiddenSelections[]=
		{
			"camo",
			"camo3"
		};
		hiddenSelectionsTextures[]=
		{
			"cos_casques\data\protech\prohelmet_co.paa",
			"cos_casques\data\casques\protech\protech_strap.co.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"cos_casques\data\protech\prohelmet.rvmat",
			""
		};
		class ItemInfo: HeadgearItem
		{
			mass=19;
			uniformModel="\COS_casques\PROTECH";
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]=
			{
				"camo",
				"camo3"
			};
			hiddenSelectionsTextures[]=
			{
				"cos_casques\data\protech\prohelmet_co.paa",
				"cos_casques\data\casques\protech\protech_strap.co.paa"
			};
			hiddenSelectionsMaterials[]=
			{
				"cos_casques\data\protech\prohelmet.rvmat",
				""
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					Armor=8;
					passThrough=0.5;
				};
			};
		};
	};
	class Mohawk_Core_cover_OD: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		_generalMacro="Mohawk_Core_cover_OD";
		displayName=".Mohawk_cover_OD";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\ic_helmet_fs_OD_ca.paa";
		model="\COS_casques\OPS_helmet_CUSTO";
		hiddenSelections[]=
		{
			"camo",
			"camo2",
			"camo3"
		};
		hiddenSelectionsTextures[]=
		{
			"COS_casques\data\helmet_OD_co.paa"
		};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=33;
			uniformModel="\COS_casques\OPS_helmet_CUSTO";
			hiddenSelections[]=
			{
				"camo",
				"camo2",
				"camo3"
			};
			hiddenSelectionsTextures[]=
			{
				"COS_casques\data\helmet_OD_co.paa"
			};
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor=6;
			passThrough=0.5;
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=6;
					passThrough=0.5;
				};
			};
		};
	};
	class Mohawk_Core_cover_tan: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		_generalMacro="Mohawk_Core_cover_tan";
		displayName=".Mohawk_cover_tan";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\ic_helmet_fs_tan_ca.paa";
		model="\COS_casques\OPS_helmet_CUSTO";
		hiddenSelections[]=
		{
			"camo",
			"camo2",
			"camo3"
		};
		hiddenSelectionsTextures[]=
		{
			"COS_casques\data\helmet_TAN_co.paa"
		};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=33;
			uniformModel="\COS_casques\OPS_helmet_CUSTO";
			hiddenSelections[]=
			{
				"camo",
				"camo2",
				"camo3"
			};
			hiddenSelectionsTextures[]=
			{
				"COS_casques\data\helmet_TAN_co.paa"
			};
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor=6;
			passThrough=0.5;
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=6;
					passThrough=0.5;
				};
			};
		};
	};
	class Mohawk_Core_cover_ce: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		_generalMacro="Mohawk_Core_cover_ce";
		displayName=".Mohawk_cover_ce";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\ic_helmet_fs_ce_ca.paa";
		model="\COS_casques\OPS_helmet_CUSTO";
		hiddenSelections[]=
		{
			"camo",
			"camo2",
			"camo3"
		};
		hiddenSelectionsTextures[]=
		{
			"COS_casques\data\helmet_ce_co.paa"
		};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=33;
			uniformModel="\COS_casques\OPS_helmet_CUSTO";
			hiddenSelections[]=
			{
				"camo",
				"camo2",
				"camo3"
			};
			hiddenSelectionsTextures[]=
			{
				"COS_casques\data\helmet_ce_co.paa"
			};
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor=6;
			passThrough=0.5;
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=6;
					passThrough=0.5;
				};
			};
		};
	};
	class Mohawk_Core_cover_mtp: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		_generalMacro="Mohawk_Core_cover_mtp";
		displayName=".Mohawk_cover_mtp";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\ic_helmet_fs_scorpion_ca.paa";
		model="\COS_casques\OPS_helmet_CUSTO";
		hiddenSelections[]=
		{
			"camo",
			"camo2",
			"camo3"
		};
		hiddenSelectionsTextures[]=
		{
			"COS_casques\data\helmet_mtp_co.paa"
		};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=33;
			uniformModel="\COS_casques\OPS_helmet_CUSTO";
			hiddenSelections[]=
			{
				"camo",
				"camo2",
				"camo3"
			};
			hiddenSelectionsTextures[]=
			{
				"COS_casques\data\helmet_mtp_co.paa"
			};
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor=6;
			passThrough=0.5;
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=6;
					passThrough=0.5;
				};
			};
		};
	};
	class Mohawk_Core_S_OD: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		_generalMacro="Mohawk_Core_S_OD";
		displayName=".Mohawk_Simple_OD";
		author="3d_artist/modifiedby.&.Sakuraba";
		picture="COS_casques\data\icon\ic_helmet_fs_OD_ca.paa";
		model="\COS_casques\OPS_helmet_CUSTO_3";
		hiddenSelections[]=
		{
			"camo",
			"camo2",
			"camo3"
		};
		hiddenSelectionsTextures[]=
		{
			"COS_casques\data\helmet_OD_co.paa"
		};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=21;
			uniformModel="\COS_casques\OPS_helmet_CUSTO_3";
			hiddenSelections[]=
			{
				"camo",
				"camo2",
				"camo3"
			};
			hiddenSelectionsTextures[]=
			{
				"COS_casques\data\helmet_OD_co.paa"
			};
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor=6;
			passThrough=0.5;
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=6;
					passThrough=0.5;
				};
			};
		};
	};
	class Mohawk_Core_S_TAN: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		_generalMacro="Mohawk_Core_S_TAN";
		displayName=".Mohawk_Simple_TAN";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\ic_helmet_fs_TAN_ca.paa";
		model="\COS_casques\OPS_helmet_CUSTO_3";
		hiddenSelections[]=
		{
			"camo",
			"camo2",
			"camo3"
		};
		hiddenSelectionsTextures[]=
		{
			"COS_casques\data\helmet_tan_co.paa"
		};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=21;
			uniformModel="\COS_casques\OPS_helmet_CUSTO_3";
			hiddenSelections[]=
			{
				"camo",
				"camo2",
				"camo3"
			};
			hiddenSelectionsTextures[]=
			{
				"COS_casques\data\helmet_TAN_co.paa"
			};
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor=6;
			passThrough=0.5;
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=6;
					passThrough=0.5;
				};
			};
		};
	};
	class Mohawk_Core_S_CE: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		_generalMacro="Mohawk_Core_S_CE";
		displayName=".Mohawk_Simple_CE";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\ic_helmet_fs_CE_ca.paa";
		model="\COS_casques\OPS_helmet_CUSTO_3";
		hiddenSelections[]=
		{
			"camo",
			"camo2",
			"camo3"
		};
		hiddenSelectionsTextures[]=
		{
			"COS_casques\data\helmet_ce_co.paa"
		};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=21;
			uniformModel="\COS_casques\OPS_helmet_CUSTO_3";
			hiddenSelections[]=
			{
				"camo",
				"camo2",
				"camo3"
			};
			hiddenSelectionsTextures[]=
			{
				"COS_casques\data\helmet_CE_co.paa"
			};
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor=6;
			passThrough=0.5;
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=6;
					passThrough=0.5;
				};
			};
		};
	};
	class Mohawk_Core_S_mtp: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		_generalMacro="Mohawk_Core_S_mtp";
		displayName=".Mohawk_Simple_mtp";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\ic_helmet_fs_scorpion_ca.paa";
		model="\COS_casques\OPS_helmet_CUSTO_3";
		hiddenSelections[]=
		{
			"camo",
			"camo2",
			"camo3"
		};
		hiddenSelectionsTextures[]=
		{
			"COS_casques\data\helmet_mtp_co.paa"
		};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=21;
			uniformModel="\COS_casques\OPS_helmet_CUSTO_3";
			hiddenSelections[]=
			{
				"camo",
				"camo2",
				"camo3"
			};
			hiddenSelectionsTextures[]=
			{
				"COS_casques\data\helmet_mtp_co.paa"
			};
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor=6;
			passThrough=0.5;
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=6;
					passThrough=0.5;
				};
			};
		};
	};
	class Mohawk_Core_cyalumen_OD: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		_generalMacro="Mohawk_Core_cyalumen_OD";
		displayName=".Mohawk_cyalumen_OD";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\ic_helmet_fs_OD_ca.paa";
		model="\COS_casques\OPS_helmet_CUSTO_5";
		hiddenSelections[]=
		{
			"camo",
			"camo3"
		};
		hiddenSelectionsTextures[]=
		{
			"COS_casques\data\helmet_OD_co.paa"
		};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=31;
			uniformModel="\COS_casques\OPS_helmet_CUSTO_5";
			hiddenSelections[]=
			{
				"camo",
				"camo3"
			};
			hiddenSelectionsTextures[]=
			{
				"COS_casques\data\helmet_OD_co.paa"
			};
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor=6;
			passThrough=0.5;
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=6;
					passThrough=0.5;
				};
			};
		};
	};
	class Mohawk_Core_cyalumen_tan: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		_generalMacro="Mohawk_Core_cyalumen_tan";
		displayName=".Mohawk_cyalumen_tan";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\ic_helmet_fs_tan_ca.paa";
		model="\COS_casques\OPS_helmet_CUSTO_5";
		hiddenSelections[]=
		{
			"camo",
			"camo3"
		};
		hiddenSelectionsTextures[]=
		{
			"COS_casques\data\helmet_tan_co.paa"
		};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=31;
			uniformModel="\COS_casques\OPS_helmet_CUSTO_5";
			hiddenSelections[]=
			{
				"camo",
				"camo3"
			};
			hiddenSelectionsTextures[]=
			{
				"COS_casques\data\helmet_tan_co.paa"
			};
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor=6;
			passThrough=0.5;
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=6;
					passThrough=0.5;
				};
			};
		};
	};
	class Mohawk_Core_cyalumen_ce: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		_generalMacro="Mohawk_Core_cyalumen_ce";
		displayName=".Mohawk_cyalumen_ce";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\ic_helmet_fs_ce_ca.paa";
		model="\COS_casques\OPS_helmet_CUSTO_5";
		hiddenSelections[]=
		{
			"camo",
			"camo3"
		};
		hiddenSelectionsTextures[]=
		{
			"COS_casques\data\helmet_ce_co.paa"
		};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=31;
			uniformModel="\COS_casques\OPS_helmet_CUSTO_5";
			hiddenSelections[]=
			{
				"camo",
				"camo3"
			};
			hiddenSelectionsTextures[]=
			{
				"COS_casques\data\helmet_ce_co.paa"
			};
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor=6;
			passThrough=0.5;
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=6;
					passThrough=0.5;
				};
			};
		};
	};
	class Mohawk_Core_cyalumen_MTP: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		_generalMacro="Mohawk_Core_cyalumen_MTP";
		displayName=".Mohawk_cyalumen_mtp";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\ic_helmet_fs_scorpion_ca.paa";
		model="\COS_casques\OPS_helmet_CUSTO_5";
		hiddenSelections[]=
		{
			"camo",
			"camo3"
		};
		hiddenSelectionsTextures[]=
		{
			"COS_casques\data\helmet_MTP_co.paa"
		};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=31;
			uniformModel="\COS_casques\OPS_helmet_CUSTO_5";
			hiddenSelections[]=
			{
				"camo",
				"camo3"
			};
			hiddenSelectionsTextures[]=
			{
				"COS_casques\data\helmet_MTP_co.paa"
			};
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor=6;
			passThrough=0.5;
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=6;
					passThrough=0.5;
				};
			};
		};
	};
	class Mohawk_Core_MANTA_OD: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		_generalMacro="Mohawk_Core_MANTA_OD";
		displayName=".Mohawk_MANTA_OD";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\ic_helmet_fs_OD_ca.paa";
		model="\COS_casques\OPS_helmet_CUSTO_6";
		hiddenSelections[]=
		{
			"camo",
			"camo3"
		};
		hiddenSelectionsTextures[]=
		{
			"COS_casques\data\helmet_OD_co.paa"
		};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=31;
			uniformModel="\COS_casques\OPS_helmet_CUSTO_6";
			hiddenSelections[]=
			{
				"camo",
				"camo3"
			};
			hiddenSelectionsTextures[]=
			{
				"COS_casques\data\helmet_OD_co.paa"
			};
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor=6;
			passThrough=0.5;
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=6;
					passThrough=0.5;
				};
			};
		};
	};
	class Mohawk_Core_MANTA_tan: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		_generalMacro="Mohawk_Core_MANTA_tan";
		displayName=".Mohawk_MANTA_tan";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\ic_helmet_fs_tan_ca.paa";
		model="\COS_casques\OPS_helmet_CUSTO_6";
		hiddenSelections[]=
		{
			"camo",
			"camo3"
		};
		hiddenSelectionsTextures[]=
		{
			"COS_casques\data\helmet_tan_co.paa"
		};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=31;
			uniformModel="\COS_casques\OPS_helmet_CUSTO_6";
			hiddenSelections[]=
			{
				"camo",
				"camo3"
			};
			hiddenSelectionsTextures[]=
			{
				"COS_casques\data\helmet_tan_co.paa"
			};
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor=6;
			passThrough=0.5;
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=6;
					passThrough=0.5;
				};
			};
		};
	};
	class Mohawk_Core_MANTA_ce: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		_generalMacro="Mohawk_Core_MANTA_ce";
		displayName=".Mohawk_MANTA_ce";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\ic_helmet_fs_ce_ca.paa";
		model="\COS_casques\OPS_helmet_CUSTO_6";
		hiddenSelections[]=
		{
			"camo",
			"camo3"
		};
		hiddenSelectionsTextures[]=
		{
			"COS_casques\data\helmet_ce_co.paa"
		};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=31;
			uniformModel="\COS_casques\OPS_helmet_CUSTO_6";
			hiddenSelections[]=
			{
				"camo",
				"camo3"
			};
			hiddenSelectionsTextures[]=
			{
				"COS_casques\data\helmet_ce_co.paa"
			};
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor=6;
			passThrough=0.5;
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=6;
					passThrough=0.5;
				};
			};
		};
	};
	class Mohawk_Core_MANTA_MTP: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		_generalMacro="Mohawk_Core_MANTA_MTP";
		displayName=".Mohawk_MANTA_MTP";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\ic_helmet_fs_scorpion_ca.paa";
		model="\COS_casques\OPS_helmet_CUSTO_6";
		hiddenSelections[]=
		{
			"camo",
			"camo3"
		};
		hiddenSelectionsTextures[]=
		{
			"COS_casques\data\helmet_MTP_co.paa"
		};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=31;
			uniformModel="\COS_casques\OPS_helmet_CUSTO_6";
			hiddenSelections[]=
			{
				"camo",
				"camo3"
			};
			hiddenSelectionsTextures[]=
			{
				"COS_casques\data\helmet_MTP_co.paa"
			};
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor=6;
			passThrough=0.5;
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=6;
					passThrough=0.5;
				};
			};
		};
	};
	class Mohawk_Core_ESS_OD: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		_generalMacro="Mohawk_Core_ESS_OD";
		displayName=".Mohawk_ESS_OD";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\ic_helmet_fs_OD_ca.paa";
		model="\COS_casques\OPS_helmet_ESS";
		hiddenSelections[]=
		{
			"camo",
			"camo3"
		};
		hiddenSelectionsTextures[]=
		{
			"COS_casques\data\helmet_OD_co.paa"
		};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=31;
			uniformModel="\COS_casques\OPS_helmet_ESS";
			hiddenSelections[]=
			{
				"camo",
				"camo3"
			};
			hiddenSelectionsTextures[]=
			{
				"COS_casques\data\helmet_OD_co.paa"
			};
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor=6;
			passThrough=0.5;
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=6;
					passThrough=0.5;
				};
			};
		};
	};
	class Mohawk_Core_ESS_tan: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		_generalMacro="Mohawk_Core_ESS_tan";
		displayName=".Mohawk_ESS_tan";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\ic_helmet_fs_tan_ca.paa";
		model="\COS_casques\OPS_helmet_ESS";
		hiddenSelections[]=
		{
			"camo",
			"camo3"
		};
		hiddenSelectionsTextures[]=
		{
			"COS_casques\data\helmet_tan_co.paa"
		};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=31;
			uniformModel="\COS_casques\OPS_helmet_ESS";
			hiddenSelections[]=
			{
				"camo",
				"camo3"
			};
			hiddenSelectionsTextures[]=
			{
				"COS_casques\data\helmet_tan_co.paa"
			};
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor=6;
			passThrough=0.5;
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=6;
					passThrough=0.5;
				};
			};
		};
	};
	class Mohawk_Core_ESS_ce: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		_generalMacro="Mohawk_Core_ESS_ce";
		displayName=".Mohawk_ESS_ce";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\ic_helmet_fs_ce_ca.paa";
		model="\COS_casques\OPS_helmet_ESS";
		hiddenSelections[]=
		{
			"camo",
			"camo3"
		};
		hiddenSelectionsTextures[]=
		{
			"COS_casques\data\helmet_ce_co.paa"
		};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=31;
			uniformModel="\COS_casques\OPS_helmet_ESS";
			hiddenSelections[]=
			{
				"camo",
				"camo3"
			};
			hiddenSelectionsTextures[]=
			{
				"COS_casques\data\helmet_ce_co.paa"
			};
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor=6;
			passThrough=0.5;
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=6;
					passThrough=0.5;
				};
			};
		};
	};
	class Mohawk_Core_ESS_MTP: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponPoolAvailable=1;
		_generalMacro="Mohawk_Core_ESS_MTP";
		displayName=".Mohawk_ESS_MTP";
		author="3d_artist/modifiedbySakuraba";
		picture="COS_casques\data\icon\ic_helmet_fs_scorpion_ca.paa";
		model="\COS_casques\OPS_helmet_ESS";
		hiddenSelections[]=
		{
			"camo",
			"camo3"
		};
		hiddenSelectionsTextures[]=
		{
			"COS_casques\data\helmet_MTP_co.paa"
		};
		hiddenSelectionsMaterials[]={};
		class ItemInfo: HeadgearItem
		{
			mass=31;
			uniformModel="\COS_casques\OPS_helmet_ESS";
			hiddenSelections[]=
			{
				"camo",
				"camo3"
			};
			hiddenSelectionsTextures[]=
			{
				"COS_casques\data\helmet_MTP_co.paa"
			};
			allowedSlots[]={701,901};
			modelSides[]={3,1};
			armor=6;
			passThrough=0.5;
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=6;
					passThrough=0.5;
				};
			};
		};
	};
};
class cfgMods
{
	author="sakuraba";
	timepacked=1509622537;
};
