//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 196.146114 on Stable branch
// Generated with ALiVE version 1.11.3.1905291
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class O_RussiaMercenaries_Winter {
        displayName = "Russian Mercenaries";
        side = 0;
        flag = "\a3\Data_F_Enoch\Flags\flag_RUS_co.paa";
        icon = "\a3\Data_F_Enoch\Flags\flag_RUS_co.paa";
        priority = 3;
    };
};

class CfgGroups {
    class EAST {

        class O_RussiaMercenaries_Winter {
            name = "Russian Mercenaries";

            class Infantry {
                name = "Infantry";

            };

            class SpecOps {
                name = "Infantry";

                class o_russiamercenaries_specops_fire_team_winter {
                    name = "Fire Team";
                    side = 0;
                    faction = "O_RussiaMercenaries_Winter";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "LIEUTENANT";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Team_Leader_Winter_02";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Auto_Rifleman_Winter_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Combat_Life_Saver_Winter_02";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Rifleman_Winter_01";
                    };
                };

                class o_russiamercenaries_specops_recon_fireteam_winter {
                    name = "Recon Fireteam";
                    side = 0;
                    faction = "O_RussiaMercenaries_Winter";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "LIEUTENANT";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Team_Leader_Winter_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Autorifleman_Winter_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Combat_Life_Saver_Winter_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Recon_Rifleman_Winter_01";
                    };
                };

                class o_russiamercenaries_specops_at_team_winter {
                    name = "AT Team";
                    side = 0;
                    faction = "O_RussiaMercenaries_Winter";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Rifleman_AT_Winter_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Rifleman_Winter_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Team_Leader_Winter_01";
                    };
                };

                class o_russiamercenaries_specops_recon_at_team_winter {
                    name = "Recon AT Team";
                    side = 0;
                    faction = "O_RussiaMercenaries_Winter";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Rifleman_AT_Winter_02";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Team_Leader_Winter_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Recon_Rifleman_Winter_01";
                    };
                };

                class o_russiamercenaries_specops_sniper_team_winter {
                    name = "Sniper Team";
                    side = 0;
                    faction = "O_RussiaMercenaries_Winter";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Sharpshooter_Winter_02";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_JTAC_Winter_01";
                    };
                };

                class o_russiamercenaries_specops_recon_sniper_team_winter {
                    name = "Recon Sniper Team";
                    side = 0;
                    faction = "O_RussiaMercenaries_Winter";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Sharpshooter_Winter_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_JTAC_Winter_01";
                    };
                };

                class o_russiamercenaries_specops_mg_team_winter {
                    name = "MG Team";
                    side = 0;
                    faction = "O_RussiaMercenaries_Winter";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Machinegunner_Winter_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_MG_Assistant_Winter_01";
                    };
                };

                class o_russiamercenaries_specops_sentry_winter {
                    name = "Sentry";
                    side = 0;
                    faction = "O_RussiaMercenaries_Winter";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Rifleman_Winter_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Grenadier_Winter_02";
                    };
                };

                class o_russiamercenaries_specops_recon_sentry_winter {
                    name = "Recon Sentry";
                    side = 0;
                    faction = "O_RussiaMercenaries_Winter";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Marksman_Winter_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Recon_Rifleman_Winter_01";
                    };
                };

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

                class o_russiamercenaries_support_sapper_team_winter {
                    name = "Sapper Team";
                    side = 0;
                    faction = "O_RussiaMercenaries_Winter";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Explosive_Specialist_Winter_02";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Grenadier_Winter_02";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Rifleman_Winter_01";
                    };
                };

                class o_russiamercenaries_support_recon_sapper_team_winter {
                    name = "Recon Sapper Team";
                    side = 0;
                    faction = "O_RussiaMercenaries_Winter";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Explosive_Specialist_Winter_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Recon_Rifleman_Winter_01";
                    };
                };

                class o_russiamercenaries_support_command_group_winter {
                    name = "Command Group";
                    side = 0;
                    faction = "O_RussiaMercenaries_Winter";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CAPTAIN";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Team_Leader_Winter_02";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_JTAC_Winter_02";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Rifleman_Winter_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Rifleman_AT_Winter_01";
                    };
                };

                class o_russiamercenaries_support_recon_command_group_winter {
                    name = "Recon Command Group";
                    side = 0;
                    faction = "O_RussiaMercenaries_Winter";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CAPTAIN";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Team_Leader_Winter_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_JTAC_Winter_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Recon_Rifleman_Winter_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Rifleman_AT_Winter_02";
                    };
                };

                class o_russiamercenaries_support_engineer_team_winter {
                    name = "Engineer Team";
                    side = 0;
                    faction = "O_RussiaMercenaries_Winter";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "LIEUTENANT";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Engineer_Winter_02";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Rifleman_Winter_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Auto_Rifleman_Winter_01";
                    };
                };

                class o_russiamercenaries_support_recon_engineer_team_winter {
                    name = "Recon Engineer Team";
                    side = 0;
                    faction = "O_RussiaMercenaries_Winter";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "LIEUTENANT";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Engineer_Winter_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Autorifleman_Winter_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RussiaMercenaries_Recon_Rifleman_Winter_01";
                    };
                };

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class O_R_Patrol_Soldier_Engineer_F;
    class O_R_Patrol_Soldier_Engineer_F_OCimport_01 : O_R_Patrol_Soldier_Engineer_F { scope = 0; class EventHandlers; };
    class O_R_Patrol_Soldier_Engineer_F_OCimport_02 : O_R_Patrol_Soldier_Engineer_F_OCimport_01 { class EventHandlers; };

    class O_R_Soldier_TL_F;
    class O_R_Soldier_TL_F_OCimport_01 : O_R_Soldier_TL_F { scope = 0; class EventHandlers; };
    class O_R_Soldier_TL_F_OCimport_02 : O_R_Soldier_TL_F_OCimport_01 { class EventHandlers; };

    class O_R_Soldier_GL_F;
    class O_R_Soldier_GL_F_OCimport_01 : O_R_Soldier_GL_F { scope = 0; class EventHandlers; };
    class O_R_Soldier_GL_F_OCimport_02 : O_R_Soldier_GL_F_OCimport_01 { class EventHandlers; };

    class O_R_soldier_exp_F;
    class O_R_soldier_exp_F_OCimport_01 : O_R_soldier_exp_F { scope = 0; class EventHandlers; };
    class O_R_soldier_exp_F_OCimport_02 : O_R_soldier_exp_F_OCimport_01 { class EventHandlers; };

    class O_R_Soldier_AR_F;
    class O_R_Soldier_AR_F_OCimport_01 : O_R_Soldier_AR_F { scope = 0; class EventHandlers; };
    class O_R_Soldier_AR_F_OCimport_02 : O_R_Soldier_AR_F_OCimport_01 { class EventHandlers; };

    class O_R_soldier_M_F;
    class O_R_soldier_M_F_OCimport_01 : O_R_soldier_M_F { scope = 0; class EventHandlers; };
    class O_R_soldier_M_F_OCimport_02 : O_R_soldier_M_F_OCimport_01 { class EventHandlers; };

    class O_R_medic_F;
    class O_R_medic_F_OCimport_01 : O_R_medic_F { scope = 0; class EventHandlers; };
    class O_R_medic_F_OCimport_02 : O_R_medic_F_OCimport_01 { class EventHandlers; };

    class O_R_Patrol_Soldier_LAT_F;
    class O_R_Patrol_Soldier_LAT_F_OCimport_01 : O_R_Patrol_Soldier_LAT_F { scope = 0; class EventHandlers; };
    class O_R_Patrol_Soldier_LAT_F_OCimport_02 : O_R_Patrol_Soldier_LAT_F_OCimport_01 { class EventHandlers; };

    class O_R_JTAC_F;
    class O_R_JTAC_F_OCimport_01 : O_R_JTAC_F { scope = 0; class EventHandlers; };
    class O_R_JTAC_F_OCimport_02 : O_R_JTAC_F_OCimport_01 { class EventHandlers; };

    class O_R_Patrol_Soldier_M_F;
    class O_R_Patrol_Soldier_M_F_OCimport_01 : O_R_Patrol_Soldier_M_F { scope = 0; class EventHandlers; };
    class O_R_Patrol_Soldier_M_F_OCimport_02 : O_R_Patrol_Soldier_M_F_OCimport_01 { class EventHandlers; };

    class CUP_I_LSV_02_unarmed_ION;
    class CUP_I_LSV_02_unarmed_ION_OCimport_01 : CUP_I_LSV_02_unarmed_ION { scope = 0; class EventHandlers; class Turrets; };
    class CUP_I_LSV_02_unarmed_ION_OCimport_02 : CUP_I_LSV_02_unarmed_ION_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
        };
    };

    class CUP_I_SUV_ION;
    class CUP_I_SUV_ION_OCimport_01 : CUP_I_SUV_ION { scope = 0; class EventHandlers; class Turrets; };
    class CUP_I_SUV_ION_OCimport_02 : CUP_I_SUV_ION_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
            class CargoTurret_07;
            class CargoTurret_08;
            class CargoTurret_09;
        };
    };

    class I_E_Quadbike_01_F;
    class I_E_Quadbike_01_F_OCimport_01 : I_E_Quadbike_01_F { scope = 0; class EventHandlers; };
    class I_E_Quadbike_01_F_OCimport_02 : I_E_Quadbike_01_F_OCimport_01 { scope = 0; class EventHandlers; };

    class CUP_O_PBX_RU;
    class CUP_O_PBX_RU_OCimport_01 : CUP_O_PBX_RU { scope = 0; class EventHandlers; class Turrets; };
    class CUP_O_PBX_RU_OCimport_02 : CUP_O_PBX_RU_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
        };
    };

    class fsg_tigr_2;
    class fsg_tigr_2_OCimport_01 : fsg_tigr_2 { scope = 0; class EventHandlers; class Turrets; };
    class fsg_tigr_2_OCimport_02 : fsg_tigr_2_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class AGS_Turret;
        };
    };

    class RCOMM_wnato_mrap;
    class RCOMM_wnato_mrap_OCimport_01 : RCOMM_wnato_mrap { scope = 0; class EventHandlers; };
    class RCOMM_wnato_mrap_OCimport_02 : RCOMM_wnato_mrap_OCimport_01 { scope = 0; class EventHandlers; };

    class fsg_tigr_3;
    class fsg_tigr_3_OCimport_01 : fsg_tigr_3 { scope = 0; class EventHandlers; class Turrets; };
    class fsg_tigr_3_OCimport_02 : fsg_tigr_3_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
        };
    };


    class O_RussiaMercenaries_Engineer_Winter_01 : O_R_Patrol_Soldier_Engineer_F_OCimport_02 {
        author = "Pants";
        scope = 2;
        scopeCurator = 2;
        displayName = "Recon Engineer";
        side = 0;
        faction = "O_RussiaMercenaries_Winter";

        identityTypes[] = {"Head_Russian","LanguageRUS_F","G_RUS_SF"};

        uniformClass = "milgp_u_fleece_grey_g3_field_pants_mcalpine";

        linkedItems[] = {"CUP_V_PMC_CIRAS_Winter_Patrol","rhsusf_opscore_bk","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_GPNVG_black"};
        respawnlinkedItems[] = {"CUP_V_PMC_CIRAS_Winter_Patrol","rhsusf_opscore_bk","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_GPNVG_black"};

        weapons[] = {"hlc_rifle_ak12","hgun_Rook40_F","Laserdesignator_01_khk_F"};
        respawnWeapons[] = {"hlc_rifle_ak12","hgun_Rook40_F","Laserdesignator_01_khk_F"};

        magazines[] = {"hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","Laserbatteries","hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","Laserbatteries"};
        respawnMagazines[] = {"hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","Laserbatteries","hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","Laserbatteries"};

        backpack = "CUP_B_MedicPack_ACU";

        ALiVE_orbatCreator_loadout[] = {{"hlc_rifle_ak12","CUP_muzzle_TGPA","CUP_acc_LLM_black","hlc_optic_HensoldtZO_lo_Docter_2D",{"hlc_30Rnd_545x39_B_AK",30},{},"rhs_acc_grip_ffg2"},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"milgp_u_fleece_grey_g3_field_pants_mcalpine",{{"ACE_fieldDressing",2},{"ACE_elasticBandage",3},{"ACE_quikclot",3},{"ACE_atropine",1},{"ACE_adenosine",1},{"ACE_CableTie",1},{"ACE_epinephrine",2},{"ACE_MapTools",1},{"MRH_Map",1},{"ACE_morphine",2},{"ACE_packingBandage",3},{"adv_aceSplint_splint",1},{"ACE_tourniquet",2}}},{"CUP_V_PMC_CIRAS_Winter_Patrol",{{"HandGrenade",2,1}}},{"CUP_B_MedicPack_ACU",{{"ToolKit",1},{"MineDetector",1},{"ACE_Cellphone",1},{"ACE_DefusalKit",1},{"APERSBoundingMine_Range_Mag",2,1}}},"rhsusf_opscore_bk","shesh_cover_tan",{"Laserdesignator_01_khk_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_GPNVG_black"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RussiaMercenaries_Team_Leader_Winter_01 : O_R_Soldier_TL_F_OCimport_02 {
        author = "Pants";
        scope = 2;
        scopeCurator = 2;
        displayName = "Recon Team Leader";
        side = 0;
        faction = "O_RussiaMercenaries_Winter";

        identityTypes[] = {"Head_Enoch","LanguageRUS_F","G_RUS_SF"};

        uniformClass = "TRYK_U_B_Snowt";

        linkedItems[] = {"CUP_V_PMC_CIRAS_Winter_Grenadier","ALP_opscore","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_GPNVG_winter"};
        respawnlinkedItems[] = {"CUP_V_PMC_CIRAS_Winter_Grenadier","ALP_opscore","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_GPNVG_winter"};

        weapons[] = {"hlc_rifle_ak12GL","hgun_Rook40_F","Rangefinder"};
        respawnWeapons[] = {"hlc_rifle_ak12GL","hgun_Rook40_F","Rangefinder"};

        magazines[] = {"hlc_30Rnd_545x39_B_AK","hlc_VOG25_AK","16Rnd_9x21_Mag","hlc_30Rnd_545x39_B_AK","hlc_VOG25_AK","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"hlc_30Rnd_545x39_B_AK","hlc_VOG25_AK","16Rnd_9x21_Mag","hlc_30Rnd_545x39_B_AK","hlc_VOG25_AK","16Rnd_9x21_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"hlc_rifle_ak12GL","CUP_muzzle_TGPA","CUP_acc_LLM_black","hlc_optic_HensoldtZO_lo_Docter",{"hlc_30Rnd_545x39_B_AK",30},{"hlc_VOG25_AK",1},""},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"TRYK_U_B_Snowt",{{"ACE_fieldDressing",1},{"ACE_packingBandage",1},{"ACE_morphine",1},{"ACE_tourniquet",1},{"hlc_30Rnd_545x39_B_AK",3,30}}},{"CUP_V_PMC_CIRAS_Winter_Grenadier",{{"16Rnd_9x21_Mag",2,17},{"SmokeShell",1,1},{"SmokeShellRed",1,1},{"SmokeShellOrange",1,1},{"Chemlight_red",2,1},{"1Rnd_Smoke_Grenade_shell",2,1},{"1Rnd_SmokeRed_Grenade_shell",1,1},{"1Rnd_SmokeOrange_Grenade_shell",1,1},{"1Rnd_SmokeYellow_Grenade_shell",1,1},{"hlc_VOG25_AK",3,1},{"rhs_30Rnd_545x39_7N10_2mag_AK",3,30},{"rhs_mag_m67",2,1}}},{},"ALP_opscore","CUP_G_ESS_KHK_Facewrap_White",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_GPNVG_winter"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RussiaMercenaries_Grenadier_Winter_01 : O_R_Soldier_GL_F_OCimport_02 {
        author = "Pants";
        scope = 2;
        scopeCurator = 2;
        displayName = "Recon Grenadier";
        side = 0;
        faction = "O_RussiaMercenaries_Winter";

        identityTypes[] = {"Head_Russian","LanguageRUS_F","G_RUS_SF"};

        uniformClass = "milgp_u_pcu_g3_field_pants_mcalpine";

        linkedItems[] = {"CUP_V_PMC_CIRAS_Winter_Grenadier","WHT_opscore","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"};
        respawnlinkedItems[] = {"CUP_V_PMC_CIRAS_Winter_Grenadier","WHT_opscore","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"};

        weapons[] = {"hlc_rifle_ak12GL","hgun_Rook40_F","Binocular"};
        respawnWeapons[] = {"hlc_rifle_ak12GL","hgun_Rook40_F","Binocular"};

        magazines[] = {"hlc_30Rnd_545x39_B_AK","hlc_VOG25_AK","16Rnd_9x21_Mag","hlc_30Rnd_545x39_B_AK","hlc_VOG25_AK","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"hlc_30Rnd_545x39_B_AK","hlc_VOG25_AK","16Rnd_9x21_Mag","hlc_30Rnd_545x39_B_AK","hlc_VOG25_AK","16Rnd_9x21_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"hlc_rifle_ak12GL","CUP_muzzle_TGPA","CUP_acc_LLM_black","hlc_optic_HensoldtZO_lo_Docter",{"hlc_30Rnd_545x39_B_AK",30},{"hlc_VOG25_AK",1},""},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"milgp_u_pcu_g3_field_pants_mcalpine",{{"ACE_fieldDressing",1},{"ACE_packingBandage",1},{"ACE_morphine",1},{"ACE_tourniquet",1},{"hlc_30Rnd_545x39_B_AK",3,30}}},{"CUP_V_PMC_CIRAS_Winter_Grenadier",{{"HandGrenade",2,1},{"SmokeShell",1,1},{"SmokeShellRed",1,1},{"Chemlight_red",2,1},{"hlc_VOG25_AK",3,1},{"16Rnd_9x21_Mag",3,17},{"CUP_30Rnd_545x39_AK74M_M",4,30},{"CUP_IlumFlareRed_GP25_M",1,1},{"hlc_GRD_Red",1,1}}},{},"WHT_opscore","VSM_Facemask_black_Goggles",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RussiaMercenaries_Explosive_Specialist_Winter_01 : O_R_soldier_exp_F_OCimport_02 {
        author = "Pants";
        scope = 2;
        scopeCurator = 2;
        displayName = "Recon Explosive Specialist";
        side = 0;
        faction = "O_RussiaMercenaries_Winter";

        identityTypes[] = {"Head_Russian","LanguageRUS_F","G_RUS_SF"};

        uniformClass = "milgp_u_g3_field_set_mcalpine";

        linkedItems[] = {"CUP_V_PMC_CIRAS_Winter_TL","rhsusf_opscore_bk_pelt","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","A3_GPNVG18_BLK_F"};
        respawnlinkedItems[] = {"CUP_V_PMC_CIRAS_Winter_TL","rhsusf_opscore_bk_pelt","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","A3_GPNVG18_BLK_F"};

        weapons[] = {"hlc_rifle_aku12","hgun_Rook40_F","Binocular"};
        respawnWeapons[] = {"hlc_rifle_aku12","hgun_Rook40_F","Binocular"};

        magazines[] = {"hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag"};

        backpack = "Alpine_Carryall";

        ALiVE_orbatCreator_loadout[] = {{"hlc_rifle_aku12","CUP_muzzle_snds_KZRZP_AK545","CUP_acc_LLM_black","CUP_optic_HoloBlack",{"hlc_30Rnd_545x39_B_AK",30},{},"rhs_acc_grip_ffg2"},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"milgp_u_g3_field_set_mcalpine",{{"ACE_packingBandage",3},{"ACE_morphine",2},{"ACE_tourniquet",1},{"ACE_fieldDressing",2},{"ACE_elasticBandage",2},{"ACE_quikclot",2},{"ACE_epinephrine",2},{"ACE_MapTools",1},{"hlc_30Rnd_545x39_B_AK",3,30}}},{"CUP_V_PMC_CIRAS_Winter_TL",{{"16Rnd_9x21_Mag",2,17},{"APERSMine_Range_Mag",3,1},{"HandGrenade",2,1},{"SmokeShell",1,1},{"SmokeShellRed",1,1},{"Chemlight_red",2,1},{"CUP_30Rnd_545x39_AK74M_M",3,30}}},{"Alpine_Carryall",{{"ToolKit",1},{"MineDetector",1},{"ACE_Clacker",1},{"APERSBoundingMine_Range_Mag",2,1},{"DemoCharge_Remote_Mag",2,1},{"CUP_IED_V1_M",1,1},{"ClaymoreDirectionalMine_Remote_Mag",1,1}}},"rhsusf_opscore_bk_pelt","G_Balaclava_blk",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","A3_GPNVG18_BLK_F"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RussiaMercenaries_Autorifleman_Winter_01 : O_R_Soldier_AR_F_OCimport_02 {
        author = "Pants";
        scope = 2;
        scopeCurator = 2;
        displayName = "Recon Autorifleman";
        side = 0;
        faction = "O_RussiaMercenaries_Winter";

        identityTypes[] = {"Head_Enoch","LanguageRUS_F","G_RUS_SF"};

        uniformClass = "Alpine_Crye_Grey_Shirt_SS_Camo";

        linkedItems[] = {"CUP_V_PMC_CIRAS_Winter_Patrol","TRYK_H_Helmet_Winter","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_GPNVG_winter"};
        respawnlinkedItems[] = {"CUP_V_PMC_CIRAS_Winter_Patrol","TRYK_H_Helmet_Winter","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_GPNVG_winter"};

        weapons[] = {"hlc_rifle_RPK12","hgun_Rook40_F"};
        respawnWeapons[] = {"hlc_rifle_RPK12","hgun_Rook40_F"};

        magazines[] = {"hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag"};

        backpack = "Alpine_backpack_kitbag";

        ALiVE_orbatCreator_loadout[] = {{"hlc_rifle_RPK12","CUP_muzzle_TGPA","CUP_acc_LLM_black","hlc_optic_HensoldtZO_lo_Docter",{"hlc_30Rnd_545x39_B_AK",30},{},"rhs_acc_grip_ffg2"},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"Alpine_Crye_Grey_Shirt_SS_Camo",{{"ACE_EarPlugs",1},{"ACE_fieldDressing",1},{"ACE_packingBandage",3},{"ACE_morphine",2},{"ACE_tourniquet",2},{"ACE_quikclot",2},{"ACE_elasticBandage",2},{"ACE_atropine",1},{"ACE_adenosine",1},{"ACE_epinephrine",2},{"SmokeShell",1,1},{"hlc_30Rnd_545x39_B_AK",2,30}}},{"CUP_V_PMC_CIRAS_Winter_Patrol",{{"16Rnd_9x21_Mag",2,17},{"HandGrenade",1,1},{"SmokeShellRed",1,1},{"Chemlight_red",2,1},{"hlc_30Rnd_545x39_B_AK",1,30},{"CUP_60Rnd_545x39_AK74M_M",3,60}}},{"Alpine_backpack_kitbag",{{"CUP_60Rnd_545x39_AK74M_M",3,60}}},"TRYK_H_Helmet_Winter","G_Balaclava_blk",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_GPNVG_winter"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RussiaMercenaries_Marksman_Winter_01 : O_R_soldier_M_F_OCimport_02 {
        author = "Pants";
        scope = 2;
        scopeCurator = 2;
        displayName = "Recon Marksman";
        side = 0;
        faction = "O_RussiaMercenaries_Winter";

        identityTypes[] = {"Head_Russian","LanguageRUS_F","G_RUS_SF"};

        uniformClass = "Alpine_Crye_Camo";

        linkedItems[] = {"CUP_V_PMC_CIRAS_Winter_TL","RCOMM_wnato_h_helmetlight","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","A3_GPNVG18_BLK_F"};
        respawnlinkedItems[] = {"CUP_V_PMC_CIRAS_Winter_TL","RCOMM_wnato_h_helmetlight","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","A3_GPNVG18_BLK_F"};

        weapons[] = {"srifle_DMR_04_DMS_weathered_Kir_F_F","hgun_Rook40_F","Laserdesignator_03"};
        respawnWeapons[] = {"srifle_DMR_04_DMS_weathered_Kir_F_F","hgun_Rook40_F","Laserdesignator_03"};

        magazines[] = {"10Rnd_127x54_Mag","16Rnd_9x21_Mag","Laserbatteries","10Rnd_127x54_Mag","16Rnd_9x21_Mag","Laserbatteries"};
        respawnMagazines[] = {"10Rnd_127x54_Mag","16Rnd_9x21_Mag","Laserbatteries","10Rnd_127x54_Mag","16Rnd_9x21_Mag","Laserbatteries"};

        ALiVE_orbatCreator_loadout[] = {{"srifle_DMR_04_DMS_weathered_Kir_F_F","","acc_pointer_IR","optic_DMS_weathered_Kir_F",{"10Rnd_127x54_Mag",10},{},"bipod_02_F_blk"},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"Alpine_Crye_Camo",{{"ACE_fieldDressing",1},{"ACE_packingBandage",3},{"ACE_morphine",2},{"ACE_tourniquet",2},{"ACE_quikclot",1},{"adv_aceSplint_splint",1},{"10Rnd_127x54_Mag",2,10}}},{"CUP_V_PMC_CIRAS_Winter_TL",{{"10Rnd_127x54_Mag",7,10},{"16Rnd_9x21_Mag",2,17},{"HandGrenade",2,1},{"SmokeShell",1,1}}},{},"RCOMM_wnato_h_helmetlight","CUP_G_ESS_KHK_Facewrap_White",{"Laserdesignator_03","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","A3_GPNVG18_BLK_F"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RussiaMercenaries_Combat_Life_Saver_Winter_01 : O_R_medic_F_OCimport_02 {
        author = "Pants";
        scope = 2;
        scopeCurator = 2;
        displayName = "Recon Combat Life Saver";
        side = 0;
        faction = "O_RussiaMercenaries_Winter";

        identityTypes[] = {"Head_Russian","LanguageRUS_F","G_RUS_SF"};

        uniformClass = "Alpine_Crye_Grey_Shirt_SS_Camo";

        linkedItems[] = {"CUP_V_PMC_CIRAS_Winter_Patrol","ALP_opscore","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_GPNVG_winter"};
        respawnlinkedItems[] = {"CUP_V_PMC_CIRAS_Winter_Patrol","ALP_opscore","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_GPNVG_winter"};

        weapons[] = {"hlc_rifle_aku12","hgun_Rook40_F","Binocular"};
        respawnWeapons[] = {"hlc_rifle_aku12","hgun_Rook40_F","Binocular"};

        magazines[] = {"hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag"};

        backpack = "CUP_B_MedicPack_ACU";

        ALiVE_orbatCreator_loadout[] = {{"hlc_rifle_aku12","CUP_muzzle_snds_KZRZP_AK545","CUP_acc_LLM01_L","optic_ACO_grn",{"hlc_30Rnd_545x39_B_AK",30},{},"rhs_acc_grip_ffg2"},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"Alpine_Crye_Grey_Shirt_SS_Camo",{{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_morphine",5},{"ACE_tourniquet",5},{"adv_aceSplint_splint",2},{"hlc_30Rnd_545x39_B_AK",1,30},{"CUP_30Rnd_545x39_AK74M_M",2,30}}},{"CUP_V_PMC_CIRAS_Winter_Patrol",{{"ACE_fieldDressing",6},{"ACE_packingBandage",6},{"ACE_morphine",6},{"ACE_tourniquet",6},{"16Rnd_9x21_Mag",2,17},{"SmokeShell",1,1},{"SmokeShellRed",1,1},{"SmokeShellOrange",1,1},{"SmokeShellYellow",1,1},{"Chemlight_red",2,1},{"hlc_30Rnd_545x39_B_AK",2,30}}},{"CUP_B_MedicPack_ACU",{{"ACE_fieldDressing",1},{"ACE_packingBandage",19},{"ACE_epinephrine",17},{"ACE_morphine",15},{"ACE_salineIV_250",1},{"ACE_tourniquet",4},{"ACE_elasticBandage",23},{"ACE_quikclot",21},{"ACE_bloodIV_500",1},{"ACE_bodyBag",1},{"ACE_Canteen",1},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_XL50",1},{"ACE_plasmaIV_500",1},{"ACE_plasmaIV_250",1},{"SmokeShellRed",1,1},{"SmokeShellBlue",1,1},{"SmokeShellOrange",1,1}}},"ALP_opscore","CUP_G_ESS_BLK_Scarf_White",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_GPNVG_winter"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RussiaMercenaries_Rifleman_AT_Winter_02 : O_R_Patrol_Soldier_LAT_F_OCimport_02 {
        author = "Pants";
        scope = 2;
        scopeCurator = 2;
        displayName = "Recon Rifleman (AT)";
        side = 0;
        faction = "O_RussiaMercenaries_Winter";

        identityTypes[] = {"Head_Russian","LanguageRUS_F","G_RUS_SF"};

        uniformClass = "milgp_u_fleece_grey_g3_field_pants_mcalpine";

        linkedItems[] = {"CUP_V_PMC_CIRAS_Winter_TL","CUP_H_OpsCore_Grey","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","A3_GPNVG18_BLK_TI"};
        respawnlinkedItems[] = {"CUP_V_PMC_CIRAS_Winter_TL","CUP_H_OpsCore_Grey","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","A3_GPNVG18_BLK_TI"};

        weapons[] = {"hlc_rifle_ak12","launch_MRAWS_white_rail_F","hgun_Rook40_F","Rangefinder"};
        respawnWeapons[] = {"hlc_rifle_ak12","launch_MRAWS_white_rail_F","hgun_Rook40_F","Rangefinder"};

        magazines[] = {"hlc_30Rnd_545x39_B_AK","MRAWS_HEAT_F","16Rnd_9x21_Mag","hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"hlc_30Rnd_545x39_B_AK","MRAWS_HEAT_F","16Rnd_9x21_Mag","hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag"};

        backpack = "Alpine_backpack_kitbag";

        ALiVE_orbatCreator_loadout[] = {{"hlc_rifle_ak12","CUP_muzzle_TGPA","CUP_acc_LLM_od","CUP_optic_HensoldtZO_low_RDS",{"hlc_30Rnd_545x39_B_AK",30},{},"rhs_acc_grip_ffg2"},{"launch_MRAWS_white_rail_F","","","",{"MRAWS_HEAT_F",1},{},""},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"milgp_u_fleece_grey_g3_field_pants_mcalpine",{{"ACE_EarPlugs",1},{"ACE_fieldDressing",2},{"ACE_packingBandage",2},{"ACE_morphine",2},{"ACE_tourniquet",2},{"16Rnd_9x21_Mag",1,17},{"hlc_30Rnd_545x39_B_AK",2,30}}},{"CUP_V_PMC_CIRAS_Winter_TL",{{"HandGrenade",3,1},{"SmokeShell",2,1},{"CUP_30Rnd_545x39_AK74M_M",5,30}}},{"Alpine_backpack_kitbag",{{"MRAWS_HEAT_F",2,1},{"CUP_MAAWS_HEDP_M",2,1}}},"CUP_H_OpsCore_Grey","milgp_f_face_shield_tactical_BLK",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","A3_GPNVG18_BLK_TI"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RussiaMercenaries_JTAC_Winter_01 : O_R_JTAC_F_OCimport_02 {
        author = "Pants";
        scope = 2;
        scopeCurator = 2;
        displayName = "Recon JTAC";
        side = 0;
        faction = "O_RussiaMercenaries_Winter";

        identityTypes[] = {"Head_Enoch","LanguageRUS_F","G_RUS_SF"};

        uniformClass = "milgp_u_g3_field_set_mcalpine";

        linkedItems[] = {"CUP_V_PMC_CIRAS_Winter_TL","TRYK_H_Helmet_Winter","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","CUP_NVG_GPNVG_winter"};
        respawnlinkedItems[] = {"CUP_V_PMC_CIRAS_Winter_TL","TRYK_H_Helmet_Winter","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","CUP_NVG_GPNVG_winter"};

        weapons[] = {"hlc_rifle_ak12","hgun_Rook40_F","Laserdesignator_01_khk_F"};
        respawnWeapons[] = {"hlc_rifle_ak12","hgun_Rook40_F","Laserdesignator_01_khk_F"};

        magazines[] = {"hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","Laserbatteries","hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","Laserbatteries"};
        respawnMagazines[] = {"hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","Laserbatteries","hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","Laserbatteries"};

        backpack = "tfw_ilbe_whip_alpine";

        ALiVE_orbatCreator_loadout[] = {{"hlc_rifle_ak12","CUP_muzzle_TGPA","CUP_acc_LLM_black","hlc_optic_HensoldtZO_lo_Docter",{"hlc_30Rnd_545x39_B_AK",30},{},"rhs_acc_grip_ffg2"},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"milgp_u_g3_field_set_mcalpine",{{"ACE_fieldDressing",3},{"ACE_packingBandage",3},{"ACE_morphine",2},{"ACE_tourniquet",1},{"ACE_elasticBandage",3},{"ACE_epinephrine",2},{"ACE_MapTools",1},{"MRH_Map",1},{"16Rnd_9x21_Mag",2,17},{"MiniGrenade",1,1},{"Chemlight_red",1,1},{"hlc_30Rnd_545x39_B_AK",1,30}}},{"CUP_V_PMC_CIRAS_Winter_TL",{{"MiniGrenade",1,1},{"O_R_IR_Grenade",2,1},{"SmokeShell",1,1},{"SmokeShellRed",1,1},{"Chemlight_red",1,1},{"CUP_30Rnd_545x39_AK74M_M",5,30}}},{"tfw_ilbe_whip_alpine",{{"ACE_SpottingScope",1},{"tfw_dd",1},{"ACE_wirecutter",1},{"tfw_rf3080Item",1},{"adv_aceSplint_splint",1},{"ACE_rope12",1},{"ACE_microDAGR",1},{"ACE_IR_Strobe_Item",2},{"ACE_Chemlight_IR",2,1},{"O_R_IR_Grenade",2,1}}},"TRYK_H_Helmet_Winter","CUP_G_ESS_KHK_Facewrap_White",{"Laserdesignator_01_khk_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","CUP_NVG_GPNVG_winter"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RussiaMercenaries_Sharpshooter_Winter_01 : O_R_Patrol_Soldier_M_F_OCimport_02 {
        author = "Pants";
        scope = 2;
        scopeCurator = 2;
        displayName = "Recon Sharpshooter";
        side = 0;
        faction = "O_RussiaMercenaries_Winter";

        identityTypes[] = {"Head_Russian","LanguageRUS_F","G_RUS_SF"};

        uniformClass = "RCOMM_wnato_uniform_ghillie";

        linkedItems[] = {"dr_ALPlbt_op","CUP_H_PMC_Beanie_Headphones_Winter","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_GPNVG_winter"};
        respawnlinkedItems[] = {"dr_ALPlbt_op","CUP_H_PMC_Beanie_Headphones_Winter","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_GPNVG_winter"};

        weapons[] = {"rhs_weap_XM2010","hgun_Rook40_F","Rangefinder"};
        respawnWeapons[] = {"rhs_weap_XM2010","hgun_Rook40_F","Rangefinder"};

        magazines[] = {"rhsusf_5Rnd_300winmag_xm2010","16Rnd_9x21_Mag","rhsusf_5Rnd_300winmag_xm2010","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"rhsusf_5Rnd_300winmag_xm2010","16Rnd_9x21_Mag","rhsusf_5Rnd_300winmag_xm2010","16Rnd_9x21_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_XM2010","rhsusf_acc_M2010S_wd","ACE_acc_pointer_green","hlc_optic_ATACR_Offset",{"rhsusf_5Rnd_300winmag_xm2010",5},{},"bipod_01_F_blk"},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"RCOMM_wnato_uniform_ghillie",{{"ACE_fieldDressing",2},{"ACE_packingBandage",3},{"ACE_morphine",2},{"ACE_tourniquet",2},{"ACE_elasticBandage",2},{"ACE_Canteen_Half",1},{"ACE_epinephrine",2},{"ACE_EntrenchingTool",2},{"ACE_IR_Strobe_Item",1},{"MRH_Map",1},{"ACE_MapTools",1},{"ACE_Kestrel4500",1},{"ACE_RangeCard",1},{"16Rnd_9x21_Mag",1,17},{"rhsusf_5Rnd_300winmag_xm2010",3,5}}},{"dr_ALPlbt_op",{{"ACE_wirecutter",1},{"ACE_MRE_CreamChickenSoup",1},{"ACE_MRE_CreamTomatoSoup",1},{"ACE_microDAGR",1},{"HandGrenade",2,1},{"SmokeShell",3,1},{"16Rnd_9x21_Mag",2,17},{"hlc_5rnd_300WM_FMJ_AWM",3,5},{"hlc_5rnd_300WM_mk248_AWM",2,5},{"hlc_5rnd_300WM_AP_AWM",2,5},{"SmokeShellRed",1,1},{"SmokeShellPurple",1,1}}},{},"CUP_H_PMC_Beanie_Headphones_Winter","CUP_G_ESS_BLK_Scarf_White",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_GPNVG_winter"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RussiaMercenaries_Team_Leader_Winter_02 : O_RussiaMercenaries_Team_Leader_Winter_01 {
        author = "Pants";
        scope = 2;
        scopeCurator = 2;
        displayName = "Team Leader";
        side = 0;
        faction = "O_RussiaMercenaries_Winter";

        identityTypes[] = {"Head_Enoch","LanguageRUS_F","G_RUS_SF"};

        uniformClass = "TRYK_U_B_Snowt";

        linkedItems[] = {"CUP_V_PMC_CIRAS_Winter_Grenadier","ALP_opscore","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_GPNVG_winter"};
        respawnlinkedItems[] = {"CUP_V_PMC_CIRAS_Winter_Grenadier","ALP_opscore","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_GPNVG_winter"};

        weapons[] = {"hlc_rifle_ak12GL","hgun_Rook40_F","Rangefinder"};
        respawnWeapons[] = {"hlc_rifle_ak12GL","hgun_Rook40_F","Rangefinder"};

        magazines[] = {"hlc_30Rnd_545x39_B_AK","hlc_VOG25_AK","16Rnd_9x21_Mag","hlc_30Rnd_545x39_B_AK","hlc_VOG25_AK","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"hlc_30Rnd_545x39_B_AK","hlc_VOG25_AK","16Rnd_9x21_Mag","hlc_30Rnd_545x39_B_AK","hlc_VOG25_AK","16Rnd_9x21_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"hlc_rifle_ak12GL","","CUP_acc_LLM_black","hlc_optic_HensoldtZO_lo_Docter",{"hlc_30Rnd_545x39_B_AK",30},{"hlc_VOG25_AK",1},""},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"TRYK_U_B_Snowt",{{"ACE_fieldDressing",1},{"ACE_packingBandage",1},{"ACE_morphine",1},{"ACE_tourniquet",1},{"hlc_30Rnd_545x39_B_AK",3,30}}},{"CUP_V_PMC_CIRAS_Winter_Grenadier",{{"16Rnd_9x21_Mag",2,17},{"SmokeShell",1,1},{"SmokeShellRed",1,1},{"SmokeShellOrange",1,1},{"Chemlight_red",2,1},{"1Rnd_Smoke_Grenade_shell",2,1},{"1Rnd_SmokeRed_Grenade_shell",1,1},{"1Rnd_SmokeOrange_Grenade_shell",1,1},{"1Rnd_SmokeYellow_Grenade_shell",1,1},{"hlc_VOG25_AK",3,1},{"rhs_30Rnd_545x39_7N10_2mag_AK",3,30},{"rhs_mag_m67",2,1}}},{},"ALP_opscore","",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_GPNVG_winter"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RussiaMercenaries_Grenadier_Winter_02 : O_RussiaMercenaries_Grenadier_Winter_01 {
        author = "Pants";
        scope = 2;
        scopeCurator = 2;
        displayName = "Grenadier";
        side = 0;
        faction = "O_RussiaMercenaries_Winter";

        identityTypes[] = {"Head_Russian","LanguageRUS_F","G_RUS_SF"};

        uniformClass = "milgp_u_pcu_g3_field_pants_mcalpine";

        linkedItems[] = {"CUP_V_PMC_CIRAS_Winter_Grenadier","WHT_opscore","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"};
        respawnlinkedItems[] = {"CUP_V_PMC_CIRAS_Winter_Grenadier","WHT_opscore","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"};

        weapons[] = {"hlc_rifle_ak12GL","hgun_Rook40_F","Binocular"};
        respawnWeapons[] = {"hlc_rifle_ak12GL","hgun_Rook40_F","Binocular"};

        magazines[] = {"hlc_30Rnd_545x39_B_AK","hlc_VOG25_AK","16Rnd_9x21_Mag","hlc_30Rnd_545x39_B_AK","hlc_VOG25_AK","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"hlc_30Rnd_545x39_B_AK","hlc_VOG25_AK","16Rnd_9x21_Mag","hlc_30Rnd_545x39_B_AK","hlc_VOG25_AK","16Rnd_9x21_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"hlc_rifle_ak12GL","","CUP_acc_LLM_black","hlc_optic_HensoldtZO_lo_Docter",{"hlc_30Rnd_545x39_B_AK",30},{"hlc_VOG25_AK",1},""},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"milgp_u_pcu_g3_field_pants_mcalpine",{{"ACE_fieldDressing",1},{"ACE_packingBandage",1},{"ACE_morphine",1},{"ACE_tourniquet",1},{"hlc_30Rnd_545x39_B_AK",3,30}}},{"CUP_V_PMC_CIRAS_Winter_Grenadier",{{"HandGrenade",2,1},{"SmokeShell",1,1},{"SmokeShellRed",1,1},{"Chemlight_red",2,1},{"hlc_VOG25_AK",3,1},{"16Rnd_9x21_Mag",3,17},{"CUP_30Rnd_545x39_AK74M_M",4,30},{"CUP_IlumFlareRed_GP25_M",1,1},{"hlc_GRD_Red",1,1}}},{},"WHT_opscore","rhs_balaclava1_olive",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RussiaMercenaries_Explosive_Specialist_Winter_02 : O_RussiaMercenaries_Explosive_Specialist_Winter_01 {
        author = "Pants";
        scope = 2;
        scopeCurator = 2;
        displayName = "Explosive Specialist";
        side = 0;
        faction = "O_RussiaMercenaries_Winter";

        identityTypes[] = {"Head_Russian","LanguageRUS_F","G_RUS_SF"};

        uniformClass = "milgp_u_g3_field_set_mcalpine";

        linkedItems[] = {"CUP_V_PMC_CIRAS_Winter_TL","rhsusf_opscore_bk_pelt","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","A3_GPNVG18_BLK_F"};
        respawnlinkedItems[] = {"CUP_V_PMC_CIRAS_Winter_TL","rhsusf_opscore_bk_pelt","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","A3_GPNVG18_BLK_F"};

        weapons[] = {"hlc_rifle_aku12","hgun_Rook40_F","Binocular"};
        respawnWeapons[] = {"hlc_rifle_aku12","hgun_Rook40_F","Binocular"};

        magazines[] = {"hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag"};

        backpack = "Alpine_Carryall";

        ALiVE_orbatCreator_loadout[] = {{"hlc_rifle_aku12","","CUP_acc_LLM_black","CUP_optic_HoloBlack",{"hlc_30Rnd_545x39_B_AK",30},{},"rhs_acc_grip_ffg2"},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"milgp_u_g3_field_set_mcalpine",{{"ACE_packingBandage",3},{"ACE_morphine",2},{"ACE_tourniquet",1},{"ACE_fieldDressing",2},{"ACE_elasticBandage",2},{"ACE_quikclot",2},{"ACE_epinephrine",2},{"ACE_MapTools",1},{"hlc_30Rnd_545x39_B_AK",3,30}}},{"CUP_V_PMC_CIRAS_Winter_TL",{{"16Rnd_9x21_Mag",2,17},{"APERSMine_Range_Mag",3,1},{"HandGrenade",2,1},{"SmokeShell",1,1},{"SmokeShellRed",1,1},{"Chemlight_red",2,1},{"CUP_30Rnd_545x39_AK74M_M",3,30}}},{"Alpine_Carryall",{{"ToolKit",1},{"MineDetector",1},{"ACE_Clacker",1},{"APERSBoundingMine_Range_Mag",2,1},{"DemoCharge_Remote_Mag",2,1},{"CUP_IED_V1_M",1,1},{"ClaymoreDirectionalMine_Remote_Mag",1,1}}},"rhsusf_opscore_bk_pelt","TRYK_Shemagh_ESS_WH",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","A3_GPNVG18_BLK_F"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RussiaMercenaries_Auto_Rifleman_Winter_01 : O_RussiaMercenaries_Autorifleman_Winter_01 {
        author = "Pants";
        scope = 2;
        scopeCurator = 2;
        displayName = "Auto Rifleman";
        side = 0;
        faction = "O_RussiaMercenaries_Winter";

        identityTypes[] = {"Head_Enoch","LanguageRUS_F","G_RUS_SF"};

        uniformClass = "Alpine_Crye_Grey_Shirt_SS_Camo";

        linkedItems[] = {"CUP_V_PMC_CIRAS_Winter_Patrol","TRYK_H_Helmet_Winter","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_GPNVG_winter"};
        respawnlinkedItems[] = {"CUP_V_PMC_CIRAS_Winter_Patrol","TRYK_H_Helmet_Winter","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_GPNVG_winter"};

        weapons[] = {"hlc_rifle_RPK12","hgun_Rook40_F"};
        respawnWeapons[] = {"hlc_rifle_RPK12","hgun_Rook40_F"};

        magazines[] = {"hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag"};

        backpack = "Alpine_backpack_kitbag";

        ALiVE_orbatCreator_loadout[] = {{"hlc_rifle_RPK12","","CUP_acc_LLM_black","hlc_optic_HensoldtZO_lo_Docter",{"hlc_30Rnd_545x39_B_AK",30},{},"rhs_acc_grip_ffg2"},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"Alpine_Crye_Grey_Shirt_SS_Camo",{{"ACE_EarPlugs",1},{"ACE_fieldDressing",1},{"ACE_packingBandage",3},{"ACE_morphine",2},{"ACE_tourniquet",2},{"ACE_quikclot",2},{"ACE_elasticBandage",2},{"ACE_atropine",1},{"ACE_adenosine",1},{"ACE_epinephrine",2},{"SmokeShell",1,1},{"hlc_30Rnd_545x39_B_AK",2,30}}},{"CUP_V_PMC_CIRAS_Winter_Patrol",{{"16Rnd_9x21_Mag",2,17},{"HandGrenade",1,1},{"SmokeShellRed",1,1},{"Chemlight_red",2,1},{"hlc_30Rnd_545x39_B_AK",1,30},{"CUP_60Rnd_545x39_AK74M_M",3,60}}},{"Alpine_backpack_kitbag",{{"CUP_60Rnd_545x39_AK74M_M",3,60}}},"TRYK_H_Helmet_Winter","shesh_cover_tan",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_GPNVG_winter"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RussiaMercenaries_Combat_Life_Saver_Winter_02 : O_RussiaMercenaries_Combat_Life_Saver_Winter_01 {
        author = "Pants";
        scope = 2;
        scopeCurator = 2;
        displayName = "Combat Life Saver";
        side = 0;
        faction = "O_RussiaMercenaries_Winter";

        identityTypes[] = {"Head_Russian","LanguageRUS_F","G_RUS_SF"};

        uniformClass = "Alpine_Crye_Grey_Shirt_SS_Camo";

        linkedItems[] = {"CUP_V_PMC_CIRAS_Winter_Patrol","ALP_opscore","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_GPNVG_winter"};
        respawnlinkedItems[] = {"CUP_V_PMC_CIRAS_Winter_Patrol","ALP_opscore","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_GPNVG_winter"};

        weapons[] = {"hlc_rifle_aku12","hgun_Rook40_F","Binocular"};
        respawnWeapons[] = {"hlc_rifle_aku12","hgun_Rook40_F","Binocular"};

        magazines[] = {"hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag"};

        backpack = "CUP_B_MedicPack_ACU";

        ALiVE_orbatCreator_loadout[] = {{"hlc_rifle_aku12","","CUP_acc_LLM01_L","optic_ACO_grn",{"hlc_30Rnd_545x39_B_AK",30},{},"rhs_acc_grip_ffg2"},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"Alpine_Crye_Grey_Shirt_SS_Camo",{{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_morphine",5},{"ACE_tourniquet",5},{"adv_aceSplint_splint",2},{"hlc_30Rnd_545x39_B_AK",1,30},{"CUP_30Rnd_545x39_AK74M_M",2,30}}},{"CUP_V_PMC_CIRAS_Winter_Patrol",{{"ACE_fieldDressing",6},{"ACE_packingBandage",6},{"ACE_morphine",6},{"ACE_tourniquet",6},{"16Rnd_9x21_Mag",2,17},{"SmokeShell",1,1},{"SmokeShellRed",1,1},{"SmokeShellOrange",1,1},{"SmokeShellYellow",1,1},{"Chemlight_red",2,1},{"hlc_30Rnd_545x39_B_AK",2,30}}},{"CUP_B_MedicPack_ACU",{{"ACE_fieldDressing",1},{"ACE_packingBandage",19},{"ACE_epinephrine",17},{"ACE_morphine",15},{"ACE_salineIV_250",1},{"ACE_tourniquet",4},{"ACE_elasticBandage",23},{"ACE_quikclot",21},{"ACE_bloodIV_500",1},{"ACE_bodyBag",1},{"ACE_Canteen",1},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_XL50",1},{"ACE_plasmaIV_500",1},{"ACE_plasmaIV_250",1},{"SmokeShellRed",1,1},{"SmokeShellBlue",1,1},{"SmokeShellOrange",1,1}}},"ALP_opscore","rhs_balaclava",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_GPNVG_winter"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RussiaMercenaries_JTAC_Winter_02 : O_RussiaMercenaries_JTAC_Winter_01 {
        author = "Pants";
        scope = 2;
        scopeCurator = 2;
        displayName = "JTAC";
        side = 0;
        faction = "O_RussiaMercenaries_Winter";

        identityTypes[] = {"Head_Enoch","LanguageRUS_F","G_RUS_SF"};

        uniformClass = "milgp_u_g3_field_set_mcalpine";

        linkedItems[] = {"CUP_V_PMC_CIRAS_Winter_TL","TRYK_H_Helmet_Winter","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","CUP_NVG_GPNVG_winter"};
        respawnlinkedItems[] = {"CUP_V_PMC_CIRAS_Winter_TL","TRYK_H_Helmet_Winter","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","CUP_NVG_GPNVG_winter"};

        weapons[] = {"hlc_rifle_ak12","hgun_Rook40_F","Laserdesignator_01_khk_F"};
        respawnWeapons[] = {"hlc_rifle_ak12","hgun_Rook40_F","Laserdesignator_01_khk_F"};

        magazines[] = {"hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","Laserbatteries","hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","Laserbatteries"};
        respawnMagazines[] = {"hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","Laserbatteries","hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","Laserbatteries"};

        backpack = "tfw_ilbe_whip_alpine";

        ALiVE_orbatCreator_loadout[] = {{"hlc_rifle_ak12","","CUP_acc_LLM_black","hlc_optic_HensoldtZO_lo_Docter",{"hlc_30Rnd_545x39_B_AK",30},{},"rhs_acc_grip_ffg2"},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"milgp_u_g3_field_set_mcalpine",{{"ACE_fieldDressing",3},{"ACE_packingBandage",3},{"ACE_morphine",2},{"ACE_tourniquet",1},{"ACE_elasticBandage",3},{"ACE_epinephrine",2},{"ACE_MapTools",1},{"MRH_Map",1},{"16Rnd_9x21_Mag",2,17},{"MiniGrenade",1,1},{"Chemlight_red",1,1},{"hlc_30Rnd_545x39_B_AK",1,30}}},{"CUP_V_PMC_CIRAS_Winter_TL",{{"MiniGrenade",1,1},{"O_R_IR_Grenade",2,1},{"SmokeShell",1,1},{"SmokeShellRed",1,1},{"Chemlight_red",1,1},{"CUP_30Rnd_545x39_AK74M_M",5,30}}},{"tfw_ilbe_whip_alpine",{{"ACE_SpottingScope",1},{"tfw_dd",1},{"ACE_wirecutter",1},{"tfw_rf3080Item",1},{"adv_aceSplint_splint",1},{"ACE_rope12",1},{"ACE_microDAGR",1},{"ACE_IR_Strobe_Item",2},{"ACE_Chemlight_IR",2,1},{"O_R_IR_Grenade",2,1}}},"TRYK_H_Helmet_Winter","",{"Laserdesignator_01_khk_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","CUP_NVG_GPNVG_winter"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RussiaMercenaries_Sharpshooter_Winter_02 : O_RussiaMercenaries_Sharpshooter_Winter_01 {
        author = "Pants";
        scope = 2;
        scopeCurator = 2;
        displayName = "Sharpshooter";
        side = 0;
        faction = "O_RussiaMercenaries_Winter";

        identityTypes[] = {"Head_Russian","LanguageRUS_F","G_RUS_SF"};

        uniformClass = "RCOMM_wnato_uniform_ghillie";

        linkedItems[] = {"dr_ALPlbt_op","CUP_H_PMC_Beanie_Headphones_Winter","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_GPNVG_winter"};
        respawnlinkedItems[] = {"dr_ALPlbt_op","CUP_H_PMC_Beanie_Headphones_Winter","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_GPNVG_winter"};

        weapons[] = {"rhs_weap_XM2010","hgun_Rook40_F","Rangefinder"};
        respawnWeapons[] = {"rhs_weap_XM2010","hgun_Rook40_F","Rangefinder"};

        magazines[] = {"rhsusf_5Rnd_300winmag_xm2010","16Rnd_9x21_Mag","rhsusf_5Rnd_300winmag_xm2010","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"rhsusf_5Rnd_300winmag_xm2010","16Rnd_9x21_Mag","rhsusf_5Rnd_300winmag_xm2010","16Rnd_9x21_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_XM2010","","ACE_acc_pointer_green","hlc_optic_ATACR_Offset",{"rhsusf_5Rnd_300winmag_xm2010",5},{},"bipod_01_F_blk"},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"RCOMM_wnato_uniform_ghillie",{{"ACE_fieldDressing",2},{"ACE_packingBandage",3},{"ACE_morphine",2},{"ACE_tourniquet",2},{"ACE_elasticBandage",2},{"ACE_Canteen_Half",1},{"ACE_epinephrine",2},{"ACE_EntrenchingTool",2},{"ACE_IR_Strobe_Item",1},{"MRH_Map",1},{"ACE_MapTools",1},{"ACE_Kestrel4500",1},{"ACE_RangeCard",1},{"16Rnd_9x21_Mag",1,17},{"rhsusf_5Rnd_300winmag_xm2010",3,5}}},{"dr_ALPlbt_op",{{"ACE_wirecutter",1},{"ACE_MRE_CreamChickenSoup",1},{"ACE_MRE_CreamTomatoSoup",1},{"ACE_microDAGR",1},{"HandGrenade",2,1},{"SmokeShell",3,1},{"16Rnd_9x21_Mag",2,17},{"hlc_5rnd_300WM_FMJ_AWM",3,5},{"hlc_5rnd_300WM_mk248_AWM",2,5},{"hlc_5rnd_300WM_AP_AWM",2,5},{"SmokeShellRed",1,1},{"SmokeShellPurple",1,1}}},{},"CUP_H_PMC_Beanie_Headphones_Winter","shesh_cover_tan",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_GPNVG_winter"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RussiaMercenaries_Engineer_Winter_02 : O_RussiaMercenaries_Engineer_Winter_01 {
        author = "Pants";
        scope = 2;
        scopeCurator = 2;
        displayName = "Engineer";
        side = 0;
        faction = "O_RussiaMercenaries_Winter";

        identityTypes[] = {"Head_Russian","LanguageRUS_F","G_RUS_SF"};

        uniformClass = "milgp_u_fleece_grey_g3_field_pants_mcalpine";

        linkedItems[] = {"CUP_V_PMC_CIRAS_Winter_Patrol","rhsusf_opscore_bk","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_GPNVG_black"};
        respawnlinkedItems[] = {"CUP_V_PMC_CIRAS_Winter_Patrol","rhsusf_opscore_bk","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_GPNVG_black"};

        weapons[] = {"hlc_rifle_ak12","hgun_Rook40_F","Laserdesignator_01_khk_F"};
        respawnWeapons[] = {"hlc_rifle_ak12","hgun_Rook40_F","Laserdesignator_01_khk_F"};

        magazines[] = {"hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","Laserbatteries","hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","Laserbatteries"};
        respawnMagazines[] = {"hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","Laserbatteries","hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","Laserbatteries"};

        backpack = "CUP_B_MedicPack_ACU";

        ALiVE_orbatCreator_loadout[] = {{"hlc_rifle_ak12","","CUP_acc_LLM_black","hlc_optic_HensoldtZO_lo_Docter_2D",{"hlc_30Rnd_545x39_B_AK",30},{},"rhs_acc_grip_ffg2"},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"milgp_u_fleece_grey_g3_field_pants_mcalpine",{{"ACE_fieldDressing",2},{"ACE_elasticBandage",3},{"ACE_quikclot",3},{"ACE_atropine",1},{"ACE_adenosine",1},{"ACE_CableTie",1},{"ACE_epinephrine",2},{"ACE_MapTools",1},{"MRH_Map",1},{"ACE_morphine",2},{"ACE_packingBandage",3},{"adv_aceSplint_splint",1},{"ACE_tourniquet",2}}},{"CUP_V_PMC_CIRAS_Winter_Patrol",{{"HandGrenade",2,1}}},{"CUP_B_MedicPack_ACU",{{"ToolKit",1},{"MineDetector",1},{"ACE_Cellphone",1},{"ACE_DefusalKit",1},{"APERSBoundingMine_Range_Mag",2,1}}},"rhsusf_opscore_bk","shesh_cover_tan",{"Laserdesignator_01_khk_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_GPNVG_black"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RussiaMercenaries_Rifleman_AT_Winter_01 : O_RussiaMercenaries_Rifleman_AT_Winter_02 {
        author = "Pants";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (AT)";
        side = 0;
        faction = "O_RussiaMercenaries_Winter";

        identityTypes[] = {"Head_Russian","LanguageRUS_F","G_RUS_SF"};

        uniformClass = "milgp_u_fleece_grey_g3_field_pants_mcalpine";

        linkedItems[] = {"CUP_V_PMC_CIRAS_Winter_TL","CUP_H_OpsCore_Grey","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","A3_GPNVG18_BLK_TI"};
        respawnlinkedItems[] = {"CUP_V_PMC_CIRAS_Winter_TL","CUP_H_OpsCore_Grey","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","A3_GPNVG18_BLK_TI"};

        weapons[] = {"hlc_rifle_ak12","launch_MRAWS_white_rail_F","hgun_Rook40_F","Rangefinder"};
        respawnWeapons[] = {"hlc_rifle_ak12","launch_MRAWS_white_rail_F","hgun_Rook40_F","Rangefinder"};

        magazines[] = {"hlc_30Rnd_545x39_B_AK","MRAWS_HEAT_F","16Rnd_9x21_Mag","hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"hlc_30Rnd_545x39_B_AK","MRAWS_HEAT_F","16Rnd_9x21_Mag","hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag"};

        backpack = "Alpine_backpack_kitbag";

        ALiVE_orbatCreator_loadout[] = {{"hlc_rifle_ak12","","CUP_acc_LLM_od","CUP_optic_HensoldtZO_low_RDS",{"hlc_30Rnd_545x39_B_AK",30},{},"rhs_acc_grip_ffg2"},{"launch_MRAWS_white_rail_F","","","",{"MRAWS_HEAT_F",1},{},""},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"milgp_u_fleece_grey_g3_field_pants_mcalpine",{{"ACE_EarPlugs",1},{"ACE_fieldDressing",2},{"ACE_packingBandage",2},{"ACE_morphine",2},{"ACE_tourniquet",2},{"16Rnd_9x21_Mag",1,17},{"hlc_30Rnd_545x39_B_AK",2,30}}},{"CUP_V_PMC_CIRAS_Winter_TL",{{"HandGrenade",3,1},{"SmokeShell",2,1},{"CUP_30Rnd_545x39_AK74M_M",5,30}}},{"Alpine_backpack_kitbag",{{"MRAWS_HEAT_F",2,1},{"CUP_MAAWS_HEDP_M",2,1}}},"CUP_H_OpsCore_Grey","rhssaf_veil_Green",{"Rangefinder","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","A3_GPNVG18_BLK_TI"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RussiaMercenaries_Recon_Rifleman_Winter_01 : O_RussiaMercenaries_JTAC_Winter_01 {
        author = "Pants";
        scope = 2;
        scopeCurator = 2;
        displayName = "Recon Rifleman";
        side = 0;
        faction = "O_RussiaMercenaries_Winter";

        identityTypes[] = {"Head_Enoch","LanguageRUS_F","G_RUS_SF"};

        uniformClass = "Alpine_Crye_Grey_Shirt_Camo";

        linkedItems[] = {"CUP_V_PMC_CIRAS_Winter_TL","TRYK_H_Helmet_Winter","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","CUP_NVG_GPNVG_winter"};
        respawnlinkedItems[] = {"CUP_V_PMC_CIRAS_Winter_TL","TRYK_H_Helmet_Winter","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","CUP_NVG_GPNVG_winter"};

        weapons[] = {"hlc_rifle_ak12","hgun_Rook40_F","Laserdesignator_01_khk_F"};
        respawnWeapons[] = {"hlc_rifle_ak12","hgun_Rook40_F","Laserdesignator_01_khk_F"};

        magazines[] = {"hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","Laserbatteries","hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","Laserbatteries"};
        respawnMagazines[] = {"hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","Laserbatteries","hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","Laserbatteries"};

        ALiVE_orbatCreator_loadout[] = {{"hlc_rifle_ak12","CUP_muzzle_TGPA","CUP_acc_LLM_black","hlc_optic_HensoldtZO_lo_Docter",{"hlc_30Rnd_545x39_B_AK",30},{},"rhs_acc_grip_ffg2"},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"Alpine_Crye_Grey_Shirt_Camo",{{"ACE_fieldDressing",3},{"ACE_packingBandage",3},{"ACE_morphine",2},{"ACE_tourniquet",1},{"ACE_elasticBandage",3},{"ACE_epinephrine",2},{"ACE_MapTools",1},{"MRH_Map",1},{"16Rnd_9x21_Mag",2,17},{"MiniGrenade",1,1},{"Chemlight_red",1,1}}},{"CUP_V_PMC_CIRAS_Winter_TL",{{"MiniGrenade",1,1},{"O_R_IR_Grenade",2,1},{"SmokeShell",1,1},{"SmokeShellRed",1,1},{"Chemlight_red",1,1},{"CUP_30Rnd_545x39_AK74M_M",5,30}}},{},"TRYK_H_Helmet_Winter","",{"Laserdesignator_01_khk_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","CUP_NVG_GPNVG_winter"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RussiaMercenaries_Rifleman_Winter_01 : O_RussiaMercenaries_Recon_Rifleman_Winter_01 {
        author = "Pants";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 0;
        faction = "O_RussiaMercenaries_Winter";

        identityTypes[] = {"Head_Enoch","LanguageRUS_F","G_RUS_SF"};

        uniformClass = "Alpine_Crye_Grey_Shirt_Camo";

        linkedItems[] = {"CUP_V_PMC_CIRAS_Winter_TL","TRYK_H_Helmet_Winter","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","CUP_NVG_GPNVG_winter"};
        respawnlinkedItems[] = {"CUP_V_PMC_CIRAS_Winter_TL","TRYK_H_Helmet_Winter","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","CUP_NVG_GPNVG_winter"};

        weapons[] = {"hlc_rifle_ak12","hgun_Rook40_F","Laserdesignator_01_khk_F"};
        respawnWeapons[] = {"hlc_rifle_ak12","hgun_Rook40_F","Laserdesignator_01_khk_F"};

        magazines[] = {"hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","Laserbatteries","hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","Laserbatteries"};
        respawnMagazines[] = {"hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","Laserbatteries","hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","Laserbatteries"};

        ALiVE_orbatCreator_loadout[] = {{"hlc_rifle_ak12","","CUP_acc_LLM_black","hlc_optic_HensoldtZO_lo_Docter",{"hlc_30Rnd_545x39_B_AK",30},{},"rhs_acc_grip_ffg2"},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"Alpine_Crye_Grey_Shirt_Camo",{{"ACE_fieldDressing",3},{"ACE_packingBandage",3},{"ACE_morphine",2},{"ACE_tourniquet",1},{"ACE_elasticBandage",3},{"ACE_epinephrine",2},{"ACE_MapTools",1},{"MRH_Map",1},{"16Rnd_9x21_Mag",2,17},{"MiniGrenade",1,1},{"Chemlight_red",1,1}}},{"CUP_V_PMC_CIRAS_Winter_TL",{{"MiniGrenade",1,1},{"O_R_IR_Grenade",2,1},{"SmokeShell",1,1},{"SmokeShellRed",1,1},{"Chemlight_red",1,1},{"CUP_30Rnd_545x39_AK74M_M",5,30}}},{},"TRYK_H_Helmet_Winter","rhs_balaclava1_olive",{"Laserdesignator_01_khk_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","CUP_NVG_GPNVG_winter"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RussiaMercenaries_Qilin_Winter_01 : CUP_I_LSV_02_unarmed_ION_OCimport_02 {
        author = "Pants";
        scope = 2;
        scopeCurator = 2;
        displayName = "Qilin";
        side = 0;
        faction = "O_RussiaMercenaries_Winter";
        crew = "O_RussiaMercenaries_Rifleman_Winter_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\CUP\WheeledVehicles\CUP_WheeledVehicles_LSV_02\data\PMC_lsv_02_01_winter_co.paa'];_unit setObjectTextureGlobal [1,'\CUP\WheeledVehicles\CUP_WheeledVehicles_LSV_02\data\PMC_lsv_02_02_winter_co.paa'];_unit setObjectTextureGlobal [2,'\CUP\WheeledVehicles\CUP_WheeledVehicles_LSV_02\data\PMC_lsv_02_03_winter_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "PMC_2";

    };

    class O_RussiaMercenaries_SUV_Winter_01 : CUP_I_SUV_ION_OCimport_02 {
        author = "Pants";
        scope = 2;
        scopeCurator = 2;
        displayName = "SUV";
        side = 0;
        faction = "O_RussiaMercenaries_Winter";
        crew = "O_RussiaMercenaries_Rifleman_Winter_01";

        class Turrets : Turrets {
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
            class CargoTurret_07 : CargoTurret_07 { gunnerType = ""; };
            class CargoTurret_08 : CargoTurret_08 { gunnerType = ""; };
            class CargoTurret_09 : CargoTurret_09 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\CUP\WheeledVehicles\CUP_WheeledVehicles_SUV\data\suv_body_bluewhite_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "CIV";

    };

    class O_RussiaMercenaries_QuadBike_Scout_Winter_01 : I_E_Quadbike_01_F_OCimport_02 {
        author = "Pants";
        scope = 2;
        scopeCurator = 2;
        displayName = "QuadBike Scout";
        side = 0;
        faction = "O_RussiaMercenaries_Winter";
        crew = "O_RussiaMercenaries_Marksman_Winter_01";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\A3\Soft_F_Beta\Quadbike_01\Data\Quadbike_01_CIV_WHITE_CO.paa'];_unit setObjectTextureGlobal [1,'\A3\Soft_F_Beta\Quadbike_01\Data\Quadbike_01_wheel_CIVWHITE_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "White";

    };

    class O_RussiaMercenaries_Assault_Boat_Winter_01 : CUP_O_PBX_RU_OCimport_02 {
        author = "Pants";
        scope = 2;
        scopeCurator = 2;
        displayName = "Assault Boat";
        side = 0;
        faction = "O_RussiaMercenaries_Winter";
        crew = "O_RussiaMercenaries_Recon_Rifleman_Winter_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RussiaMercenaries_Machinegunner_Winter_01 : O_RussiaMercenaries_Autorifleman_Winter_01 {
        author = "Pants";
        scope = 2;
        scopeCurator = 2;
        displayName = "Machinegunner";
        side = 0;
        faction = "O_RussiaMercenaries_Winter";

        identityTypes[] = {"Head_Enoch","LanguageRUS_F","G_RUS_SF"};

        uniformClass = "UK3CB_BAF_U_Smock_Arctic";

        linkedItems[] = {"CUP_V_PMC_CIRAS_Winter_Patrol","TRYK_H_Helmet_Winter","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_GPNVG_winter"};
        respawnlinkedItems[] = {"CUP_V_PMC_CIRAS_Winter_Patrol","TRYK_H_Helmet_Winter","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_GPNVG_winter"};

        weapons[] = {"rhs_weap_m240B","hgun_Rook40_F"};
        respawnWeapons[] = {"rhs_weap_m240B","hgun_Rook40_F"};

        magazines[] = {"rhsusf_100Rnd_762x51","16Rnd_9x21_Mag","rhsusf_100Rnd_762x51","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"rhsusf_100Rnd_762x51","16Rnd_9x21_Mag","rhsusf_100Rnd_762x51","16Rnd_9x21_Mag"};

        backpack = "Alpine_backpack_kitbag";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_m240B","rhsusf_acc_ARDEC_M240","CUP_acc_ANPEQ_2_grey","hlc_optic_HensoldtZO_Hi_Docter",{"rhsusf_100Rnd_762x51",100},{},""},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"UK3CB_BAF_U_Smock_Arctic",{{"ACE_EarPlugs",1},{"ACE_fieldDressing",1},{"ACE_packingBandage",3},{"ACE_morphine",2},{"ACE_tourniquet",2},{"ACE_quikclot",2},{"ACE_elasticBandage",2},{"ACE_atropine",1},{"ACE_adenosine",1},{"ACE_epinephrine",2},{"SmokeShell",1,1}}},{"CUP_V_PMC_CIRAS_Winter_Patrol",{{"16Rnd_9x21_Mag",2,17},{"HandGrenade",1,1},{"SmokeShellRed",1,1},{"Chemlight_red",2,1},{"rhsusf_100Rnd_762x51",2,100}}},{"Alpine_backpack_kitbag",{{"rhsusf_100Rnd_762x51",1,100},{"rhsusf_100Rnd_762x51_m61_ap",1,100},{"CUP_100Rnd_TE4_LRT4_Red_Tracer_762x51_Belt_M",2,100}}},"TRYK_H_Helmet_Winter","rhs_balaclava1_olive",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_GPNVG_winter"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RussiaMercenaries_GAZ_233014_Winter_01 : fsg_tigr_2_OCimport_02 {
        author = "Pants";
        scope = 2;
        scopeCurator = 2;
        displayName = "GAZ-233014";
        side = 0;
        faction = "O_RussiaMercenaries_Winter";
        crew = "O_RussiaMercenaries_Rifleman_Winter_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_RussiaMercenaries_Team_Leader_Winter_02"; };
            class AGS_Turret : AGS_Turret { gunnerType = "O_RussiaMercenaries_Grenadier_Winter_02"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RussiaMercenaries_MATV_Captured_Winter_01 : RCOMM_wnato_mrap_OCimport_02 {
        author = "Pants";
        scope = 2;
        scopeCurator = 2;
        displayName = "MATV (Captured)";
        side = 0;
        faction = "O_RussiaMercenaries_Winter";
        crew = "O_RussiaMercenaries_Rifleman_Winter_01";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RussiaMercenaries_GAZ_M240_Winter_01 : fsg_tigr_3_OCimport_02 {
        author = "Pants";
        scope = 2;
        scopeCurator = 2;
        displayName = "GAZ (M240)";
        side = 0;
        faction = "O_RussiaMercenaries_Winter";
        crew = "O_RussiaMercenaries_Rifleman_Winter_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "O_RussiaMercenaries_Machinegunner_Winter_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'fsg\fsg_vehicles\data\rhs_tigr_co.paa'];_unit setObjectTextureGlobal [1,'fsg\fsg_vehicles\data\rhs_tigr_int_01_co.paa'];_unit setObjectTextureGlobal [2,'rhsafrf\addons\rhs_tigr\data\rhs_tigr_int_02_co.paa'];_unit setObjectTextureGlobal [3,'fsg\fsg_vehicles\data\tigr_ext_ads_co.paa'];_unit setObjectTextureGlobal [4,'rhsafrf\addons\rhs_tigr\m_proxies\data\tigr_m_adds_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "standard";

    };

    class O_RussiaMercenaries_MG_Assistant_Winter_01 : O_RussiaMercenaries_Rifleman_Winter_01 {
        author = "Pants";
        scope = 2;
        scopeCurator = 2;
        displayName = "MG Assistant";
        side = 0;
        faction = "O_RussiaMercenaries_Winter";

        identityTypes[] = {"Head_Enoch","LanguageRUS_F","G_RUS_SF"};

        uniformClass = "Alpine_Crye_Grey_Shirt_Camo";

        linkedItems[] = {"CUP_V_PMC_CIRAS_Winter_TL","TRYK_H_Helmet_Winter","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","CUP_NVG_GPNVG_winter"};
        respawnlinkedItems[] = {"CUP_V_PMC_CIRAS_Winter_TL","TRYK_H_Helmet_Winter","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","CUP_NVG_GPNVG_winter"};

        weapons[] = {"hlc_rifle_ak12","hgun_Rook40_F","Laserdesignator_01_khk_F"};
        respawnWeapons[] = {"hlc_rifle_ak12","hgun_Rook40_F","Laserdesignator_01_khk_F"};

        magazines[] = {"hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","Laserbatteries","hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","Laserbatteries"};
        respawnMagazines[] = {"hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","Laserbatteries","hlc_30Rnd_545x39_B_AK","16Rnd_9x21_Mag","Laserbatteries"};

        backpack = "CUP_B_MedicPack_ACU";

        ALiVE_orbatCreator_loadout[] = {{"hlc_rifle_ak12","","CUP_acc_LLM_black","hlc_optic_HensoldtZO_lo_Docter",{"hlc_30Rnd_545x39_B_AK",30},{},"rhs_acc_grip_ffg2"},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"Alpine_Crye_Grey_Shirt_Camo",{{"ACE_fieldDressing",3},{"ACE_packingBandage",3},{"ACE_morphine",2},{"ACE_tourniquet",1},{"ACE_elasticBandage",3},{"ACE_epinephrine",2},{"ACE_MapTools",1},{"MRH_Map",1},{"16Rnd_9x21_Mag",2,17},{"MiniGrenade",1,1},{"Chemlight_red",1,1}}},{"CUP_V_PMC_CIRAS_Winter_TL",{{"MiniGrenade",1,1},{"O_R_IR_Grenade",2,1},{"SmokeShell",1,1},{"SmokeShellRed",1,1},{"Chemlight_red",1,1},{"CUP_30Rnd_545x39_AK74M_M",5,30}}},{"CUP_B_MedicPack_ACU",{{"rhsusf_100Rnd_762x51",2,100},{"rhsusf_100Rnd_762x51_m62_tracer",1,100},{"rhsusf_100Rnd_762x51_m61_ap",1,100}}},"TRYK_H_Helmet_Winter","G_Balaclava_blk",{"Laserdesignator_01_khk_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","CUP_NVG_GPNVG_winter"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};