// Generated by unRap v1.06 by Kegetys

class CfgPatches {
	class COS_back_pack {
		requiredAddons[] = {"A3_Air_F"};
		requiredVersion = 0.1;
		units[] = {"NonSteerable_Parachute_F", "Steerable_Parachute_F"};
		version = 20-05-2016;
		author = "Sakuraba_and_author_in_credits";
	};
};
