// Generated by unRap v1.06 by Kegetys
// All Recon packs (with antenna) have had the RT-1523G TFAR radio added by Corey with a call function by Dunbar Snackbar. They have had their mass increased by 80 and carrying capacity decreased by 80 to simulate the presence of the radio.

class CfgVehicles {
	class B_Kitbag_Base;	// External class reference
	class B_AssaultPack_mcamo;	// External class reference
	class B_Bergen_Base_F;	// External class reference
	class Steerable_Parachute_F;	// External class reference
	class ParachuteBase;	// External class reference
	class B_Parachute;	// External class reference
	
	class PARA_VOILE_W : Steerable_Parachute_F {
		author = "Sakuraba";
		_generalMacro = PARA_VOILE_W;
		scope = protected;
		displayName = PARA_VOILE_W;
		model = "\COS_back_pack\PARA_VOILE";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"cos_back_pack\data\parachute\Parachute_winter_co.paa"};
	};
	
	class PARA_VOILE : Steerable_Parachute_F {
		author = "Sakuraba";
		_generalMacro = PARA_VOILE;
		scope = protected;
		displayName = PARA_VOILE;
		model = "\COS_back_pack\PARA_VOILE";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"cos_back_pack\data\parachute\Parachute_co.paa"};
	};
	
	class COS_PARACHUTE : B_Parachute {
		author = "";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		_generalMacro = COS_PARACHUTE;
		displayName = ".COS_PARACHUTE";
		model = "\COS_back_pack\COS_PARACHUTE";
		ParachuteClass = PARA_VOILE;
		descriptionShort = "Parachute Backpack";
		hiddenSelections[] = {};
		hiddenSelectionsTextures[] = {};
		hiddenSelectionsMaterials[] = {};
		picture = "\A3\Air_F_Beta\Parachute_01\Data\UI\Portrait_Parachute_01_CA.paa";
		editorPreview = "\Mod\ui\para_preview.jpg";
	};
	
	class PARACHUTE_W : B_Parachute {
		author = "";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		_generalMacro = PARACHUTE_W;
		displayName = ".COS_PARACHUTE_Winter";
		model = "\COS_back_pack\COS_PARACHUTE";
		ParachuteClass = PARA_VOILE_W;
		descriptionShort = "Parachute Backpack";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"cos_back_pack\data\parachute\Parachute_MODEL_co.paa"};
		hiddenSelectionsMaterials[] = {};
		picture = "\A3\Air_F_Beta\Parachute_01\Data\UI\Portrait_Parachute_01_CA.paa";
		editorPreview = "\Mod\ui\para_preview.jpg";
	};
	class Weapon_Bag_Base;	// External class reference
	class Boat_F;	// External class reference
	
	class Rubber_duck_base_F : Boat_F {
		class EventHandlers;	// External class reference
	};
	
	class B_Boat_Transport_01_F : Rubber_duck_base_F {
		class EventHandlers : EventHandlers {
			init = "(_this select 0) execVM ""\COS_back_pack\data\functions\rotate.sqf""";
		};
		
		class assembleInfo {
			assembleto = "";
			base = "";
			displayname = "";
			dissasembleto[] = {"drybag_zodiac_od", "drybag_zodiac_blk"};
			primary = "true";
		};
	};
	
	class B_UAV_01_backpack_F : Weapon_Bag_Base {
		class assembleinfo;	// External class reference
		class EventHandlers;	// External class reference
	};
	
	class drybag_zodiac_od : B_UAV_01_backpack_F {
		author = ".../modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = "drybag_zodiac_od";
		displayName = ".DryBag zodiac Od";
		picture = "";
		model = "\COS_back_pack\drybag";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"cos_back_pack\data\drybag\DryBag_Z_od_co.paa"};
		hiddenSelectionsMaterials[] = {"cos_back_pack\data\drybag\drybag.rvmat"};
		hiddenUnderwaterSelections[] = {"hide"};
		shownUnderwaterSelections[] = {"unhide", "unhide2"};
		hiddenUnderwaterSelectionsTextures[] = {"cos_gilet\data\halo\diver_kit_co.paa", "cos_gilet\data\halo\diver_kit_co.paa", "A3\characters_f\data\visors_ca.paa"};
		maximumLoad = 10;
		mass = 74;
		side = "TWest";
		
		class assembleInfo : assembleinfo {
			assembleto = "B_Boat_Transport_01_F";
			base = "";
			displayname = "Zodiac";
		};
	};
	
	class drybag_zodiac_blk : B_UAV_01_backpack_F {
		author = ".../modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = "drybag_zodiac_blk";
		displayName = ".DryBag zodiac blk";
		picture = "";
		model = "\COS_back_pack\drybag";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"cos_back_pack\data\drybag\DryBag_Z_blk_co.paa"};
		hiddenSelectionsMaterials[] = {"cos_back_pack\data\drybag\drybag.rvmat"};
		hiddenUnderwaterSelections[] = {"hide"};
		shownUnderwaterSelections[] = {"unhide", "unhide2"};
		hiddenUnderwaterSelectionsTextures[] = {"cos_gilet\data\halo\diver_kit_co.paa", "cos_gilet\data\halo\diver_kit_co.paa", "A3\characters_f\data\visors_ca.paa"};
		maximumLoad = 10;
		mass = 74;
		side = "TWest";
		
		class assembleInfo : assembleinfo {
			assembleto = "B_Boat_Transport_01_F";
			base = "";
			displayname = "Zodiac";
		};
	};
	
	class drybag_od : B_AssaultPack_mcamo {
		author = ".../modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = "drybag_od ";
		displayName = ".drybag_od ";
		picture = "\COS_back_pack\data\icon\ic_drybag_OD.ca.paa";
		model = "\COS_back_pack\drybag";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"cos_back_pack\data\drybag\DryBag_od_co.paa"};
		hiddenSelectionsMaterials[] = {"cos_back_pack\data\drybag\drybag.rvmat"};
		hiddenUnderwaterSelections[] = {"hide"};
		shownUnderwaterSelections[] = {"unhide", "unhide2"};
		hiddenUnderwaterSelectionsTextures[] = {"cos_gilet\data\halo\diver_kit_co.paa", "cos_gilet\data\halo\diver_kit_co.paa", "A3\characters_f\data\visors_ca.paa"};
		maximumLoad = 120;
		mass = 33;
	};
	
	class drybag_blk : B_AssaultPack_mcamo {
		author = ".../modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = "drybag_blk";
		displayName = ".drybag_blk";
		picture = "\COS_back_pack\data\icon\ic_drybag_blk.ca.paa";
		model = "\COS_back_pack\drybag";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"cos_back_pack\data\drybag\DryBag_blk_co.paa"};
		hiddenSelectionsMaterials[] = {"cos_back_pack\data\drybag\drybag.rvmat"};
		hiddenUnderwaterSelections[] = {"hide"};
		shownUnderwaterSelections[] = {"unhide", "unhide2"};
		hiddenUnderwaterSelectionsTextures[] = {"cos_gilet\data\halo\diver_kit_co.paa", "cos_gilet\data\halo\diver_kit_co.paa", "A3\characters_f\data\visors_ca.paa"};
		maximumLoad = 120;
		mass = 33;
	};
	
	class BAG_opex_net : B_AssaultPack_mcamo {
		author = ".../modifiedbySakuraba";
		scope = private;
		scopeCurator = 0;
		scopeArsenal = 0;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = "BAG_opex_net ";
		displayName = ".Sac_opex_net";
		picture = "COS_back_pack\data\icon\Sac_assausl_od.paa";
		model = "\COS_back_pack\BAG_opex_net";
		hiddenSelections[] = {};
		hiddenSelectionsTextures[] = {};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 80;
		mass = 20;
	};
	
	class backpack_FLASH_OD : B_AssaultPack_mcamo {
		author = "...../modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = "backpack_FLASH_OD ";
		displayName = ".backpack_FLASH_OD ";
		picture = "COS_back_pack\data\icon\Sac_assausl_od.paa";
		model = "\COS_back_pack\backpack_FLASH";
		hiddenSelections[] = {};
		hiddenSelectionsTextures[] = {};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 80;
		mass = 20;
	};
	
	class backpack_OD : B_AssaultPack_mcamo {
		author = "...../modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = "backpack_OD ";
		displayName = ".backpack_combat_OD ";
		picture = "COS_back_pack\data\icon\Sac_assausl_od.paa";
		model = "\COS_back_pack\backpack";
		hiddenSelections[] = {};
		hiddenSelectionsTextures[] = {};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 80;
		mass = 20;
	};
	
	class backpack_1_OD : B_AssaultPack_mcamo {
		author = "";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = "backpack_1_OD ";
		displayName = ".backpack_standar_OD ";
		picture = "COS_back_pack\data\icon\Sac_assausl_od.paa";
		model = "\COS_back_pack\backpack_1";
		hiddenSelections[] = {};
		hiddenSelectionsTextures[] = {};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 80;
		mass = 20;
	};
	
	class backpack_2_OD : B_AssaultPack_mcamo {
		author = "";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = "backpack_2_OD";
		displayName = ".backpack_personel_OD";
		picture = "COS_back_pack\data\icon\Sac_assausl_od.paa";
		model = "\COS_back_pack\backpack_2";
		hiddenSelections[] = {};
		hiddenSelectionsTextures[] = {};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 80;
		mass = 20;
	};
	
	class backpack_2_TAN : B_AssaultPack_mcamo {
		author = "";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = "backpack_2_TAN";
		displayName = ".backpack_personel_TAN";
		picture = "COS_back_pack\data\icon\Sac_assausl_od.paa";
		model = "\COS_back_pack\backpack_2";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\COS_back_pack\data\Back_PACK\backpack_combat_TAN_co.paa"};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 80;
		mass = 20;
	};
	
	class KIT_BAG_Alpin_OD : B_AssaultPack_mcamo {
		author = "VulKaN/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = "KIT_BAG_Alpin_OD";
		displayName = ".KIT_BAG_Alpin_OD";
		picture = "COS_back_pack\data\icon\Sac_assausl_od.paa";
		model = "\COS_back_pack\KIT_BAG_Alpin";
		hiddenSelections[] = {};
		hiddenSelectionsTextures[] = {};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 160;
		mass = 40;
	};
	
	class KIT_BAG_Alpin_blk : B_AssaultPack_mcamo {
		author = "VulKaN/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = "KIT_BAG_Alpin_blk";
		displayName = ".KIT_BAG_Alpin_blk";
		picture = "COS_back_pack\data\icon\Sac_assausl_od.paa";
		model = "\COS_back_pack\KIT_BAG_Alpin";
		hiddenSelections[] = {"camo", "camo1", "camo3", "camo6"};
		hiddenSelectionsTextures[] = {"cos_back_pack\data\kit_bag\saccorps_blk.co.paa", "cos_back_pack\data\kit_bag\pochelateral_blk.co.paa", "COS_back_pack\data\ASSETS\assets_strap_blk.co.paa", "cos_back_pack\data\kit_bag\KIT_strap_blk.co.paa"};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 160;
		mass = 40;
	};
	
	class KIT_BAG_Alpin_mc : B_AssaultPack_mcamo {
		author = "VulKaN/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = "KIT_BAG_Alpin_mc";
		displayName = ".KIT_BAG_Alpin_mc";
		picture = "COS_back_pack\data\icon\Sac_assausl_od.paa";
		model = "\COS_back_pack\KIT_BAG_Alpin";
		hiddenSelections[] = {"camo", "camo1", "camo3", "camo6"};
		hiddenSelectionsTextures[] = {"cos_back_pack\data\kit_bag\saccorps_MC.co.paa", "cos_back_pack\data\kit_bag\pochelateral_MC.co.paa", "COS_back_pack\data\ASSETS\assets_strap_tan.co.paa", "cos_back_pack\data\kit_bag\KIT_strap_tan.co.paa"};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 160;
		mass = 40;
	};
	
	class KIT_BAG_Alpin_TAN : B_AssaultPack_mcamo {
		author = "VulKaN/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = "KIT_BAG_Alpin_TAN";
		displayName = ".KIT_BAG_Alpin_TAN";
		picture = "COS_back_pack\data\icon\Sac_assausl_od.paa";
		model = "\COS_back_pack\KIT_BAG_Alpin";
		hiddenSelections[] = {"camo", "camo1", "camo3", "camo6"};
		hiddenSelectionsTextures[] = {"cos_back_pack\data\kit_bag\saccorps_TAN.co.paa", "cos_back_pack\data\kit_bag\pochelateral_TAN.co.paa", "COS_back_pack\data\ASSETS\assets_strap_tan.co.paa", "cos_back_pack\data\kit_bag\KIT_strap_tan.co.paa"};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 160;
		mass = 40;
	};
	
	class KIT_BAG_pince_OD : B_AssaultPack_mcamo {
		author = "VulKaN/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = "KIT_BAG_pince_OD";
		displayName = ".KIT_BAG_pince_OD";
		picture = "COS_back_pack\data\icon\Sac_assausl_od.paa";
		model = "\COS_back_pack\KIT_BAG_PINCE";
		hiddenSelections[] = {};
		hiddenSelectionsTextures[] = {};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 160;
		mass = 40;
	};
	
	class KIT_BAG_pince_blk : B_AssaultPack_mcamo {
		author = "VulKaN/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = "KIT_BAG_pince_blk";
		displayName = ".KIT_BAG_pince_blk";
		picture = "COS_back_pack\data\icon\Sac_assausl_od.paa";
		model = "\COS_back_pack\KIT_BAG_PINCE";
		hiddenSelections[] = {"camo", "camo1", "camo3", "camo6"};
		hiddenSelectionsTextures[] = {"cos_back_pack\data\kit_bag\saccorps_blk.co.paa", "cos_back_pack\data\kit_bag\pochelateral_blk.co.paa", "COS_back_pack\data\ASSETS\assets_strap_blk.co.paa", "cos_back_pack\data\kit_bag\KIT_strap_blk.co.paa"};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 160;
		mass = 40;
	};
	
	class KIT_BAG_pince_mc : B_AssaultPack_mcamo {
		author = "VulKaN/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = "KIT_BAG_pince_mc";
		displayName = ".KIT_BAG_pince_mc";
		picture = "COS_back_pack\data\icon\Sac_assausl_od.paa";
		model = "\COS_back_pack\KIT_BAG_PINCE";
		hiddenSelections[] = {"camo", "camo1", "camo3", "camo6"};
		hiddenSelectionsTextures[] = {"cos_back_pack\data\kit_bag\saccorps_MC.co.paa", "cos_back_pack\data\kit_bag\pochelateral_MC.co.paa", "COS_back_pack\data\ASSETS\assets_strap_tan.co.paa", "cos_back_pack\data\kit_bag\KIT_strap_tan.co.paa"};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 160;
		mass = 40;
	};
	
	class KIT_BAG_pince_TAN : B_AssaultPack_mcamo {
		author = "VulKaN/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = "KIT_BAG_pince_TAN";
		displayName = ".KIT_BAG_pince_TAN";
		picture = "COS_back_pack\data\icon\Sac_assausl_od.paa";
		model = "\COS_back_pack\KIT_BAG_PINCE";
		hiddenSelections[] = {"camo", "camo1", "camo3", "camo6"};
		hiddenSelectionsTextures[] = {"cos_back_pack\data\kit_bag\saccorps_TAN.co.paa", "cos_back_pack\data\kit_bag\pochelateral_TAN.co.paa", "COS_back_pack\data\ASSETS\assets_strap_tan.co.paa", "cos_back_pack\data\kit_bag\KIT_strap_tan.co.paa"};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 160;
		mass = 40;
	};
	
	class KIT_BAG_R_OD : B_AssaultPack_mcamo {
		author = "VulKaN/modifiedbySakuraba/modifiedbyCorey";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = KIT_BAG_R_OD;
		displayName = "RT-1523G Recon Kitbag PSO OD";
		picture = "COS_back_pack\data\icon\Sac_assausl_od.paa";
		model = "\COS_back_pack\KIT_BAG_R";
		hiddenSelections[] = {};
		hiddenSelectionsTextures[] = {};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 80; //decreased maximumload by 80, increased mass by 80, so maximumload = 80 and mass = 120 rather than 160 and 40 -- simulates presence of radio
		mass = 120;
		tf_dialogUpdate = "call TFAR_fnc_updateLRDialogToChannel;";
        tf_hasLRradio = 1;
        tf_encryptionCode = "tf_west_radio_code";
        tf_dialog = "rt1523g_radio_dialog";
        tf_subtype = "digital_lr";
	};
	
	class KIT_BAG_R_blk : B_AssaultPack_mcamo {
		author = "VulKaN/modifiedbySakuraba/modifiedbyCorey";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = "KIT_BAG_R_blk";
		displayName = "RT-1523G Recon Kitbag PSO Black";
		picture = "COS_back_pack\data\icon\Sac_assausl_od.paa";
		model = "\COS_back_pack\KIT_BAG_R";
		hiddenSelections[] = {"camo", "camo1", "camo3", "camo6"};
		hiddenSelectionsTextures[] = {"cos_back_pack\data\kit_bag\saccorps_blk.co.paa", "cos_back_pack\data\kit_bag\pochelateral_blk.co.paa", "COS_back_pack\data\ASSETS\assets_strap_blk.co.paa", "cos_back_pack\data\kit_bag\KIT_strap_blk.co.paa"};
		maximumLoad = 80; //decreased maximumload by 80, increased mass by 80, so maximumload = 80 and mass = 120 rather than 160 and 40 -- simulates presence of radio
		mass = 120;
		tf_dialogUpdate = "call TFAR_fnc_updateLRDialogToChannel;";
        tf_hasLRradio = 1;
        tf_encryptionCode = "tf_west_radio_code";
        tf_dialog = "rt1523g_radio_dialog";
        tf_subtype = "digital_lr";
	};
	
	class KIT_BAG_R_MC : B_AssaultPack_mcamo {
		author = "VulKaN/modifiedbySakuraba/modifiedbyCorey";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = KIT_BAG_R_MC;
		displayName = "RT-1523G Recon Kitbag Multicam PSO";
		picture = "COS_back_pack\data\icon\Sac_assausl_od.paa";
		model = "\COS_back_pack\KIT_BAG_R";
		hiddenSelections[] = {"camo", "camo1", "camo3", "camo6"};
		hiddenSelectionsTextures[] = {"cos_back_pack\data\kit_bag\saccorps_MC.co.paa", "cos_back_pack\data\kit_bag\pochelateral_MC.co.paa", "COS_back_pack\data\ASSETS\assets_strap_tan.co.paa", "cos_back_pack\data\kit_bag\KIT_strap_tan.co.paa"};
		maximumLoad = 80; //decreased maximumload by 80, increased mass by 80, so maximumload = 80 and mass = 120 rather than 160 and 40 -- simulates presence of radio
		mass = 120;
		tf_dialogUpdate = "call TFAR_fnc_updateLRDialogToChannel;";
        tf_hasLRradio = 1;
        tf_encryptionCode = "tf_west_radio_code";
        tf_dialog = "rt1523g_radio_dialog";
        tf_subtype = "digital_lr";
	};
	
	class KIT_BAG_R_TAN : B_AssaultPack_mcamo {
		author = "VulKaN/modifiedbySakuraba/modifiedbyCorey";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = KIT_BAG_R_TAN;
		displayName = "RT-1523G Recon Kitbag PSO Tan";
		picture = "COS_back_pack\data\icon\Sac_assausl_od.paa";
		model = "\COS_back_pack\KIT_BAG_R";
		hiddenSelections[] = {"camo", "camo1", "camo3", "camo6"};
		hiddenSelectionsTextures[] = {"cos_back_pack\data\kit_bag\saccorps_TAN.co.paa", "cos_back_pack\data\kit_bag\pochelateral_TAN.co.paa", "COS_back_pack\data\ASSETS\assets_strap_tan.co.paa", "cos_back_pack\data\kit_bag\KIT_strap_tan.co.paa"};
		maximumLoad = 80; //decreased maximumload by 80, increased mass by 80, so maximumload = 80 and mass = 120 rather than 160 and 40 -- simulates presence of radio
		mass = 120;
		tf_dialogUpdate = "call TFAR_fnc_updateLRDialogToChannel;";
        tf_hasLRradio = 1;
        tf_encryptionCode = "tf_west_radio_code";
        tf_dialog = "rt1523g_radio_dialog";
        tf_subtype = "digital_lr";
	};
	
	class KIT_BAG_od : B_AssaultPack_mcamo {
		author = "VulKaN/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = "KIT_BAG_od";
		displayName = ".Kit_Bag_Od";
		picture = "COS_back_pack\data\icon\Sac_assausl_od.paa";
		model = "\COS_back_pack\KIT_BAG";
		hiddenSelections[] = {};
		hiddenSelectionsTextures[] = {};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 160;
		mass = 40;
	};
	
	class KIT_BAG_blk : B_AssaultPack_mcamo {
		author = "VulKaN/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = "KIT_BAG_blk";
		displayName = ".Kit_Bag_blk";
		picture = "COS_back_pack\data\icon\Sac_assausl_od.paa";
		model = "\COS_back_pack\KIT_BAG";
		hiddenSelections[] = {"camo", "camo1", "camo3", "camo6"};
		hiddenSelectionsTextures[] = {"cos_back_pack\data\kit_bag\saccorps_blk.co.paa", "cos_back_pack\data\kit_bag\pochelateral_blk.co.paa", "COS_back_pack\data\ASSETS\assets_strap_blk.co.paa", "cos_back_pack\data\kit_bag\KIT_strap_blk.co.paa"};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 160;
		mass = 40;
	};
	
	class KIT_BAG_MC : B_AssaultPack_mcamo {
		author = "VulKaN/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = KIT_BAG_MC;
		displayName = ".Kit_Bag_MC";
		picture = "COS_back_pack\data\icon\Sac_assausl_od.paa";
		model = "\COS_back_pack\KIT_BAG";
		hiddenSelections[] = {"camo", "camo1", "camo3", "camo6"};
		hiddenSelectionsTextures[] = {"cos_back_pack\data\kit_bag\saccorps_MC.co.paa", "cos_back_pack\data\kit_bag\pochelateral_MC.co.paa", "COS_back_pack\data\ASSETS\assets_strap_tan.co.paa", "cos_back_pack\data\kit_bag\KIT_strap_tan.co.paa"};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 160;
		mass = 40;
	};
	
	class KIT_BAG_TAN : B_AssaultPack_mcamo {
		author = "VulKaN/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = KIT_BAG_TAN;
		displayName = ".Kit_Bag_TAN";
		picture = "COS_back_pack\data\icon\Sac_assausl_od.paa";
		model = "\COS_back_pack\KIT_BAG";
		hiddenSelections[] = {"camo", "camo1", "camo3", "camo6"};
		hiddenSelectionsTextures[] = {"cos_back_pack\data\kit_bag\saccorps_TAN.co.paa", "cos_back_pack\data\kit_bag\pochelateral_TAN.co.paa", "COS_back_pack\data\ASSETS\assets_strap_tan.co.paa", "cos_back_pack\data\kit_bag\KIT_strap_tan.co.paa"};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 160;
		mass = 40;
	};
	
	class SOG_BAG_OD : B_AssaultPack_mcamo {
		author = "VulKaN/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = SOG_BAG_OD;
		displayName = ".SF_Backpack_od";
		picture = "COS_back_pack\data\icon\sac_fs.paa";
		model = "\COS_back_pack\SOG_BAG";
		hiddenSelections[] = {"camo", "camo3"};
		hiddenSelectionsTextures[] = {"\COS_back_pack\data\SOG_BACKPACK\SOG_BAG_OD_co.paa", "cos_back_pack\data\assets\assets_strap.co.paa"};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 120;
		mass = 30;
	};
	
	class SOG_BAG_tan : B_AssaultPack_mcamo {
		author = "VulKaN/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = "SOG_BAG_tan";
		displayName = ".SF_Backpack_tan";
		picture = "COS_back_pack\data\icon\sac_fs.paa";
		model = "\COS_back_pack\SOG_BAG";
		hiddenSelections[] = {"camo", "camo3"};
		hiddenSelectionsTextures[] = {"\COS_back_pack\data\SOG_BACKPACK\SOG_BAG_TAN_co.paa", "cos_back_pack\data\assets\assets_strap_tan.co.paa"};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 120;
		mass = 30;
	};
	
	class SOG_BAG_blk : B_AssaultPack_mcamo {
		author = "VulKaN/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = "SOG_BAG_blk";
		displayName = ".SF_Backpack_blk";
		picture = "COS_back_pack\data\icon\sac_fs.paa";
		model = "\COS_back_pack\SOG_BAG";
		hiddenSelections[] = {"camo", "camo3"};
		hiddenSelectionsTextures[] = {"\COS_back_pack\data\SOG_BACKPACK\sog_bag_blk_co.paa", "cos_back_pack\data\assets\assets_strap_blk.co.paa"};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 120;
		mass = 30;
	};
	
	class SOG_BAG_MC : B_AssaultPack_mcamo {
		author = "VulKaN/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = SOG_BAG_MC;
		displayName = ".SF_Backpack_MC";
		picture = "COS_back_pack\data\icon\sac_fs.paa";
		model = "\COS_back_pack\SOG_BAG";
		hiddenSelections[] = {"camo", "camo3"};
		hiddenSelectionsTextures[] = {"\COS_back_pack\data\SOG_BACKPACK\SOG_BAG_MC_co.paa", "cos_back_pack\data\assets\assets_strap_tan.co.paa"};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 120;
		mass = 30;
	};
	
	class SOG_BAG_BREACHER_od : B_AssaultPack_mcamo {
		author = "VulKaN/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = "SOG_BAG_BREACHER_od";
		displayName = ".SF_Backpack_Breacher_od";
		picture = "COS_back_pack\data\icon\sac_fs.paa";
		model = "\COS_back_pack\SOG_BAG_BREACHER";
		hiddenSelections[] = {"camo", "camo3"};
		hiddenSelectionsTextures[] = {"\COS_back_pack\data\SOG_BACKPACK\SOG_BAG_OD_co.paa", "cos_back_pack\data\assets\assets_strap.co.paa"};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 120;
		mass = 30;
	};
	
	class SOG_BAG_BREACHER_tan : B_AssaultPack_mcamo {
		author = "VulKaN/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = "SOG_BAG_BREACHER_tan";
		displayName = ".SF_Backpack_Breacher_tan";
		picture = "COS_back_pack\data\icon\sac_fs.paa";
		model = "\COS_back_pack\SOG_BAG_BREACHER";
		hiddenSelections[] = {"camo", "camo3"};
		hiddenSelectionsTextures[] = {"\COS_back_pack\data\SOG_BACKPACK\SOG_BAG_TAN_co.paa", "cos_back_pack\data\assets\assets_strap_tan.co.paa"};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 120;
		mass = 30;
	};
	
	class SOG_BAG_BREACHER_blk : B_AssaultPack_mcamo {
		author = "VulKaN/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = "SOG_BAG_BREACHER_blk";
		displayName = ".SF_Backpack_Breacher_blk";
		picture = "COS_back_pack\data\icon\sac_fs.paa";
		model = "\COS_back_pack\SOG_BAG_BREACHER";
		hiddenSelections[] = {"camo", "camo3"};
		hiddenSelectionsTextures[] = {"\COS_back_pack\data\SOG_BACKPACK\sog_bag_blk_co.paa", "cos_back_pack\data\assets\assets_strap_blk.co.paa"};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 120;
		mass = 30;
	};
	
	class SOG_BAG_BREACHER_MC : B_AssaultPack_mcamo {
		author = "VulKaN/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = SOG_BAG_BREACHER_MC;
		displayName = ".SF_Backpack_Breacher_MC";
		picture = "COS_back_pack\data\icon\sac_fs.paa";
		model = "\COS_back_pack\SOG_BAG_BREACHER";
		hiddenSelections[] = {"camo", "camo3"};
		hiddenSelectionsTextures[] = {"\COS_back_pack\data\SOG_BACKPACK\SOG_BAG_MC_co.paa", "cos_back_pack\data\assets\assets_strap_tan.co.paa"};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 120;
		mass = 30;
	};
	
	class SOG_BAG_recon_od : B_AssaultPack_mcamo {
		author = "VulKaN/modifiedbySakuraba/modifiedbyCorey";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = "SOG_BAG_recon_od";
		displayName = "RT-1523G Recon SFF PSO OD";
		picture = "COS_back_pack\data\icon\sac_fs.paa";
		model = "\COS_back_pack\SOG_BAG_recon";
		hiddenSelections[] = {"camo", "camo3"};
		hiddenSelectionsTextures[] = {"\COS_back_pack\data\SOG_BACKPACK\SOG_BAG_OD_co.paa", "cos_back_pack\data\assets\assets_strap.co.paa"};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 40; //from 120 load and 30 mass to 40 load and 110 mass (change of 80 to simulate radio)
		mass = 110;
		tf_dialogUpdate = "call TFAR_fnc_updateLRDialogToChannel;";
        tf_hasLRradio = 1;
        tf_encryptionCode = "tf_west_radio_code";
        tf_dialog = "rt1523g_radio_dialog";
        tf_subtype = "digital_lr";
	};
	
	class SOG_BAG_recon_tan : B_AssaultPack_mcamo {
		author = "VulKaN/modifiedbySakuraba/modifiedbyCorey";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = "SOG_BAG_recon_tan";
		displayName = "RT-1523G Recon SFF PSO Tan";
		picture = "COS_back_pack\data\icon\sac_fs.paa";
		model = "\COS_back_pack\SOG_BAG_recon";
		hiddenSelections[] = {"camo", "camo3"};
		hiddenSelectionsTextures[] = {"\COS_back_pack\data\SOG_BACKPACK\SOG_BAG_TAN_co.paa", "cos_back_pack\data\assets\assets_strap_tan.co.paa"};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 40; //from 120 load and 30 mass to 40 load and 110 mass (change of 80 to simulate radio)
		mass = 110;
		tf_dialogUpdate = "call TFAR_fnc_updateLRDialogToChannel;";
        tf_hasLRradio = 1;
        tf_encryptionCode = "tf_west_radio_code";
        tf_dialog = "rt1523g_radio_dialog";
        tf_subtype = "digital_lr";
	};
	
	class SOG_BAG_recon_blk : B_AssaultPack_mcamo {
		author = "VulKaN/modifiedbySakuraba/modifiedbyCorey";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = "SOG_BAG_recon_blk";
		displayName = "RT-1523G Recon SFF PSO Black";
		picture = "COS_back_pack\data\icon\sac_fs.paa";
		model = "\COS_back_pack\SOG_BAG_recon";
		hiddenSelections[] = {"camo", "camo3"};
		hiddenSelectionsTextures[] = {"\COS_back_pack\data\SOG_BACKPACK\sog_bag_blk_co.paa", "cos_back_pack\data\assets\assets_strap_blk.co.paa"};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 40; //from 120 load and 30 mass to 40 load and 110 mass (change of 80 to simulate radio)
		mass = 110;
		tf_dialogUpdate = "call TFAR_fnc_updateLRDialogToChannel;";
        tf_hasLRradio = 1;
        tf_encryptionCode = "tf_west_radio_code";
        tf_dialog = "rt1523g_radio_dialog";
        tf_subtype = "digital_lr";
	};
	
	class SOG_BAG_recon_MC : B_AssaultPack_mcamo {
		author = "VulKaN/modifiedbySakuraba/modifiedbyCorey";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = "SOG_BAG_recon_MC";
		displayName = "RT-1523G Recon SFF PSO Multicam";
		picture = "COS_back_pack\data\icon\sac_fs.paa";
		model = "\COS_back_pack\SOG_BAG_recon";
		hiddenSelections[] = {"camo", "camo3"};
		hiddenSelectionsTextures[] = {"\COS_back_pack\data\SOG_BACKPACK\SOG_BAG_MC_co.paa", "cos_back_pack\data\assets\assets_strap_tan.co.paa"};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 40; //from 120 load and 30 mass to 40 load and 110 mass (change of 80 to simulate radio)
		mass = 110;
		tf_dialogUpdate = "call TFAR_fnc_updateLRDialogToChannel;";
        tf_hasLRradio = 1;
        tf_encryptionCode = "tf_west_radio_code";
        tf_dialog = "rt1523g_radio_dialog";
        tf_subtype = "digital_lr";
	};
	
	class SOG_BAG_med_od : B_AssaultPack_mcamo {
		author = "VulKaN/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = "SOG_BAG_med_od";
		displayName = ".SF_Backpack_med_od";
		picture = "COS_back_pack\data\icon\sac_fs.paa";
		model = "\COS_back_pack\SOG_BAG_med";
		hiddenSelections[] = {"camo", "camo3"};
		hiddenSelectionsTextures[] = {"\COS_back_pack\data\SOG_BACKPACK\SOG_BAG_OD_co.paa", "cos_back_pack\data\assets\assets_strap.co.paa"};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 120;
		mass = 30;
	};
	
	class SOG_BAG_med_tan : B_AssaultPack_mcamo {
		author = "VulKaN/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = "SOG_BAG_med_tan";
		displayName = ".SF_Backpack_med_tan";
		picture = "COS_back_pack\data\icon\sac_fs.paa";
		model = "\COS_back_pack\SOG_BAG_med";
		hiddenSelections[] = {"camo", "camo3"};
		hiddenSelectionsTextures[] = {"\COS_back_pack\data\SOG_BACKPACK\SOG_BAG_TAN_co.paa", "cos_back_pack\data\assets\assets_strap_tan.co.paa"};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 120;
		mass = 30;
	};
	
	class SOG_BAG_med_blk : B_AssaultPack_mcamo {
		author = "VulKaN/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = "SOG_BAG_med_blk";
		displayName = ".SF_Backpack_med_blk";
		picture = "COS_back_pack\data\icon\sac_fs.paa";
		model = "\COS_back_pack\SOG_BAG_med";
		hiddenSelections[] = {"camo", "camo3"};
		hiddenSelectionsTextures[] = {"\COS_back_pack\data\SOG_BACKPACK\sog_bag_blk_co.paa", "cos_back_pack\data\assets\assets_strap_blk.co.paa"};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 120;
		mass = 30;
	};
	
	class SOG_BAG_med_MC : B_AssaultPack_mcamo {
		author = "VulKaN/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = "SOG_BAG_med_MC";
		displayName = ".SF_Backpack_med_MC";
		picture = "COS_back_pack\data\icon\sac_fs.paa";
		model = "\COS_back_pack\SOG_BAG_med";
		hiddenSelections[] = {"camo", "camo3"};
		hiddenSelectionsTextures[] = {"\COS_back_pack\data\SOG_BACKPACK\SOG_BAG_MC_co.paa", "cos_back_pack\data\assets\assets_strap_tan.co.paa"};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 120;
		mass = 30;
	};
	
	class SOG_BAG_ALPIN_od : B_AssaultPack_mcamo {
		author = "VulKaN/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = "SOG_BAG_ALPIN_od";
		displayName = ".SF_Backpack_bush_od";
		picture = "COS_back_pack\data\icon\sac_fs.paa";
		model = "\COS_back_pack\SOG_BAG_ALPIN";
		hiddenSelections[] = {"camo", "camo3"};
		hiddenSelectionsTextures[] = {"\COS_back_pack\data\SOG_BACKPACK\SOG_BAG_OD_co.paa", "cos_back_pack\data\assets\assets_strap.co.paa"};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 120;
		mass = 30;
	};
	
	class SOG_BAG_ALPIN_tan : B_AssaultPack_mcamo {
		author = "VulKaN/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = "SOG_BAG_ALPIN_tan";
		displayName = ".SF_Backpack_bush_tan";
		picture = "COS_back_pack\data\icon\sac_fs.paa";
		model = "\COS_back_pack\SOG_BAG_ALPIN";
		hiddenSelections[] = {"camo", "camo3"};
		hiddenSelectionsTextures[] = {"\COS_back_pack\data\SOG_BACKPACK\SOG_BAG_TAN_co.paa", "cos_back_pack\data\assets\assets_strap_tan.co.paa"};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 120;
		mass = 30;
	};
	
	class SOG_BAG_ALPIN_blk : B_AssaultPack_mcamo {
		author = "VulKaN/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = "SOG_BAG_ALPIN_blk";
		displayName = ".SF_Backpack_bush_blk";
		picture = "COS_back_pack\data\icon\sac_fs.paa";
		model = "\COS_back_pack\SOG_BAG_ALPIN";
		hiddenSelections[] = {"camo", "camo3"};
		hiddenSelectionsTextures[] = {"\COS_back_pack\data\SOG_BACKPACK\sog_bag_blk_co.paa", "cos_back_pack\data\assets\assets_strap_blk.co.paa"};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 120;
		mass = 30;
	};
	
	class SOG_BAG_ALPIN_MC : B_AssaultPack_mcamo {
		author = "VulKaN/modifiedbySakuraba";
		scope = public;
		scopeCurator = 2;
		scopeArsenal = 2;
		icon = "iconBackpack";
		transportMaxWeapons = 1;
		transportMaxMagazines = 20;
		isbackpack = 1;
		reversed = true;
		mapSize = 2;
		vehicleClass = "Backpacks";
		allowedSlots[] = {901};
		_generalMacro = SOG_BAG_ALPIN_MC;
		displayName = ".SF_Backpack_bush_MC";
		picture = "COS_back_pack\data\icon\sac_fs.paa";
		model = "\COS_back_pack\SOG_BAG_ALPIN";
		hiddenSelections[] = {"camo", "camo3"};
		hiddenSelectionsTextures[] = {"\COS_back_pack\data\SOG_BACKPACK\SOG_BAG_MC_co.paa", "cos_back_pack\data\assets\assets_strap_tan.co.paa"};
		hiddenSelectionsMaterials[] = {};
		maximumLoad = 120;
		mass = 30;
	};
	class NATO_Box_Base;	// External class reference
	
	class COS_BOX_HALO : NATO_Box_Base {
		scope = public;
		vehicleClass = "Ammo";
		displayName = "equipement";
		model = "\COS_back_pack\COS_BOX_HALO";
		icon = "iconCrateWpns";
		
		class TransportWeapons {};
		
		class TransportMagazines {};
		
		class TransportItems {
			class _xx_SCUBA_PARACHUTE {
				name = SCUBA_PARACHUTE;
				count = 10;
			};
			
			class _xx_PARACHUTE {
				name = PARACHUTE;
				count = 10;
			};
			
			class _xx_COS_PARACHUTE {
				name = COS_PARACHUTE;
				count = 10;
			};
			
			class _xx_PARACHUTE_W {
				name = PARACHUTE_W;
				count = 10;
			};
			
			class _xx_GOGGLE_PARA {
				name = GOGGLE_PARA;
				count = 10;
			};
			
			class _xx_BALA_SWAT_BLK {
				name = BALA_SWAT_BLK;
				count = 10;
			};
			
			class _xx_BALA_SWAT_OD {
				name = BALA_SWAT_OD;
				count = 10;
			};
			
			class _xx_mask_HALO {
				name = "mask_HALO";
				count = 10;
			};
			
			class _xx_ABS_Base_Jump_GREY {
				name = "ABS_Base_Jump_GREY";
				count = 10;
			};
			
			class _xx_halo_vest_L {
				name = "halo_vest_L";
				count = 10;
			};
			
			class _xx_ABS_Base_Jump_IR_grey {
				name = "ABS_Base_Jump_IR_grey";
				count = 10;
			};
			
			class _xx_HALO_MARITIME {
				name = HALO_MARITIME;
				count = 10;
			};
			
			class _xx_HALO_MOWHAK {
				name = HALO_MOWHAK;
				count = 10;
			};
		};
	};
	
	class COS_BOX_DIVER : NATO_Box_Base {
		scope = public;
		vehicleClass = "Ammo";
		displayName = "equipement plongeur";
		model = "\COS_back_pack\COS_BOX_DIVER";
		icon = "iconCrateWpns";
		
		class TransportWeapons {};
		
		class TransportMagazines {};
		
		class TransportItems {
			class _xx_drybag_blk {
				name = "drybag_blk";
				count = 10;
			};
			
			class _xx_drybag_zodiac_blk {
				name = "drybag_zodiac_blk";
				count = 10;
			};
			
			class _xx_DIVER_MASK {
				name = DIVER_MASK;
				count = 10;
			};
			
			class _xx_RECYCLEUR_FULL_TL {
				name = RECYCLEUR_FULL_TL;
				count = 10;
			};
			
			class _xx_13_RDP_SUIT {
				name = 13_RDP_SUIT;
				count = 10;
			};
			
			class _xx_Sotg_DIVER_1_CE {
				name = "Sotg_DIVER_1_CE";
				count = 10;
			};
			
			class _xx_Sotg_DIVER_1_Daguet {
				name = "Sotg_DIVER_1_Daguet";
				count = 10;
			};
			
			class _xx_ABS_Base_Jump_GREY {
				name = "ABS_Base_Jump_GREY";
				count = 10;
			};
			
			class _xx_ABS_Base_Jump_BLK {
				name = "ABS_Base_Jump_BLK ";
				count = 10;
			};
		};
	};
};
