// config.bin - 03:31:10 08/26/19, generated in 0.13 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Enabled, Automatic comments: Enabled

#define private		0
#define protected		1
#define public		2

#define true	1
#define false	0

class DefaultEventhandlers;	// External class reference
#include "CfgPatches.hpp"
#include "UniformSlotInfo.hpp"
#include "CfgVehicles.hpp"
#include "cfgMods.hpp"
